services:
  backend:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"

  postgres:
    ports:
      - "5432:5432"

  frontend:
    ports:
      - "3000:3000"
