"""Domande suggerite di default per l'assistente.
Seed idempotente (italiano) per il pulsante "Prepara domanda" della pagina
/assistente. I topic combaciano con i TOPIC_IDS del frontend, organizzati
per le 4 basi di conoscenza (Guida, Framework, Questionari, CounselorBot).
Ogni topic ha 20 domande. Le altre lingue ricadono sulle varianti i18n.
"""

DEFAULT_ASSISTANT_QUESTIONS: dict[str, list[str]] = {
    # --- Guida (competenzestrategiche) ---
    "cs_strumenti": [
        "Che cos'e' il progetto competenzestrategiche.it e quali strumenti offre?",
        "Quali questionari sono disponibili su competenzestrategiche.it?",
        "Come si accede ai questionari su competenzestrategiche.it?",
        "Qual e' la guida ufficiale per usare la piattaforma?",
        "A chi si rivolge il progetto competenzestrategiche.it?",
        "Cosa distingue il QSA dagli altri questionari del progetto?",
        "Quali sono i passaggi per somministrare un questionario?",
        "Come si ottiene un profilo dopo aver compilato un questionario?",
        "Che tipo di report viene generato dopo la compilazione?",
        "Come si interpretano i risultati di un questionario?",
        "Quali materiali di supporto offre il progetto?",
        "Dove trovo le istruzioni per compilare i questionari?",
        "Come funziona il libretto dello studente?",
        "Quali strumenti sono disponibili anche in lingua straniera?",
        "Come si richiede l'accesso per una scuola o un ente?",
        "Qual e' la procedura per una somministrazione collettiva?",
        "Cosa serve per iniziare un percorso di autovalutazione?",
        "Quali sono i requisiti tecnici per usare la piattaforma?",
        "Come si contatta il team del progetto per assistenza?",
        "Dove trovo esempi di profili gia' compilati?",
    ],
    "cs_metodologia": [
        "Qual e' la metodologia alla base del progetto competenzestrategiche.it?",
        "Come e' nato il progetto e chi lo ha sviluppato?",
        "Quali sono i fondamenti pedagogici degli strumenti?",
        "Come si colloca il progetto nel panorama dell'orientamento?",
        "Che cos'e' l'autovalutazione delle competenze strategiche?",
        "Quali sono le fasi di un percorso di counseling con questi strumenti?",
        "Come si integra la piattaforma nella didattica curricolare?",
        "Quali evidenze scientifiche supportano l'uso del QSA?",
        "Come si forma un docente all'uso degli strumenti?",
        "Quali sono le buone pratiche per la somministrazione?",
        "Come si personalizza il percorso in base al profilo dello studente?",
        "Che ruolo ha il formatore nel percorso di autovalutazione?",
        "Quali sono i limiti e le cautele nell'uso degli strumenti?",
        "Come si misura l'efficacia di un percorso di counseling?",
        "Quali competenze sviluppa lo studente con questi strumenti?",
        "Come si inserisce il progetto nel quadro delle competenze chiave europee?",
        "Qual e' il modello teorico di riferimento per le competenze strategiche?",
        "Come si distingue l'orientamento formativo da quello professionale?",
        "Quali sinergie ci sono tra il progetto e il mondo della formazione professionale?",
        "Come si valutano i progressi dello studente nel tempo?",
    ],

    # --- Framework ---
    "fw_teoria": [
        "Cosa sono le competenze strategiche secondo il modello Pellerey?",
        "Qual e' la differenza tra competenze cognitive e affettivo-motivazionali?",
        "Che cos'e' l'autoregolazione nell'apprendimento?",
        "Cosa si intende per autodeterminazione nello studio e nel lavoro?",
        "Qual e' il ruolo della metacognizione nelle competenze strategiche?",
        "Come si collegano soft skill e competenze strategiche?",
        "Che cos'e' la teoria dell'apprendimento autoregolato di Zimmerman?",
        "Quali sono le fasi del processo di autoregolazione?",
        "Come influisce la prospettiva temporale sulle scelte di carriera?",
        "Che cos'e' il modello Life Design di Savickas?",
        "Qual e' il rapporto tra competenze strategiche e occupabilita'?",
        "Cosa sono le funzioni esecutive e come si collegano all'apprendimento?",
        "Qual e' il contributo di Heckman sulle character skills?",
        "Come si definisce l'identita' professionale in ottica narrativa?",
        "Quali sono le dimensioni morali e spirituali delle competenze strategiche?",
        "Che cos'e' la teoria delle attribuzioni causali di Weiner?",
        "Come si collega l'autovalutazione allo sviluppo delle competenze?",
        "Qual e' il ruolo del portfolio digitale nella riflessione su di se'?",
        "Cosa si intende per apprendimento permanente (lifelong learning)?",
        "Quali sono gli otto ambiti di competenza strategica?",
    ],
    "fw_articoli": [
        "Quali pubblicazioni recenti ci sono sulle competenze strategiche?",
        "Dove posso trovare gli studi di validazione del QSA?",
        "Quali convegni ha organizzato il gruppo di ricerca?",
        "Che risultati ha prodotto la ricerca-intervento CNOS-FAP?",
        "Quali articoli trattano l'adattamento dello ZTPI al contesto italiano?",
        "Dove sono pubblicati gli atti del convegno del 2019?",
        "Quali studi riguardano il QSAr nella scuola secondaria di primo grado?",
        "Che cosa contiene il volume Dirigere se stessi del 2020?",
        "Quali ricerche collegano competenze strategiche e dispersione scolastica?",
        "Dove trovo gli studi sul portfolio digitale e l'autovalutazione?",
        "Quali pubblicazioni trattano il tema soft skill e orientamento?",
        "Che risultati ha prodotto la sperimentazione con Mahara?",
        "Quali studi hanno validato il QPCC?",
        "Dove sono documentati i dati normativi degli strumenti?",
        "Quali articoli descrivono la piattaforma competenzestrategiche.it?",
        "Che cosa contengono gli atti del convegno 2025?",
        "Quali pubblicazioni riguardano l'uso didattico degli strumenti?",
        "Dove trovo studi che confrontano QSA e altri questionari?",
        "Quali ricerche internazionali citano il modello Pellerey?",
        "Che studi esistono sull'efficacia dei percorsi di counseling?",
    ],
    "fw_autori": [
        "Chi e' Michele Pellerey e qual e' il suo contributo?",
        "Qual e' il ruolo di Massimo Margottini nel progetto?",
        "Chi e' Enrica Ottone e di cosa si occupa?",
        "Qual e' il contributo di Dariusz Grzadziel?",
        "Chi e' Filippo Epifani e quale ruolo ha nella piattaforma?",
        "Quali autori hanno collaborato alla guida all'uso della piattaforma?",
        "Chi ha curato il volume Dirigere se stessi del 2020?",
        "Quali istituzioni sono coinvolte nel progetto?",
        "Che cos'e' il CNOS-FAP e qual e' il suo ruolo?",
        "Qual e' il contributo dell'Universita' Roma Tre?",
        "Che ruolo ha l'Universita' Pontificia Salesiana nel progetto?",
        "Chi sono gli autori degli studi su soft skill e orientamento?",
        "Quali ricercatori hanno lavorato sulla validazione degli strumenti?",
        "Chi ha sviluppato la piattaforma competenzestrategiche.it?",
        "Quali autori hanno contribuito agli atti dei convegni?",
        "Chi sono i curatori della guida del 2023?",
        "Quali formatori sono accreditati per l'uso degli strumenti?",
        "Chi ha scritto le schede fattori del QSA?",
        "Quali autori italiani hanno adattato lo ZTPI?",
        "Chi sono i referenti per la ricerca-intervento nelle scuole?",
    ],

    # --- Questionari ---
    "q_strumenti": [
        "Come e' strutturato il QSA e quanti item ha?",
        "Qual e' la differenza tra QSA e QSAr?",
        "Quanti fattori ha il QSA e come si chiamano?",
        "Quali sono i fattori cognitivi del QSA?",
        "Quali sono i fattori affettivo-motivazionali del QSA?",
        "Come e' strutturato lo ZTPI e quante dimensioni misura?",
        "Qual e' la scala di risposta dei questionari?",
        "Cosa misura il questionario QPCS?",
        "Quali fattori compongono il QPCC?",
        "Cosa valuta il QAP e da quale modello deriva?",
        "Quanti item ha il QSAr e quali fattori misura?",
        "Qual e' la differenza tra QPCS e QPCC?",
        "Come funziona il colloquio narrativo di Savickas?",
        "A che eta' si possono somministrare i diversi questionari?",
        "Quali questionari sono autosomministrati e quali guidati?",
        "In quali lingue sono disponibili i questionari?",
        "Quanto tempo richiede la compilazione di ciascuno strumento?",
        "Quali questionari hanno item a risposta multipla?",
        "Cosa distingue un questionario self-report da un'intervista?",
        "Quali strumenti sono adatti a un percorso di orientamento?",
    ],
    "q_fattori": [
        "Cosa misura il fattore C1 - Strategie elaborative?",
        "Cosa significa autoregolazione nel fattore C2?",
        "Che cos'e' il fattore C3 - Disorientamento?",
        "Cosa misura C4 - Disponibilita' alla collaborazione?",
        "Cosa sono gli organizzatori semantici nel fattore C5?",
        "Cosa indica il fattore C6 - Difficolta' di concentrazione?",
        "Che cos'e' l'autointerrogazione nel fattore C7?",
        "Cosa misura A1 - Ansieta' di base?",
        "Che cos'e' la volizione nel fattore A2?",
        "Cosa sono le attribuzioni causali in A3?",
        "Cosa misura A4 - Attribuzione a cause incontrollabili?",
        "Che cos'e' la mancanza di perseveranza in A5?",
        "Cosa indica A6 - Percezione di competenza?",
        "Che cos'e' l'interferenza emotiva in A7?",
        "Quali fattori del QSA sono invertiti e perche'?",
        "Come si interpreta un punteggio alto in un fattore invertito?",
        "Cosa significano le 5 dimensioni temporali dello ZTPI?",
        "Quali dimensioni ZTPI sono considerate a rischio?",
        "Come si interpreta un profilo ZTPI sbilanciato?",
        "Cosa significa prospettiva temporale bilanciata?",
    ],
    "q_scoring": [
        "Come si calcolano le stanine a partire dai punteggi grezzi?",
        "Qual e' la differenza tra punteggio grezzo e stanina?",
        "Quali sono le fasce normative per i fattori QSA?",
        "Cosa significa che un fattore ha una stanina tra 1 e 3?",
        "Come si interpreta una stanina tra 7 e 9?",
        "Qual e' il significato della fascia media (stanine 4-6)?",
        "Come si gestisce lo scoring dei fattori invertiti?",
        "Perche' i fattori invertiti vanno interpretati al contrario?",
        "Come si calcola il profilo complessivo a partire dai fattori?",
        "Quali formule psicometriche si usano per la validazione?",
        "Che cos'e' l'Alpha di Cronbach e perche' e' importante?",
        "Cosa misura l'Omega di McDonald?",
        "Che cos'e' l'RMSEA e cosa indica in una CFA?",
        "Qual e' il significato del CFI nella validazione?",
        "Come si costruiscono le norme di riferimento?",
        "Quanti soggetti servono per costruire norme affidabili?",
        "Come si verifica l'invarianza di misura tra gruppi?",
        "Cosa significa validita' convergente e discriminante?",
        "Come si valuta l'affidabilita' test-retest?",
        "Quali sono i criteri per considerare validato uno strumento?",
    ],

    # --- CounselorBot ---
    "cb_piattaforma": [
        "Che cos'e' CounselorBot e come funziona?",
        "Qual e' la differenza tra CounselorBot e competenzestrategiche.it?",
        "Come si accede a CounselorBot?",
        "Quali ruoli esistono sulla piattaforma?",
        "In quali lingue posso usare CounselorBot?",
        "Come funziona la chat guidata con il counselor AI?",
        "Che cos'e' il profilo dello studente (open learner model)?",
        "Come posso usare il portfolio su CounselorBot?",
        "A cosa serve il libretto dello studente?",
        "Che cos'e' l'analisi combinata dei questionari?",
        "Come funziona l'esperienza OpenCode?",
        "Che cos'e' il pQBL (pure Question-Based Learning)?",
        "Come si carica un profilo da PDF o foto?",
        "E' possibile usare i questionari in italiano?",
        "Come funziona l'assistente informativo?",
        "Quali sono le differenze tra chat guidata e assistente?",
        "Come si tiene traccia delle sessioni passate?",
        "Posso eliminare una sessione o un profilo?",
        "Come funziona l'autenticazione sulla piattaforma?",
        "Quali dati vengono salvati e per quanto tempo?",
    ],
    "cb_strumenti": [
        "Quali questionari posso usare su CounselorBot?",
        "Qual e' la differenza tra QSA, QSAr e ZTPI?",
        "A cosa serve il questionario QPCS?",
        "Che cos'e' il QPCC e a chi si rivolge?",
        "Cosa misura il QAP?",
        "Come funziona il colloquio Savickas su CounselorBot?",
        "Quali questionari posso compilare direttamente sulla piattaforma?",
        "Come si inseriscono i punteggi manualmente?",
        "Posso caricare un profilo gia' ottenuto su competenzestrategiche.it?",
        "Quali strumenti hanno la chat guidata passo-passo?",
        "Qual e' la differenza tra strumenti a punteggio e intervista?",
        "Come funziona la dashboard visiva dei risultati?",
        "Cosa significano i colori nel grafico del profilo?",
        "Quali strumenti supportano il caricamento da PDF?",
        "Posso fare piu' questionari nello stesso account?",
        "Come si passa da un questionario all'altro?",
        "Quali strumenti sono disponibili in inglese, spagnolo e svedese?",
        "Posso usare CounselorBot solo per alcuni questionari?",
        "Come si scarica il report PDF del proprio profilo?",
        "Quali questionari contribuiscono all'analisi combinata?",
    ],
    "cb_percorso": [
        "Come inizio un percorso di autovalutazione su CounselorBot?",
        "Cosa succede dopo aver completato un questionario?",
        "Come funziona la chat con il counselor AI?",
        "Posso fare domande libere durante la chat guidata?",
        "Come si passa allo step successivo nella chat?",
        "Il counselor ricorda le conversazioni precedenti?",
        "Come leggo il mio profilo dopo la chat?",
        "A cosa serve il libretto di riflessione?",
        "Come uso il portfolio per documentare il mio percorso?",
        "Cosa posso caricare nel mio portfolio?",
        "Come faccio l'analisi combinata dei miei risultati?",
        "Posso interrompere una sessione e riprenderla dopo?",
        "Cosa succede se cambio counselor durante il percorso?",
        "Come scelgo il counselor piu' adatto a me?",
        "Posso confrontare i risultati di questionari diversi?",
        "Come esporto o salvo i miei risultati?",
        "Cosa sono le strategie certificate e come mi aiutano?",
        "Come uso il pQBL per studiare dai miei materiali?",
        "Posso condividere il mio profilo con un docente?",
        "Come seguo i miei progressi nel tempo?",
    ],
    "cb_console": [
        "Come accedo alla console di amministrazione?",
        "Quali funzioni ha la console per i ricercatori?",
        "Come si configurano i prompt di sistema?",
        "Come si crea un nuovo counselor AI?",
        "Come si gestiscono i preset dei modelli AI?",
        "Come si visualizzano i risultati dei questionari?",
        "Come si esportano i dati per la validazione?",
        "Come si creano contatti di ricerca con QR code?",
        "Come si gestiscono i piani di somministrazione?",
        "Come si monitorano i costi per modello AI?",
        "Come funziona il benchmark dei modelli?",
        "Come si visualizzano i log delle conversazioni?",
        "Come si gestisce la retention e la redazione PII?",
        "Come si accede al dataset di training?",
        "Come si gestiscono le domande suggerite per l'assistente?",
        "Come funziona il pannello delle strategie certificate?",
        "Come si configura il budget mensile?",
        "Come si usa l'anteprima di ruolo (view-as)?",
        "Come si accede al prompt audit?",
        "Come si gestiscono i questionari di gradimento?",
    ],
    "cb_counselor": [
        "Che cos'e' un counselor AI su CounselorBot?",
        "Come si crea un nuovo counselor?",
        "Quali campi definiscono un counselor?",
        "Come si collega un counselor a un modello AI?",
        "Che cos'e' la persona di un counselor?",
        "Come si scrive una persona efficace per un counselor?",
        "Come si assegnano i questionari a un counselor?",
        "Come si impostano le lingue supportate da un counselor?",
        "Come si attiva o disattiva un counselor?",
        "Qual e' la differenza tra un counselor locale e uno cloud?",
        "Come si ordinano i counselor nel selettore?",
        "Come si traduce la descrizione di un counselor?",
        "Come si testa un counselor prima di attivarlo?",
        "Quali stili di counseling sono disponibili?",
        "Come si personalizza il tono del counselor?",
        "Posso creare counselor diversi per strumenti diversi?",
        "Come influisce il counselor sulla chat guidata?",
        "Quali modelli AI sono consigliati per i counselor?",
        "Come si disabilita il thinking per un counselor?",
        "Come si imposta un avatar per il counselor?",
    ],
    "cb_guida": [
        "Come organizzo una sessione di counseling per i miei studenti?",
        "Come preparo gli studenti all'uso dei questionari?",
        "Come genero codici di accesso per una somministrazione?",
        "Come creo un piano di somministrazione?",
        "Come collego ricercatori a un piano di somministrazione?",
        "Come monitoro i progressi degli studenti?",
        "Come accedo ai risultati dei miei studenti?",
        "Come esporto i dati per l'analisi statistica?",
        "Come presento i risultati senza creare etichette?",
        "Come integro CounselorBot in un modulo didattico?",
        "Come uso l'assistente per preparare le domande?",
        "Come gestisco classi numerose con la piattaforma?",
        "Come formo altri docenti all'uso degli strumenti?",
        "Quali materiali di supporto sono disponibili per i docenti?",
        "Come si usa la funzione di anteprima di ruolo?",
        "Come verifico che gli studenti abbiano completato il percorso?",
        "Come gestisco la privacy e il consenso?",
        "Come uso il pQBL per creare quiz dai materiali?",
        "Come valuto l'efficacia del percorso di counseling?",
        "Come condivido i risultati con colleghi e genitori?",
    ],
}


def seed_assistant_questions(db, models) -> None:
    """Inserisce le domande di default (it) se la tabella è vuota. Idempotente."""
    if db.query(models.AssistantQuestion).count() > 0:
        return
    for topic, questions in DEFAULT_ASSISTANT_QUESTIONS.items():
        for order, text in enumerate(questions):
            db.add(
                models.AssistantQuestion(
                    topic=topic,
                    language="it",
                    text=text,
                    sort_order=order,
                    is_active=True,
                )
            )
    db.commit()
