"""Seme minimo del catalogo delle letture certificate.

Idempotente: crea solo gli slug mancanti e non tocca le voci gia' presenti, come
il seed delle strategie. E' un punto di partenza verificabile, non un canone: il
catalogo vero lo costruiscono gli admin dal pannello.

I testi sono seminati in italiano e inglese; il campo e' JSON per lingua, quindi
le altre quattro si aggiungono dal pannello senza migrazioni.
"""
from __future__ import annotations

from typing import Any

SEED_CERTIFIED_READINGS: list[dict[str, Any]] = [
    # --- saggistica divulgativa ---
    {
        "slug": "dweck-mindset",
        "kind": "essay",
        "title": "Mindset. Cambiare forma mentis per raggiungere il successo",
        "original_title": "Mindset: The New Psychology of Success",
        "creators": ["Carol S. Dweck"],
        "year": 2006,
        "publisher": "Random House (ed. it. Franco Angeli)",
        "themes": ["fallimento-e-attribuzione", "fiducia-in-se", "motivazione-e-volizione"],
        "factor_codes": ["A3", "A4", "A6", "K5"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "La differenza fra credere che l'intelligenza sia fissa e crederla allenabile, e come questa convinzione cambia il modo di reagire agli errori.",
            "en": "The difference between believing ability is fixed and believing it can grow, and how that belief changes the response to failure.",
        },
        "why_i18n": {
            "it": "Utile quando un risultato basso viene letto come un verdetto sulle proprie capacita' invece che su una strategia da cambiare.",
            "en": "Useful when a low score is read as a verdict on ability rather than on a strategy that can change.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Franco Angeli.",
        "source_reference": "Dweck, C. S. (2006). Mindset: The New Psychology of Success. Random House.",
        "sort_order": 10,
    },
    {
        "slug": "oakley-mind-for-numbers",
        "kind": "essay",
        "title": "Impara a imparare",
        "original_title": "A Mind for Numbers",
        "creators": ["Barbara Oakley"],
        "year": 2014,
        "publisher": "TarcherPerigee (ed. it. Vallardi)",
        "themes": ["metodo-di-studio", "organizzazione-e-tempo"],
        "factor_codes": ["C1", "C2", "C5", "C7", "S4", "K4"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["it", "en", "es", "de"],
        "summary_i18n": {
            "it": "Come funzionano attenzione diffusa e attenzione concentrata, e perche' distribuire lo studio nel tempo rende piu' di rileggere.",
            "en": "How focused and diffuse attention work, and why spacing study beats rereading.",
        },
        "why_i18n": {
            "it": "Da' una base concreta a chi studia molto ma con tecniche che non tengono, come la rilettura ripetuta.",
            "en": "Gives concrete grounding to a student who studies hard with techniques that do not hold, such as rereading.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Vallardi.",
        "source_reference": "Oakley, B. (2014). A Mind for Numbers. TarcherPerigee.",
        "sort_order": 11,
    },
    {
        "slug": "duckworth-grit",
        "kind": "essay",
        "title": "Grit. La forza della passione e della perseveranza",
        "original_title": "Grit: The Power of Passion and Perseverance",
        "creators": ["Angela Duckworth"],
        "year": 2016,
        "publisher": "Scribner (ed. it. Giunti)",
        "themes": ["motivazione-e-volizione", "fiducia-in-se"],
        "factor_codes": ["A2", "A5", "S3", "K3"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Perche' la costanza su un interesse coltivato nel tempo pesa piu' del talento dichiarato.",
            "en": "Why sustained effort on a cultivated interest matters more than declared talent.",
        },
        "why_i18n": {
            "it": "Per chi parte con slancio e si ferma dopo pochi giorni, e legge questo come mancanza di talento.",
            "en": "For a student who starts strongly, stops after a few days, and reads that as lack of talent.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Giunti.",
        "source_reference": "Duckworth, A. (2016). Grit. Scribner.",
        "sort_order": 12,
    },
    {
        "slug": "zimbardo-boyd-time-paradox",
        "kind": "essay",
        "title": "Il paradosso del tempo",
        "original_title": "The Time Paradox",
        "creators": ["Philip Zimbardo", "John Boyd"],
        "year": 2008,
        "publisher": "Free Press (ed. it. Mondadori)",
        "themes": ["tempo-e-memoria", "futuro-e-orientamento"],
        "factor_codes": ["T1", "T2", "T3", "T4", "T5"],
        "questionnaire_types": ["ZTPI"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es"],
        "summary_i18n": {
            "it": "Le cinque prospettive temporali degli autori dello ZTPI, e come uno sbilanciamento verso il passato o il presente pesa sulle scelte.",
            "en": "The five time perspectives from the authors of the ZTPI, and how leaning too far into past or present shapes choices.",
        },
        "why_i18n": {
            "it": "E' il libro degli autori dello strumento: chiarisce da dove vengono i fattori del profilo temporale.",
            "en": "Written by the authors of the instrument: it explains where the time profile factors come from.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Mondadori.",
        "source_reference": "Zimbardo, P. & Boyd, J. (2008). The Time Paradox. Free Press.",
        "sort_order": 13,
    },
    # --- articoli divulgati ---
    {
        "slug": "dunlosky-learning-techniques",
        "kind": "article",
        "title": "Improving Students' Learning With Effective Learning Techniques",
        "creators": ["John Dunlosky", "Katherine A. Rawson", "Elizabeth J. Marsh",
                     "Mitchell J. Nathan", "Daniel T. Willingham"],
        "year": 2013,
        "publisher": "Psychological Science in the Public Interest",
        "identifiers": {"doi": "10.1177/1529100612453266"},
        "themes": ["metodo-di-studio", "organizzazione-e-tempo"],
        "factor_codes": ["C1", "C2", "C5", "C7"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "La rassegna che mette in fila dieci tecniche di studio e dice quali reggono alla prova sperimentale: pratica di recupero e studio distribuito in testa.",
            "en": "The review that ranks ten study techniques by how well they hold up experimentally: retrieval practice and spacing come first.",
        },
        "why_i18n": {
            "it": "E' la fonte da cui vengono diverse strategie certificate del catalogo: utile a chi vuole vedere le prove dietro il consiglio.",
            "en": "It is the source behind several certified strategies in the catalog: for a student who wants the evidence behind the advice.",
        },
        "where_to_find": "Accesso aperto tramite il DOI indicato.",
        "source_reference": "Dunlosky et al. (2013), PSPI 14(1), 4-58.",
        "sort_order": 20,
    },
    {
        "slug": "ramirez-beilock-writing-worries",
        "kind": "article",
        "title": "Writing About Testing Worries Boosts Exam Performance in the Classroom",
        "creators": ["Gerardo Ramirez", "Sian L. Beilock"],
        "year": 2011,
        "publisher": "Science",
        "identifiers": {"doi": "10.1126/science.1199427"},
        "themes": ["ansia-e-prestazione", "emozioni"],
        "factor_codes": ["A1", "A7", "S1", "K2"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "Dieci minuti di scrittura sulle proprie preoccupazioni prima di una prova migliorano il risultato di chi soffre d'ansia da esame.",
            "en": "Ten minutes of writing about one's worries before a test improves the performance of test-anxious students.",
        },
        "why_i18n": {
            "it": "E' lo studio dietro la strategia certificata della scrittura espressiva prima della verifica.",
            "en": "It is the study behind the certified expressive-writing strategy used before a test.",
        },
        "where_to_find": "Tramite il DOI indicato; molte biblioteche universitarie hanno l'accesso.",
        "source_reference": "Ramirez, G. & Beilock, S. (2011). Science 331(6014), 211-213.",
        "sort_order": 21,
    },
    # --- narrativa ---
    {
        "slug": "pennac-diario-di-scuola",
        "kind": "fiction",
        "title": "Diario di scuola",
        "original_title": "Chagrin d'ecole",
        "creators": ["Daniel Pennac"],
        "year": 2007,
        "publisher": "Gallimard (ed. it. Feltrinelli)",
        "themes": ["fallimento-e-attribuzione", "identita-e-se", "fiducia-in-se"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "fr", "en", "es", "de"],
        "summary_i18n": {
            "it": "Il racconto di un pessimo studente diventato scrittore e insegnante, dal punto di vista di chi a scuola si sentiva un caso perso.",
            "en": "The story of a hopeless pupil who became a writer and a teacher, told from inside the experience of feeling written off.",
        },
        "why_i18n": {
            "it": "Per chi ha smesso di credere di poter cambiare rendimento: mostra il vissuto, non la teoria dell'insuccesso scolastico.",
            "en": "For a student who has stopped believing performance can change: it shows the lived side of school failure, not the theory.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Feltrinelli.",
        "source_reference": "Pennac, D. (2007). Chagrin d'ecole. Gallimard. Premio Renaudot 2007.",
        "sort_order": 30,
    },
    {
        "slug": "calvino-barone-rampante",
        "kind": "fiction",
        "title": "Il barone rampante",
        "creators": ["Italo Calvino"],
        "year": 1957,
        "publisher": "Einaudi",
        "themes": ["scelta-e-decisione", "identita-e-se"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un ragazzo sale su un albero per non obbedire e decide di non scendere piu': una scelta tenuta per tutta la vita, con quello che costa e quello che apre.",
            "en": "A boy climbs a tree in refusal and decides never to come down: a single choice held for a lifetime, with everything it costs and opens.",
        },
        "why_i18n": {
            "it": "Per ragionare su che cosa significa tenere una decisione nel tempo, invece di viverla come un bivio istantaneo.",
            "en": "To think about what it means to hold a decision over time, rather than treat it as one instantaneous fork.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione Einaudi o Mondadori.",
        "source_reference": "Calvino, I. (1957). Il barone rampante. Einaudi.",
        "sort_order": 31,
    },
    {
        "slug": "ferrante-amica-geniale",
        "kind": "fiction",
        "title": "L'amica geniale",
        "creators": ["Elena Ferrante"],
        "year": 2011,
        "publisher": "Edizioni E/O",
        "themes": ["transizione-scuola-universita", "identita-e-se", "relazioni-e-collaborazione"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Due bambine in un rione povero di Napoli: per una la scuola diventa la via d'uscita, per l'altra si chiude presto.",
            "en": "Two girls in a poor Naples neighbourhood: for one, school becomes the way out; for the other it closes early.",
        },
        "why_i18n": {
            "it": "Per chi vive lo studio come una porta stretta fra sé e la propria origine, e ne sente il peso.",
            "en": "For a student who experiences study as a narrow door between themselves and where they come from.",
        },
        "where_to_find": "In libreria e in biblioteca; edizioni E/O.",
        "source_reference": "Ferrante, E. (2011). L'amica geniale. Edizioni E/O.",
        "sort_order": 32,
    },
    # --- film e documentari ---
    {
        "slug": "bergman-posto-delle-fragole",
        "kind": "film",
        "title": "Il posto delle fragole",
        "original_title": "Smultronstallet",
        "creators": ["Ingmar Bergman"],
        "year": 1957,
        "publisher": "Svensk Filmindustri",
        "themes": ["tempo-e-memoria", "futuro-e-orientamento"],
        "factor_codes": ["T1", "T2"],
        "questionnaire_types": ["ZTPI"],
        "audience": ["universita", "adulti"],
        "available_languages": ["sv", "it", "en"],
        "summary_i18n": {
            "it": "Un anziano professore attraversa la Svezia per un premio e fa i conti con il proprio passato lungo la strada.",
            "en": "An elderly professor drives across Sweden to receive an award and settles accounts with his own past along the way.",
        },
        "why_i18n": {
            "it": "Mostra che cosa vuol dire guardare al passato con rimpianto invece che come a una risorsa: il tema centrale del profilo temporale.",
            "en": "It shows what it means to look at the past with regret rather than as a resource: the core question of the time profile.",
        },
        "where_to_find": "Disponibile in DVD e su piattaforme di cinema d'autore; spesso nelle mediateche.",
        "source_reference": "Bergman, I. (1957). Smultronstallet. Svensk Filmindustri.",
        "sort_order": 40,
    },
    {
        "slug": "weir-attimo-fuggente",
        "kind": "film",
        "title": "L'attimo fuggente",
        "original_title": "Dead Poets Society",
        "creators": ["Peter Weir"],
        "year": 1989,
        "publisher": "Touchstone Pictures",
        "themes": ["scelta-e-decisione", "identita-e-se", "futuro-e-orientamento"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "is_sensitive": True,
        "content_warning": "Il film contiene il suicidio di un personaggio adolescente. Va proposto dicendolo prima, e non a chi sta portando in conversazione un disagio personale.",
        "summary_i18n": {
            "it": "In un collegio rigido un professore di lettere spinge i suoi studenti a decidere che vita vogliono, con conseguenze che non controlla.",
            "en": "In a strict boarding school a literature teacher pushes his students to decide what life they want, with consequences he cannot control.",
        },
        "why_i18n": {
            "it": "Per ragionare sul conflitto fra le attese della famiglia e la propria scelta di studio, senza far finta che sia un conflitto semplice.",
            "en": "To think about the conflict between family expectations and one's own choice of study, without pretending it is a simple one.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Weir, P. (1989). Dead Poets Society. Touchstone Pictures.",
        "sort_order": 41,
    },
    {
        "slug": "ted-duckworth-grit",
        "kind": "video",
        "title": "Grit: the power of passion and perseverance",
        "creators": ["Angela Duckworth"],
        "year": 2013,
        "publisher": "TED Talks Education",
        "themes": ["motivazione-e-volizione"],
        "factor_codes": ["A2", "A5", "S3"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["en", "it", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Sei minuti in cui l'autrice riassume la sua ricerca sulla perseveranza, con sottotitoli in molte lingue.",
            "en": "Six minutes in which the author sums up her research on perseverance, subtitled in many languages.",
        },
        "why_i18n": {
            "it": "Un primo passo breve per chi non vuole partire da un libro intero.",
            "en": "A short first step for a student who does not want to start with a whole book.",
        },
        "where_to_find": "Archivio TED, con trascrizione e sottotitoli.",
        "source_reference": "Duckworth, A. (2013). TED Talks Education.",
        "sort_order": 50,
    },
    # --- comunicazione ---
    {
        "slug": "anderson-ted-talks",
        "kind": "essay",
        "title": "TED Talks. Il manuale ufficiale del public speaking",
        "original_title": "TED Talks: The Official TED Guide to Public Speaking",
        "creators": ["Chris Anderson"],
        "year": 2016,
        "publisher": "Houghton Mifflin Harcourt (ed. it. Rizzoli)",
        "themes": ["comunicazione"],
        "factor_codes": ["S2", "K1"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Come si prepara un intervento: una sola idea da consegnare, una struttura che regge, e le prove che tolgono il resto.",
            "en": "How a talk is prepared: one idea to hand over, a structure that holds, and rehearsal that strips out the rest.",
        },
        "why_i18n": {
            "it": "Smonta l'idea che parlare in pubblico sia un talento: lo tratta come un mestiere fatto di scelte e di prove.",
            "en": "It takes public speaking apart as a craft of choices and rehearsal, not a talent one either has or lacks.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Rizzoli.",
        "source_reference": "Anderson, C. (2016). TED Talks: The Official TED Guide to Public Speaking. Houghton Mifflin Harcourt.",
        "sort_order": 60,
    },
    {
        "slug": "hooper-discorso-del-re",
        "kind": "film",
        "title": "Il discorso del re",
        "original_title": "The King's Speech",
        "creators": ["Tom Hooper"],
        "year": 2010,
        "publisher": "See-Saw Films",
        "themes": ["comunicazione", "ansia-e-prestazione"],
        "factor_codes": ["S2", "K1", "S1"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un re balbuziente deve parlare alla nazione e lavora per anni con un logopedista senza titoli.",
            "en": "A stammering king has to address a nation, and works for years with an unaccredited speech therapist.",
        },
        "why_i18n": {
            "it": "Mostra la fatica fisica dell'esposizione, non la retorica del superare le paure di slancio.",
            "en": "It shows the physical labour of speaking, not the rhetoric of conquering fear in one leap.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Hooper, T. (2010). The King's Speech. See-Saw Films.",
        "sort_order": 61,
    },
    {
        "slug": "treasure-how-to-speak",
        "kind": "video",
        "title": "How to speak so that people want to listen",
        "creators": ["Julian Treasure"],
        "year": 2013,
        "publisher": "TED",
        "themes": ["comunicazione"],
        "factor_codes": ["S2", "K1"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["en", "it", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Dieci minuti sul come si parla — voce, ritmo, silenzi — invece che sul cosa dire.",
            "en": "Ten minutes on how one speaks — voice, pace, silence — rather than on what to say.",
        },
        "why_i18n": {
            "it": "Un primo passo breve per chi non vuole partire da un libro intero.",
            "en": "A short first step for a student who will not start with a whole book.",
        },
        "where_to_find": "Archivio TED, con trascrizione e sottotitoli.",
        "source_reference": "Treasure, J. (2013). TED Talk.",
        "sort_order": 62,
    },
    # --- curiosita ed esplorazione ---
    {
        "slug": "gruber-states-of-curiosity",
        "kind": "article",
        "title": "States of Curiosity Modulate Hippocampus-Dependent Learning via the Dopaminergic Circuit",
        "creators": ["Matthias J. Gruber", "Bernard D. Gelman", "Charan Ranganath"],
        "year": 2014,
        "publisher": "Neuron",
        "identifiers": {"doi": "10.1016/j.neuron.2014.08.060"},
        "themes": ["curiosita-ed-esplorazione", "metodo-di-studio"],
        "factor_codes": ["AD3"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "Quando la curiosita' e' attiva si ricorda meglio anche cio' che non c'entra con la domanda.",
            "en": "When curiosity is high, even incidental material is remembered better.",
        },
        "why_i18n": {
            "it": "Da' una base sperimentale al perche' esplorare prima di scegliere, invece di trattarlo come un consiglio di buon senso.",
            "en": "It gives experimental grounding to exploring before choosing, instead of leaving it as common sense.",
        },
        "where_to_find": "Tramite il DOI indicato; accesso spesso disponibile in biblioteca universitaria.",
        "source_reference": "Gruber, Gelman & Ranganath (2014). Neuron 84(2), 486-496.",
        "sort_order": 70,
    },
    {
        "slug": "wenders-sale-della-terra",
        "kind": "documentary",
        "title": "Il sale della terra",
        "original_title": "The Salt of the Earth",
        "creators": ["Wim Wenders", "Juliano Ribeiro Salgado"],
        "year": 2014,
        "publisher": "Decia Films",
        "themes": ["curiosita-ed-esplorazione", "lavoro-e-vocazione"],
        "factor_codes": ["AD3", "AD1"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "is_sensitive": True,
        "content_warning": "Contiene immagini di carestie, esodi e violenza di guerra. Va annunciato prima di proporlo.",
        "summary_i18n": {
            "it": "Quarant'anni di lavoro del fotografo Sebastiao Salgado, raccontati da suo figlio e da Wenders.",
            "en": "Forty years of photographer Sebastiao Salgado's work, told by his son and by Wenders.",
        },
        "why_i18n": {
            "it": "La vocazione che si costruisce andando, non decidendo a tavolino, e il prezzo che chiede.",
            "en": "A vocation built by going rather than by deciding in advance, and what it costs.",
        },
        "where_to_find": "Disponibile in DVD e su piattaforme di documentari.",
        "source_reference": "Wenders, W. & Salgado, J. R. (2014). The Salt of the Earth.",
        "sort_order": 71,
    },
    # --- lavoro e vocazione ---
    {
        "slug": "melfi-diritto-di-contare",
        "kind": "film",
        "title": "Il diritto di contare",
        "original_title": "Hidden Figures",
        "creators": ["Theodore Melfi"],
        "year": 2016,
        "publisher": "Fox 2000 Pictures",
        "themes": ["lavoro-e-vocazione", "relazioni-e-collaborazione", "fiducia-in-se"],
        "factor_codes": ["AD4", "AD2", "S5"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Tre matematiche afroamericane alla NASA degli anni Sessanta, fra competenza riconosciuta e barriere che non dipendono da loro.",
            "en": "Three African American mathematicians at 1960s NASA, between recognised skill and barriers not of their making.",
        },
        "why_i18n": {
            "it": "Tiene insieme la competenza personale e gli ostacoli esterni, senza ridurre la carriera al solo merito.",
            "en": "It holds personal skill and external obstacles together, without reducing a career to merit alone.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Melfi, T. (2016). Hidden Figures. Fox 2000 Pictures.",
        "sort_order": 80,
    },
    {
        "slug": "savickas-porfeli-caas",
        "kind": "article",
        "title": "Career Adapt-Abilities Scale: construction, reliability and measurement equivalence across 13 countries",
        "creators": ["Mark L. Savickas", "Erik J. Porfeli"],
        "year": 2012,
        "publisher": "Journal of Vocational Behavior",
        "identifiers": {"doi": "10.1016/j.jvb.2012.01.011"},
        "themes": ["lavoro-e-vocazione", "futuro-e-orientamento"],
        "factor_codes": ["AD1", "AD2", "AD3", "AD4"],
        "questionnaire_types": ["QAP"],
        "audience": ["adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "La costruzione della scala di adattabilita' professionale su tredici paesi: le quattro risorse e come sono state misurate.",
            "en": "The construction of the career adaptability scale across thirteen countries: the four resources and how they were measured.",
        },
        "why_i18n": {
            "it": "E' la fonte dello strumento appena compilato: chiude il cerchio per chi vuole sapere da dove vengono le quattro risorse del QAP.",
            "en": "It is the source of the instrument just completed: it closes the loop on where the QAP's four resources come from.",
        },
        "where_to_find": "Tramite il DOI indicato.",
        "source_reference": "Savickas, M. L. & Porfeli, E. J. (2012). JVB 80(3), 661-673.",
        "sort_order": 81,
    },
    # --- ansia e prestazione ---
    {
        "slug": "beilock-choke",
        "kind": "essay",
        "title": "Choke: What the Secrets of the Brain Reveal About Getting It Right When You Have To",
        "creators": ["Sian Beilock"],
        "year": 2010,
        "publisher": "Free Press",
        "themes": ["ansia-e-prestazione", "emozioni"],
        "factor_codes": ["A1", "A7", "S1", "K2"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "Perche' si sbaglia proprio quando conta, e perche' pensare troppo a come si fa una cosa la peggiora.",
            "en": "Why we fail exactly when it matters, and why thinking too hard about how we do something makes it worse.",
        },
        "why_i18n": {
            "it": "E' l'autrice dello studio sulla scrittura espressiva gia' in catalogo: qui c'e' il quadro completo.",
            "en": "By the author of the expressive-writing study already in the catalog: here is the full picture.",
        },
        "where_to_find": "In libreria e in biblioteca universitaria.",
        "source_reference": "Beilock, S. (2010). Choke. Free Press.",
        "sort_order": 90,
    },
    {
        "slug": "chazelle-whiplash",
        "kind": "film",
        "title": "Whiplash",
        "creators": ["Damien Chazelle"],
        "year": 2014,
        "publisher": "Bold Films",
        "themes": ["ansia-e-prestazione", "motivazione-e-volizione"],
        "factor_codes": ["A1", "A5"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "is_sensitive": True,
        "content_warning": "Contiene violenza psicologica sistematica da parte di un insegnante e autolesionismo indiretto. Va proposto come oggetto di discussione, mai come modello di impegno.",
        "summary_i18n": {
            "it": "Un batterista e un insegnante che confonde l'esigenza con l'abuso, fino a dove l'ambizione regge.",
            "en": "A drummer and a teacher who confuses demand with abuse, up to the point where ambition breaks.",
        },
        "why_i18n": {
            "it": "Per distinguere la pressione che allena da quella che rompe: utile solo se la differenza viene discussa.",
            "en": "To tell pressure that trains from pressure that breaks: useful only if the difference is discussed.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Chazelle, D. (2014). Whiplash. Bold Films.",
        "sort_order": 91,
    },
    # --- emozioni ---
    {
        "slug": "goleman-intelligenza-emotiva",
        "kind": "essay",
        "title": "Intelligenza emotiva",
        "original_title": "Emotional Intelligence",
        "creators": ["Daniel Goleman"],
        "year": 1995,
        "publisher": "Bantam Books (ed. it. Rizzoli)",
        "identifiers": {"isbn": "9788817106726"},
        "themes": ["emozioni", "fiducia-in-se"],
        "factor_codes": ["A7", "S1", "K2"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Riconoscere, dare un nome e regolare le emozioni come competenze che si allenano, non come tratti fissi.",
            "en": "Recognising, naming and regulating emotions as skills that can be trained, not fixed traits.",
        },
        "why_i18n": {
            "it": "Il testo che ha reso corrente questa idea; utile a chi tratta le proprie reazioni come qualcosa che semplicemente capita.",
            "en": "The book that made the idea current; useful for a student who treats their reactions as something that simply happens.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Rizzoli.",
        "source_reference": "Goleman, D. (1995). Emotional Intelligence. Bantam Books. ATTENZIONE: da non confondere con l'articolo omonimo di Salovey e Mayer (1990).",
        "sort_order": 100,
    },
    {
        "slug": "docter-inside-out",
        "kind": "film",
        "title": "Inside Out",
        "creators": ["Pete Docter"],
        "year": 2015,
        "publisher": "Pixar Animation Studios",
        "themes": ["emozioni", "identita-e-se"],
        "factor_codes": ["A7", "S1"],
        "audience": ["secondaria"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Le emozioni di una ragazzina di undici anni come personaggi, in un trasloco che manda tutto fuori posto.",
            "en": "The emotions of an eleven-year-old as characters, during a move that throws everything out of place.",
        },
        "why_i18n": {
            "it": "Da' una funzione anche alla tristezza, invece di trattarla come un guasto da riparare.",
            "en": "It gives sadness a function, instead of treating it as a fault to be fixed.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Docter, P. (2015). Inside Out. Pixar.",
        "sort_order": 101,
    },
    # --- relazioni ---
    {
        "slug": "palacio-wonder",
        "kind": "fiction",
        "title": "Wonder",
        "creators": ["R. J. Palacio"],
        "year": 2012,
        "publisher": "Knopf (ed. it. Giunti)",
        "themes": ["relazioni-e-collaborazione", "identita-e-se"],
        "factor_codes": ["C4", "S2"],
        "audience": ["secondaria"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Il primo anno di scuola di un ragazzino con una malformazione al viso, raccontato a turno da lui e dai compagni.",
            "en": "The first school year of a boy with a facial difference, told in turn by him and by his classmates.",
        },
        "why_i18n": {
            "it": "La classe vista da chi ne sta ai margini e da chi lo esclude: il gruppo come problema e come risorsa.",
            "en": "The classroom seen by the one at its edge and by those excluding him: the group as problem and as resource.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Giunti.",
        "source_reference": "Palacio, R. J. (2012). Wonder. Knopf.",
        "sort_order": 110,
    },
    # --- transizioni ---
    {
        "slug": "gerwig-lady-bird",
        "kind": "film",
        "title": "Lady Bird",
        "creators": ["Greta Gerwig"],
        "year": 2017,
        "publisher": "A24",
        "themes": ["transizione-scuola-universita", "scelta-e-decisione", "identita-e-se"],
        "factor_codes": ["AD1", "S5"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "L'ultimo anno di scuola fra l'universita' che si vorrebbe, i soldi che non ci sono e una madre che non e' d'accordo.",
            "en": "A final school year between the university one wants, the money that is missing, and a mother who disagrees.",
        },
        "why_i18n": {
            "it": "La scelta dopo la scuola come negoziazione con la famiglia e con i vincoli reali, non come vocazione improvvisa.",
            "en": "The choice after school as a negotiation with family and real constraints, not a sudden calling.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Gerwig, G. (2017). Lady Bird. A24. Contiene una prima esperienza sessuale trattata senza enfasi: pubblico da valutare.",
        "sort_order": 120,
    },
    {
        "slug": "yeager-lay-theory-college",
        "kind": "article",
        "title": "Teaching a lay theory before college narrows achievement gaps at scale",
        "creators": ["David S. Yeager", "Gregory M. Walton", "Shannon T. Brady"],
        "year": 2016,
        "publisher": "PNAS",
        "identifiers": {"doi": "10.1073/pnas.1524360113"},
        "themes": ["transizione-scuola-universita", "fiducia-in-se"],
        "factor_codes": ["A6", "S5"],
        "audience": ["adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "Un intervento breve prima dell'ingresso all'universita' riduce il divario di risultati fra gruppi di studenti.",
            "en": "A brief intervention before college entry narrows the achievement gap between groups of students.",
        },
        "why_i18n": {
            "it": "Il primo anno come passaggio su cui si puo' agire, non come selezione naturale.",
            "en": "The first year as a transition that can be acted on, not as natural selection.",
        },
        "where_to_find": "Accesso aperto tramite il DOI indicato.",
        "source_reference": "Yeager, D. S. et al. (2016). PNAS 113(24), E3341-E3348.",
        "sort_order": 121,
    },
    # --- ampliamento: temi sottili e fascia secondaria ---
    {
        "slug": "newport-deep-work",
        "kind": "essay",
        "title": "Deep work",
        "original_title": "Deep Work: Rules for Focused Success in a Distracted World",
        "creators": ["Cal Newport"],
        "year": 2016,
        "publisher": "Grand Central (ed. it. ROI Edizioni)",
        "themes": ["organizzazione-e-tempo", "metodo-di-studio"],
        "factor_codes": ["C2", "C3", "C6", "S3"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Perche' il lavoro cognitivo esigente richiede blocchi lunghi e protetti, e come costruirli.",
            "en": "Why demanding cognitive work needs long protected blocks, and how to build them.",
        },
        "why_i18n": {
            "it": "Utile a chi studia a pezzi fra notifiche e pause e conclude poco malgrado le ore spese.",
            "en": "Useful for a student who studies in fragments between notifications and finishes little despite the hours.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana ROI Edizioni.",
        "source_reference": "Newport, C. (2016). Deep Work. Grand Central Publishing.",
        "sort_order": 130,
    },
    {
        "slug": "brown-make-it-stick",
        "kind": "essay",
        "title": "Make It Stick",
        "original_title": "Make It Stick: The Science of Successful Learning",
        "creators": ["Peter C. Brown", "Henry L. Roediger III", "Mark A. McDaniel"],
        "year": 2014,
        "publisher": "Harvard University Press",
        "themes": ["metodo-di-studio", "tempo-e-memoria"],
        "factor_codes": ["C1", "C5", "C7", "T2"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en", "es", "de"],
        "summary_i18n": {
            "it": "Che cosa regge alla prova dei dati fra le tecniche di studio: recupero attivo, pratica distribuita, interleaving.",
            "en": "Which study techniques survive the evidence: retrieval practice, spacing, interleaving.",
        },
        "why_i18n": {
            "it": "Da' un criterio a chi vuole cambiare metodo ma non sa quali tecniche valgano la fatica.",
            "en": "Gives a criterion to a student who wants to change method but cannot tell which techniques are worth the effort.",
        },
        "where_to_find": "In biblioteca universitaria; edizione originale Harvard University Press.",
        "source_reference": "Brown, P. C., Roediger, H. L., McDaniel, M. A. (2014). Make It Stick. Harvard University Press.",
        "sort_order": 131,
    },
    {
        "slug": "foer-moonwalking",
        "kind": "essay",
        "title": "L'arte di ricordare tutto",
        "original_title": "Moonwalking with Einstein",
        "creators": ["Joshua Foer"],
        "year": 2011,
        "publisher": "Penguin (ed. it. Longanesi)",
        "themes": ["tempo-e-memoria", "metodo-di-studio"],
        "factor_codes": ["T2", "C5", "C7"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Un anno passato ad allenare la memoria con le tecniche dei campionati mnemonici, e che cosa se ne impara davvero.",
            "en": "A year spent training memory with the techniques of memory championships, and what is actually learned from it.",
        },
        "why_i18n": {
            "it": "Smonta l'idea che la memoria sia un dono: e' una tecnica che si allena, e questo cambia come si studia.",
            "en": "Dismantles the idea that memory is a gift: it is a trainable technique, and that changes how one studies.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Longanesi.",
        "source_reference": "Foer, J. (2011). Moonwalking with Einstein. Penguin Press.",
        "sort_order": 132,
    },
    {
        "slug": "syed-black-box",
        "kind": "essay",
        "title": "Black Box Thinking",
        "original_title": "Black Box Thinking: Why Some People Never Learn from Their Mistakes",
        "creators": ["Matthew Syed"],
        "year": 2015,
        "publisher": "John Murray",
        "themes": ["fallimento-e-attribuzione", "metodo-di-studio"],
        "factor_codes": ["A3", "A4", "K5"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en", "es", "de"],
        "summary_i18n": {
            "it": "Perche' l'aviazione impara dagli incidenti e altri settori li nascondono, e che cosa cambia trattare l'errore come dato.",
            "en": "Why aviation learns from accidents while other fields hide them, and what changes when error is treated as data.",
        },
        "why_i18n": {
            "it": "Utile quando un errore viene vissuto come una condanna invece che come l'informazione piu' utile disponibile.",
            "en": "Useful when a mistake is experienced as a verdict instead of the most useful information available.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione originale John Murray.",
        "source_reference": "Syed, M. (2015). Black Box Thinking. John Murray.",
        "sort_order": 133,
    },
    {
        "slug": "cain-quiet",
        "kind": "essay",
        "title": "Quiet. Il potere degli introversi",
        "original_title": "Quiet: The Power of Introverts in a World That Can't Stop Talking",
        "creators": ["Susan Cain"],
        "year": 2012,
        "publisher": "Crown (ed. it. Bompiani)",
        "themes": ["relazioni-e-collaborazione", "comunicazione", "identita-e-se"],
        "factor_codes": ["C4", "S2", "S5", "K1"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Come funziona il temperamento introverso e quanto la scuola e il lavoro siano tarati su quello opposto.",
            "en": "How the introverted temperament works, and how far school and work are calibrated on its opposite.",
        },
        "why_i18n": {
            "it": "Per chi legge la propria riservatezza come un difetto da correggere invece che come un modo di funzionare.",
            "en": "For a student who reads their own reserve as a flaw to correct rather than a way of working.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Bompiani.",
        "source_reference": "Cain, S. (2012). Quiet. Crown Publishing Group.",
        "sort_order": 134,
    },
    {
        "slug": "pink-drive",
        "kind": "essay",
        "title": "Drive. La sorprendente verita' su cio' che ci motiva",
        "original_title": "Drive: The Surprising Truth About What Motivates Us",
        "creators": ["Daniel H. Pink"],
        "year": 2009,
        "publisher": "Riverhead (ed. it. Etas)",
        "themes": ["motivazione-e-volizione"],
        "factor_codes": ["A2", "A5", "S3", "K3"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Autonomia, padronanza e scopo come motori della motivazione, e i limiti di premi e punizioni.",
            "en": "Autonomy, mastery and purpose as the engines of motivation, and the limits of rewards and punishments.",
        },
        "why_i18n": {
            "it": "Per chi studia solo sotto scadenza o voto e si chiede perche' la spinta sparisca appena il premio finisce.",
            "en": "For a student who works only under a deadline or a grade and wonders why the drive vanishes once the reward is gone.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Etas.",
        "source_reference": "Pink, D. H. (2009). Drive. Riverhead Books.",
        "sort_order": 135,
    },
    {
        "slug": "sagan-cosmos",
        "kind": "essay",
        "title": "Cosmo",
        "original_title": "Cosmos",
        "creators": ["Carl Sagan"],
        "year": 1980,
        "publisher": "Random House (ed. it. Mondadori)",
        "themes": ["curiosita-ed-esplorazione"],
        "factor_codes": ["AD3"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "L'universo raccontato come una domanda aperta, dalla scala cosmica alla storia di chi l'ha indagata.",
            "en": "The universe told as an open question, from cosmic scale to the history of those who investigated it.",
        },
        "why_i18n": {
            "it": "Mostra la curiosita' come metodo, non come talento: si comincia da una domanda che non ha ancora risposta.",
            "en": "Shows curiosity as a method rather than a talent: it starts from a question that has no answer yet.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Mondadori.",
        "source_reference": "Sagan, C. (1980). Cosmos. Random House.",
        "sort_order": 136,
    },
    {
        "slug": "johnston-cielo-ottobre",
        "kind": "film",
        "title": "Cielo d'ottobre",
        "original_title": "October Sky",
        "creators": ["Joe Johnston"],
        "year": 1999,
        "publisher": "Universal Pictures",
        "themes": ["fallimento-e-attribuzione", "curiosita-ed-esplorazione", "futuro-e-orientamento"],
        "factor_codes": ["A3", "A4", "AD1", "AD3"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "In una cittadina mineraria, uno studente costruisce razzi che continuano a fallire finche' non impara a leggere gli errori.",
            "en": "In a mining town, a student builds rockets that keep failing until he learns to read the failures.",
        },
        "why_i18n": {
            "it": "Il fallimento ripetuto come parte del procedimento, in un contesto scolastico e familiare che non lo incoraggia.",
            "en": "Repeated failure as part of the procedure, in a school and family setting that does not encourage it.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Johnston, J. (1999). October Sky. Universal Pictures.",
        "sort_order": 137,
    },
    {
        "slug": "ejiofor-ragazzo-vento",
        "kind": "film",
        "title": "Il ragazzo che catturo' il vento",
        "original_title": "The Boy Who Harnessed the Wind",
        "creators": ["Chiwetel Ejiofor"],
        "year": 2019,
        "publisher": "Netflix",
        "themes": ["curiosita-ed-esplorazione", "fiducia-in-se", "transizione-scuola-universita"],
        "factor_codes": ["AD3", "A6", "S5"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Espulso da scuola perche' la famiglia non puo' pagare, un ragazzo malawiano studia in biblioteca e costruisce una turbina eolica.",
            "en": "Expelled because his family cannot pay the fees, a Malawian boy studies in the library and builds a wind turbine.",
        },
        "why_i18n": {
            "it": "L'accesso allo studio come ostacolo concreto, e la curiosita' come risorsa quando la scuola viene a mancare.",
            "en": "Access to study as a concrete obstacle, and curiosity as a resource when school falls away.",
        },
        "where_to_find": "Disponibile su Netflix.",
        "source_reference": "Ejiofor, C. (2019). The Boy Who Harnessed the Wind. Netflix.",
        "sort_order": 138,
    },
    {
        "slug": "satrapi-persepolis",
        "kind": "film",
        "title": "Persepolis",
        "original_title": "Persepolis",
        "creators": ["Marjane Satrapi", "Vincent Paronnaud"],
        "year": 2007,
        "publisher": "2.4.7. Films",
        "themes": ["identita-e-se", "transizione-scuola-universita", "scelta-e-decisione"],
        "factor_codes": ["S5", "K5", "AD1", "AD2"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "L'adolescenza di Marjane fra la rivoluzione iraniana e gli anni di studio in Europa, fra due appartenenze che non combaciano.",
            "en": "Marjane's adolescence between the Iranian revolution and her student years in Europe, between two belongings that do not match.",
        },
        "why_i18n": {
            "it": "Per chi studia lontano da casa o fra due culture e sente di non essere del tutto in nessuna delle due.",
            "en": "For a student living far from home or between two cultures who feels fully at home in neither.",
        },
        "is_sensitive": True,
        "content_warning": "Contiene repressione politica, carcerazione e la morte di familiari, raccontate senza compiacimento.",
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Satrapi, M., Paronnaud, V. (2007). Persepolis. 2.4.7. Films.",
        "sort_order": 139,
    },
    {
        "slug": "van-sant-will-hunting",
        "kind": "film",
        "title": "Will Hunting - Genio ribelle",
        "original_title": "Good Will Hunting",
        "creators": ["Gus Van Sant"],
        "year": 1997,
        "publisher": "Miramax",
        "themes": ["fiducia-in-se", "scelta-e-decisione", "identita-e-se"],
        "factor_codes": ["A6", "S5", "AD2", "K5"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un giovane con un talento matematico fuori scala evita ogni percorso che lo esponga, finche' un terapeuta non lo mette davanti alla scelta.",
            "en": "A young man with off-the-scale mathematical talent avoids every path that would expose him, until a therapist confronts him with the choice.",
        },
        "why_i18n": {
            "it": "Il talento che diventa un peso quando usarlo significa rischiare: utile a chi si tira indietro proprio dove potrebbe riuscire.",
            "en": "Talent as a burden when using it means risking: useful for a student who withdraws exactly where they could succeed.",
        },
        "is_sensitive": True,
        "content_warning": "Contiene il racconto di abusi subiti nell'infanzia e un percorso psicoterapeutico.",
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Van Sant, G. (1997). Good Will Hunting. Miramax Films.",
        "sort_order": 140,
    },
    {
        "slug": "urban-master-procrastinator",
        "kind": "video",
        "title": "Inside the mind of a master procrastinator",
        "creators": ["Tim Urban"],
        "year": 2016,
        "publisher": "TED",
        "themes": ["organizzazione-e-tempo", "motivazione-e-volizione"],
        "factor_codes": ["C2", "C3", "A5", "S3"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Il rinvio raccontato dall'interno, fra scadenze che salvano e progetti senza scadenza che nessuno comincia.",
            "en": "Procrastination told from the inside, between deadlines that rescue and deadline-free projects nobody starts.",
        },
        "why_i18n": {
            "it": "Da' un nome a un'esperienza comune senza colpevolizzarla, e distingue il rinvio con scadenza da quello senza.",
            "en": "Names a common experience without blaming it, and separates procrastination with a deadline from procrastination without one.",
        },
        "where_to_find": "Disponibile gratuitamente su ted.com con sottotitoli in italiano.",
        "source_reference": "Urban, T. (2016). Inside the mind of a master procrastinator. TED2016.",
        "sort_order": 141,
    },
    # --- secondo ampliamento: vocazione, emozioni, relazioni, fascia secondaria ---
    {
        "slug": "darabont-ali-liberta",
        "kind": "film",
        "title": "Le ali della liberta'",
        "original_title": "The Shawshank Redemption",
        "creators": ["Frank Darabont"],
        "year": 1994,
        "publisher": "Columbia Pictures",
        "themes": ["fallimento-e-attribuzione", "motivazione-e-volizione", "relazioni-e-collaborazione", "tempo-e-memoria"],
        "factor_codes": ["A3", "A5", "C4", "T2"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Vent'anni di carcere per un uomo che continua a lavorare a un progetto lungo, mentre intorno tutti hanno smesso di aspettarsi qualcosa.",
            "en": "Twenty years in prison for a man who keeps working at a long project while everyone around him has stopped expecting anything.",
        },
        "why_i18n": {
            "it": "La perseveranza su un tempo lungo, quando il risultato non arriva e l'ambiente scoraggia: utile a chi misura tutto sul risultato immediato.",
            "en": "Perseverance over a long span, when results do not come and the environment discourages: useful for a student who measures everything by the immediate result.",
        },
        "is_sensitive": True,
        "content_warning": "Contiene violenza carceraria, una violenza sessuale e un suicidio.",
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Darabont, F. (1994). The Shawshank Redemption. Columbia Pictures.",
        "sort_order": 150,
    },
    {
        "slug": "muccino-ricerca-felicita",
        "kind": "film",
        "title": "La ricerca della felicita'",
        "original_title": "The Pursuit of Happyness",
        "creators": ["Gabriele Muccino"],
        "year": 2006,
        "publisher": "Columbia Pictures",
        "themes": ["lavoro-e-vocazione", "motivazione-e-volizione", "fallimento-e-attribuzione"],
        "factor_codes": ["AD1", "A5", "A3", "S3"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un padre senza casa affronta un tirocinio non pagato mentre cresce il figlio, giocandosi tutto su una selezione che ammette una persona sola.",
            "en": "A homeless father takes an unpaid internship while raising his son, staking everything on a selection that admits one person.",
        },
        "why_i18n": {
            "it": "Mostra il costo materiale di un percorso professionale, non solo la determinazione: utile quando la riuscita viene letta come pura forza di volonta'.",
            "en": "Shows the material cost of a career path, not only determination: useful when success is read as sheer willpower.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Muccino, G. (2006). The Pursuit of Happyness. Columbia Pictures.",
        "sort_order": 151,
    },
    {
        "slug": "daldry-billy-elliot",
        "kind": "film",
        "title": "Billy Elliot",
        "original_title": "Billy Elliot",
        "creators": ["Stephen Daldry"],
        "year": 2000,
        "publisher": "Universal Pictures",
        "themes": ["lavoro-e-vocazione", "scelta-e-decisione", "identita-e-se"],
        "factor_codes": ["AD1", "AD2", "S5"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "In una citta' mineraria in sciopero, un ragazzino lascia la boxe per la danza contro la volonta' del padre.",
            "en": "In a mining town on strike, a boy leaves boxing for ballet against his father's will.",
        },
        "why_i18n": {
            "it": "La vocazione che confligge con le attese della famiglia e del contesto: il caso in cui scegliere significa deludere qualcuno.",
            "en": "A calling that collides with family and community expectations: the case where choosing means disappointing someone.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Daldry, S. (2000). Billy Elliot. Universal Pictures.",
        "sort_order": 152,
    },
    {
        "slug": "cantet-la-classe",
        "kind": "film",
        "title": "La classe - Entre les murs",
        "original_title": "Entre les murs",
        "creators": ["Laurent Cantet"],
        "year": 2008,
        "publisher": "Haut et Court",
        "themes": ["relazioni-e-collaborazione", "comunicazione", "identita-e-se"],
        "factor_codes": ["C4", "S2", "K1", "S5"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Un anno scolastico in una classe di periferia parigina, fra un insegnante e studenti che negoziano ogni parola.",
            "en": "A school year in a classroom on the outskirts of Paris, between a teacher and students who negotiate every word.",
        },
        "why_i18n": {
            "it": "Mostra la classe come luogo di conflitto e di trattativa, non come sfondo neutro dello studio.",
            "en": "Shows the classroom as a place of conflict and negotiation rather than a neutral backdrop to study.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Cantet, L. (2008). Entre les murs. Haut et Court.",
        "sort_order": 153,
    },
    {
        "slug": "marsh-teoria-del-tutto",
        "kind": "film",
        "title": "La teoria del tutto",
        "original_title": "The Theory of Everything",
        "creators": ["James Marsh"],
        "year": 2014,
        "publisher": "Working Title Films",
        "themes": ["futuro-e-orientamento", "fiducia-in-se", "relazioni-e-collaborazione"],
        "factor_codes": ["AD1", "A6", "C4"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Gli anni di dottorato di Stephen Hawking a Cambridge, fra la ricerca sull'origine dell'universo e la diagnosi di una malattia degenerativa.",
            "en": "Stephen Hawking's doctoral years at Cambridge, between research on the origin of the universe and the diagnosis of a degenerative disease.",
        },
        "why_i18n": {
            "it": "Il lavoro intellettuale che continua dentro un vincolo fisico che peggiora: utile a chi studia in condizioni che non ha scelto.",
            "en": "Intellectual work continuing inside a worsening physical constraint: useful for a student working in conditions they did not choose.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Marsh, J. (2014). The Theory of Everything. Working Title Films.",
        "sort_order": 154,
    },
    {
        "slug": "howard-beautiful-mind",
        "kind": "film",
        "title": "A Beautiful Mind",
        "original_title": "A Beautiful Mind",
        "creators": ["Ron Howard"],
        "year": 2001,
        "publisher": "Universal Pictures",
        "themes": ["ansia-e-prestazione", "identita-e-se", "relazioni-e-collaborazione"],
        "factor_codes": ["A1", "S5", "C4"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "La carriera del matematico John Nash, dall'intuizione che lo rende celebre alla schizofrenia con cui convive per decenni.",
            "en": "The career of mathematician John Nash, from the insight that made him famous to the schizophrenia he lives with for decades.",
        },
        "why_i18n": {
            "it": "Separa il valore del lavoro dalla condizione di chi lo fa, senza trasformare la malattia in una condizione del talento.",
            "en": "Separates the value of the work from the condition of the person doing it, without turning illness into a requirement for talent.",
        },
        "is_sensitive": True,
        "content_warning": "Racconta un disturbo psicotico, allucinazioni e un trattamento psichiatrico coatto.",
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Howard, R. (2001). A Beautiful Mind. Universal Pictures.",
        "sort_order": 155,
    },
    {
        "slug": "lagravenese-freedom-writers",
        "kind": "film",
        "title": "Freedom Writers",
        "original_title": "Freedom Writers",
        "creators": ["Richard LaGravenese"],
        "year": 2007,
        "publisher": "Paramount Pictures",
        "themes": ["relazioni-e-collaborazione", "metodo-di-studio", "identita-e-se"],
        "factor_codes": ["C4", "S2", "S5"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Una classe divisa dalle bande di Los Angeles comincia a tenere un diario, e la scrittura diventa il primo terreno comune.",
            "en": "A class divided by Los Angeles gang lines starts keeping journals, and writing becomes the first common ground.",
        },
        "why_i18n": {
            "it": "La scrittura come strumento di studio e di riconoscimento reciproco, in un contesto che non favorisce nessuno dei due.",
            "en": "Writing as a tool for study and for mutual recognition, in a setting that supports neither.",
        },
        "is_sensitive": True,
        "content_warning": "Contiene violenza fra bande, un omicidio e riferimenti a razzismo e Shoah.",
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "LaGravenese, R. (2007). Freedom Writers. Paramount Pictures.",
        "sort_order": 156,
    },
    {
        "slug": "nakache-quasi-amici",
        "kind": "film",
        "title": "Quasi amici - Intouchables",
        "original_title": "Intouchables",
        "creators": ["Olivier Nakache", "Eric Toledano"],
        "year": 2011,
        "publisher": "Gaumont",
        "themes": ["relazioni-e-collaborazione", "emozioni", "lavoro-e-vocazione"],
        "factor_codes": ["C4", "K1", "AD1"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un uomo tetraplegico assume come badante un giovane appena uscito dal carcere, e il rapporto funziona proprio perche' nessuno dei due recita il ruolo previsto.",
            "en": "A quadriplegic man hires a young ex-convict as his carer, and the relationship works precisely because neither plays the expected role.",
        },
        "why_i18n": {
            "it": "Una relazione di aiuto che non passa dalla pieta': utile per parlare di come si chiede e si offre sostegno.",
            "en": "A helping relationship that does not run on pity: useful for talking about how support is asked for and offered.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Nakache, O., Toledano, E. (2011). Intouchables. Gaumont.",
        "sort_order": 157,
    },
    {
        "slug": "westover-educated",
        "kind": "essay",
        "title": "L'educazione",
        "original_title": "Educated: A Memoir",
        "creators": ["Tara Westover"],
        "year": 2018,
        "publisher": "Random House (ed. it. Feltrinelli)",
        "themes": ["transizione-scuola-universita", "identita-e-se", "curiosita-ed-esplorazione", "lavoro-e-vocazione"],
        "factor_codes": ["AD1", "S5", "AD3"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Cresciuta in una famiglia che rifiutava la scuola, l'autrice entra all'universita' a diciassette anni senza aver mai frequentato una classe.",
            "en": "Raised in a family that rejected schooling, the author enters university at seventeen having never attended a classroom.",
        },
        "why_i18n": {
            "it": "L'ingresso nello studio come rottura con l'ambiente d'origine, e il prezzo che comporta: utile a chi e' il primo della famiglia a studiare.",
            "en": "Entering education as a break with one's origins, and what that costs: useful for a first-generation student.",
        },
        "is_sensitive": True,
        "content_warning": "Racconta violenza familiare, incidenti gravi e il rifiuto di cure mediche.",
        "where_to_find": "In libreria e in biblioteca; edizione italiana Feltrinelli.",
        "source_reference": "Westover, T. (2018). Educated: A Memoir. Random House.",
        "sort_order": 158,
    },
    {
        "slug": "epstein-range",
        "kind": "essay",
        "title": "Range",
        "original_title": "Range: Why Generalists Triumph in a Specialized World",
        "creators": ["David Epstein"],
        "year": 2019,
        "publisher": "Riverhead Books",
        "themes": ["lavoro-e-vocazione", "futuro-e-orientamento", "scelta-e-decisione"],
        "factor_codes": ["AD1", "AD2", "T5"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "de"],
        "summary_i18n": {
            "it": "Perche' in molti campi chi arriva tardi e per vie traverse batte chi si e' specializzato subito.",
            "en": "Why in many fields those who arrive late and by indirect routes outperform those who specialized early.",
        },
        "why_i18n": {
            "it": "Per chi teme di aver perso tempo o di aver scelto troppo tardi il proprio ambito.",
            "en": "For a student who fears having wasted time or chosen their field too late.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana disponibile.",
        "source_reference": "Epstein, D. (2019). Range. Riverhead Books.",
        "sort_order": 159,
    },
    {
        "slug": "clear-atomic-habits",
        "kind": "essay",
        "title": "Piccole abitudini per grandi cambiamenti",
        "original_title": "Atomic Habits",
        "creators": ["James Clear"],
        "year": 2018,
        "publisher": "Avery (ed. it. Corbaccio)",
        "themes": ["organizzazione-e-tempo", "motivazione-e-volizione"],
        "factor_codes": ["C2", "C3", "A5", "S3"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Come si costruisce e si smonta un'abitudine, lavorando sull'ambiente e sulle azioni minime invece che sulla motivazione.",
            "en": "How a habit is built and dismantled by working on the environment and on minimal actions rather than on motivation.",
        },
        "why_i18n": {
            "it": "Utile a chi si ripropone di studiare ogni giorno e non ci riesce: sposta il problema dalla volonta' alla struttura.",
            "en": "Useful for a student who resolves to study daily and fails: it moves the problem from willpower to structure.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Corbaccio.",
        "source_reference": "Clear, J. (2018). Atomic Habits. Avery.",
        "sort_order": 160,
    },
    {
        "slug": "kahneman-pensieri",
        "kind": "essay",
        "title": "Pensieri lenti e veloci",
        "original_title": "Thinking, Fast and Slow",
        "creators": ["Daniel Kahneman"],
        "year": 2011,
        "publisher": "Farrar, Straus and Giroux (ed. it. Mondadori)",
        "themes": ["scelta-e-decisione", "fallimento-e-attribuzione"],
        "factor_codes": ["AD2", "A3", "A4"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Due modi di pensare, uno rapido e automatico e uno lento e faticoso, e gli errori sistematici che il primo produce.",
            "en": "Two ways of thinking, one fast and automatic and one slow and effortful, and the systematic errors the first produces.",
        },
        "why_i18n": {
            "it": "Da' un vocabolario agli errori di valutazione su di se' e sulle proprie scelte, senza ridurli a distrazione.",
            "en": "Gives a vocabulary for misjudgements about oneself and one's choices, without reducing them to carelessness.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Mondadori.",
        "source_reference": "Kahneman, D. (2011). Thinking, Fast and Slow. Farrar, Straus and Giroux.",
        "sort_order": 161,
    },
    {
        "slug": "lee-buio-oltre-siepe",
        "kind": "fiction",
        "title": "Il buio oltre la siepe",
        "original_title": "To Kill a Mockingbird",
        "creators": ["Harper Lee"],
        "year": 1960,
        "publisher": "J. B. Lippincott (ed. it. Feltrinelli)",
        "themes": ["identita-e-se", "relazioni-e-collaborazione", "fiducia-in-se"],
        "factor_codes": ["S5", "C4", "A6"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Una bambina osserva il padre avvocato difendere un uomo nero in Alabama negli anni Trenta, e capisce a poco a poco che cosa costa avere ragione da soli.",
            "en": "A girl watches her lawyer father defend a Black man in 1930s Alabama, and gradually understands what it costs to be right alone.",
        },
        "why_i18n": {
            "it": "Il coraggio come scelta ripetuta e impopolare, non come tratto: utile quando la pressione del gruppo pesa piu' del giudizio proprio.",
            "en": "Courage as a repeated, unpopular choice rather than a trait: useful when peer pressure weighs more than one's own judgement.",
        },
        "is_sensitive": True,
        "content_warning": "Contiene razzismo esplicito, un processo per stupro e un linciaggio sfiorato.",
        "where_to_find": "In libreria e in biblioteca; edizione italiana Feltrinelli.",
        "source_reference": "Lee, H. (1960). To Kill a Mockingbird. J. B. Lippincott.",
        "sort_order": 162,
    },
    {
        "slug": "rosenberg-cnv",
        "kind": "essay",
        "title": "Le parole sono finestre (oppure muri)",
        "original_title": "Nonviolent Communication: A Language of Life",
        "creators": ["Marshall B. Rosenberg"],
        "year": 2003,
        "publisher": "PuddleDancer Press (ed. it. Esserci)",
        "themes": ["comunicazione", "relazioni-e-collaborazione", "emozioni"],
        "factor_codes": ["S2", "K1", "C4"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un metodo in quattro passaggi — osservazione, sentimento, bisogno, richiesta — per dire quello che serve senza accusare.",
            "en": "A four-step method — observation, feeling, need, request — for saying what one needs without accusing.",
        },
        "why_i18n": {
            "it": "Utile quando un confronto con docenti, compagni o famiglia si blocca sul tono prima ancora che sul merito.",
            "en": "Useful when a conversation with teachers, classmates or family stalls on tone before it reaches the substance.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Esserci.",
        "source_reference": "Rosenberg, M. B. (2003). Nonviolent Communication: A Language of Life. PuddleDancer Press.",
        "sort_order": 163,
    },
    {
        "slug": "brackett-permission-to-feel",
        "kind": "essay",
        "title": "Permission to Feel",
        "original_title": "Permission to Feel",
        "creators": ["Marc Brackett"],
        "year": 2019,
        "publisher": "Celadon Books",
        "themes": ["emozioni", "ansia-e-prestazione"],
        "factor_codes": ["A7", "A1", "K2"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["en", "es", "de"],
        "summary_i18n": {
            "it": "Un metodo per riconoscere e nominare le emozioni a scuola, costruito su vent'anni di lavoro con studenti e insegnanti.",
            "en": "A method for recognizing and naming emotions at school, built on twenty years of work with students and teachers.",
        },
        "why_i18n": {
            "it": "Da' parole a chi dice solo di stare male o di essere stanco, senza saper distinguere che cosa stia provando.",
            "en": "Gives words to a student who only says they feel bad or tired, without being able to tell what they are feeling.",
        },
        "where_to_find": "In libreria e in biblioteca universitaria; edizione originale Celadon Books.",
        "source_reference": "Brackett, M. (2019). Permission to Feel. Celadon Books.",
        "sort_order": 164,
    },
    {
        "slug": "cain-quiet-power",
        "kind": "essay",
        "title": "Quiet Power",
        "original_title": "Quiet Power: The Secret Strengths of Introverts",
        "creators": ["Susan Cain"],
        "year": 2016,
        "publisher": "Dial Books",
        "themes": ["identita-e-se", "relazioni-e-collaborazione", "comunicazione"],
        "factor_codes": ["S5", "C4", "S2"],
        "audience": ["secondaria"],
        "available_languages": ["it", "en", "es", "de"],
        "summary_i18n": {
            "it": "La versione per ragazzi di Quiet: come funziona il temperamento introverso a scuola, in classe e fra amici.",
            "en": "The young readers' version of Quiet: how the introverted temperament works at school, in class and among friends.",
        },
        "why_i18n": {
            "it": "Parla alla fascia della secondaria con esempi scolastici, dove il libro per adulti resta astratto.",
            "en": "Speaks to secondary-school students with school examples, where the adult book stays abstract.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana disponibile.",
        "source_reference": "Cain, S. (2016). Quiet Power. Dial Books.",
        "sort_order": 165,
    },
    # --- narrativa e tempo: il catalogo aveva cinque romanzi contro diciannove film ---
    {
        "slug": "ende-momo",
        "kind": "fiction",
        "title": "Momo",
        "original_title": "Momo",
        "creators": ["Michael Ende"],
        "year": 1973,
        "publisher": "Thienemann (ed. it. Longanesi)",
        "themes": ["tempo-e-memoria", "organizzazione-e-tempo", "curiosita-ed-esplorazione", "relazioni-e-collaborazione"],
        "factor_codes": ["T2", "T3", "C2", "C3", "AD3"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Uomini grigi convincono una citta' a risparmiare tempo, e piu' se ne risparmia meno ne resta: una bambina se ne accorge prima degli adulti.",
            "en": "Grey men persuade a town to save time, and the more it saves the less it has: a child notices before the adults do.",
        },
        "why_i18n": {
            "it": "Mette in discussione l'idea che organizzarsi significhi comprimere: utile a chi riempie ogni ora e si sente comunque in ritardo.",
            "en": "Questions the idea that organizing means compressing: useful for a student who fills every hour and still feels behind.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Longanesi.",
        "source_reference": "Ende, M. (1973). Momo. Thienemann Verlag.",
        "sort_order": 170,
    },
    {
        "slug": "salinger-holden",
        "kind": "fiction",
        "title": "Il giovane Holden",
        "original_title": "The Catcher in the Rye",
        "creators": ["J. D. Salinger"],
        "year": 1951,
        "publisher": "Little, Brown (ed. it. Einaudi)",
        "themes": ["identita-e-se", "emozioni", "transizione-scuola-universita"],
        "factor_codes": ["S5", "K5", "A7", "AD1"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Espulso dall'ennesima scuola, un ragazzo passa tre giorni a New York senza dirlo a casa, in fuga da tutto cio' che giudica falso.",
            "en": "Expelled from yet another school, a boy spends three days in New York without telling his family, running from everything he judges phoney.",
        },
        "why_i18n": {
            "it": "Il rifiuto della scuola come linguaggio di un disagio piu' largo: utile quando l'abbandono viene letto solo come pigrizia.",
            "en": "Rejection of school as the language of a wider distress: useful when dropping out is read as mere laziness.",
        },
        "is_sensitive": True,
        "content_warning": "Racconta un lutto familiare, depressione e pensieri di morte, con linguaggio crudo.",
        "where_to_find": "In libreria e in biblioteca; edizione italiana Einaudi.",
        "source_reference": "Salinger, J. D. (1951). The Catcher in the Rye. Little, Brown and Company.",
        "sort_order": 171,
    },
    {
        "slug": "giordano-numeri-primi",
        "kind": "fiction",
        "title": "La solitudine dei numeri primi",
        "creators": ["Paolo Giordano"],
        "year": 2008,
        "publisher": "Mondadori",
        "themes": ["ansia-e-prestazione", "identita-e-se", "relazioni-e-collaborazione"],
        "factor_codes": ["A1", "A7", "S5", "C4"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Due ragazzi segnati da un trauma d'infanzia si riconoscono e si sfiorano per vent'anni, come due numeri primi gemelli che restano separati.",
            "en": "Two young people marked by childhood trauma recognize each other and keep missing each other for twenty years, like twin primes that stay apart.",
        },
        "why_i18n": {
            "it": "L'eccellenza accademica che convive con un dolore intatto: utile quando i risultati vengono presi come prova che tutto va bene.",
            "en": "Academic excellence coexisting with untouched pain: useful when results are taken as proof that everything is fine.",
        },
        "is_sensitive": True,
        "content_warning": "Contiene autolesionismo, un disturbo alimentare e un incidente grave nell'infanzia.",
        "where_to_find": "In libreria e in biblioteca; edizione Mondadori.",
        "source_reference": "Giordano, P. (2008). La solitudine dei numeri primi. Mondadori.",
        "sort_order": 172,
    },
    {
        "slug": "davenia-bianca-come-latte",
        "kind": "fiction",
        "title": "Bianca come il latte, rossa come il sangue",
        "creators": ["Alessandro D'Avenia"],
        "year": 2010,
        "publisher": "Mondadori",
        "themes": ["motivazione-e-volizione", "emozioni", "identita-e-se"],
        "factor_codes": ["A2", "A5", "A7", "S5"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["it", "en", "es", "de"],
        "summary_i18n": {
            "it": "Un sedicenne che considera la scuola un peso trova un motivo per starci, fra un supplente che lo prende sul serio e una ragazza malata.",
            "en": "A sixteen-year-old who sees school as a burden finds a reason to stay, between a substitute teacher who takes him seriously and a girl who falls ill.",
        },
        "why_i18n": {
            "it": "La motivazione scolastica che nasce da una relazione e da un senso, non da un rimprovero: parla direttamente alla secondaria.",
            "en": "School motivation arising from a relationship and a meaning rather than a reprimand: it speaks directly to secondary students.",
        },
        "is_sensitive": True,
        "content_warning": "Racconta la malattia e la morte di un'adolescente.",
        "where_to_find": "In libreria e in biblioteca; edizione Mondadori.",
        "source_reference": "D'Avenia, A. (2010). Bianca come il latte, rossa come il sangue. Mondadori.",
        "sort_order": 173,
    },
    {
        "slug": "geda-coccodrilli",
        "kind": "fiction",
        "title": "Nel mare ci sono i coccodrilli",
        "creators": ["Fabio Geda"],
        "year": 2010,
        "publisher": "Baldini Castoldi Dalai",
        "themes": ["transizione-scuola-universita", "fiducia-in-se", "identita-e-se"],
        "factor_codes": ["AD1", "A6", "S5"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "La storia vera di Enaiatollah Akbari, lasciato dalla madre in Pakistan a dieci anni, che attraversa cinque paesi prima di arrivare in Italia e tornare a studiare.",
            "en": "The true story of Enaiatollah Akbari, left by his mother in Pakistan at ten, who crosses five countries before reaching Italy and returning to school.",
        },
        "why_i18n": {
            "it": "Ricomincia a studiare da adulto in una lingua non sua: utile a chi si sente fuori tempo o fuori posto in un percorso.",
            "en": "He resumes study as an adult in a language not his own: useful for a student who feels out of time or out of place in a path.",
        },
        "is_sensitive": True,
        "content_warning": "Racconta l'abbandono di un bambino, lavoro minorile e viaggi migratori pericolosi.",
        "where_to_find": "In libreria e in biblioteca; edizione Baldini Castoldi Dalai.",
        "source_reference": "Geda, F. (2010). Nel mare ci sono i coccodrilli. Baldini Castoldi Dalai.",
        "sort_order": 174,
    },
    {
        "slug": "cognetti-otto-montagne",
        "kind": "fiction",
        "title": "Le otto montagne",
        "creators": ["Paolo Cognetti"],
        "year": 2016,
        "publisher": "Einaudi",
        "themes": ["scelta-e-decisione", "identita-e-se", "relazioni-e-collaborazione"],
        "factor_codes": ["AD2", "S5", "C4"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Due amici cresciuti nella stessa valle prendono strade opposte, chi restando e chi andandosene, e si ritrovano da adulti a fare i conti con quella scelta.",
            "en": "Two friends who grew up in the same valley take opposite roads, one staying and one leaving, and meet again as adults to reckon with that choice.",
        },
        "why_i18n": {
            "it": "Due modi legittimi di costruirsi una vita, senza che il romanzo dica quale sia quello giusto: utile a chi cerca la scelta corretta invece della propria.",
            "en": "Two legitimate ways of building a life, with no verdict on which is right: useful for a student looking for the correct choice instead of their own.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione Einaudi.",
        "source_reference": "Cognetti, P. (2016). Le otto montagne. Einaudi.",
        "sort_order": 175,
    },
    {
        "slug": "williams-stoner",
        "kind": "fiction",
        "title": "Stoner",
        "original_title": "Stoner",
        "creators": ["John Williams"],
        "year": 1965,
        "publisher": "Viking Press (ed. it. Fazi)",
        "themes": ["lavoro-e-vocazione", "tempo-e-memoria", "identita-e-se"],
        "factor_codes": ["AD1", "T2", "S5"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Figlio di contadini iscritto ad agraria, William Stoner scopre la letteratura durante un corso obbligatorio e passa il resto della vita a insegnarla.",
            "en": "The son of farmers enrolled in agriculture, William Stoner discovers literature during a required course and spends the rest of his life teaching it.",
        },
        "why_i18n": {
            "it": "Una vocazione nata per caso dentro un corso non scelto, e una carriera ordinaria vissuta come propria: utile a chi crede che la strada giusta debba essere evidente.",
            "en": "A calling born by chance inside an unchosen course, and an ordinary career lived as one's own: useful for a student who believes the right path must be obvious.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Fazi.",
        "source_reference": "Williams, J. (1965). Stoner. Viking Press.",
        "sort_order": 176,
    },
    {
        "slug": "saint-exupery-piccolo-principe",
        "kind": "fiction",
        "title": "Il piccolo principe",
        "original_title": "Le Petit Prince",
        "creators": ["Antoine de Saint-Exupery"],
        "year": 1943,
        "publisher": "Reynal & Hitchcock (ed. it. Bompiani)",
        "themes": ["relazioni-e-collaborazione", "curiosita-ed-esplorazione", "identita-e-se"],
        "factor_codes": ["C4", "AD3", "S5", "K1"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un aviatore precipitato nel deserto incontra un bambino venuto da un altro pianeta, che gli racconta i grandi impegnati a contare cose che non capiscono.",
            "en": "A pilot stranded in the desert meets a child from another planet, who tells him of grown-ups busy counting things they do not understand.",
        },
        "why_i18n": {
            "it": "Distingue il misurare dal comprendere: utile quando lo studio si riduce a numeri e il senso di cio' che si fa sparisce.",
            "en": "Separates measuring from understanding: useful when study shrinks to numbers and the point of the work disappears.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Bompiani.",
        "source_reference": "Saint-Exupery, A. de (1943). Le Petit Prince. Reynal & Hitchcock.",
        "sort_order": 177,
    },
    {
        "slug": "burkeman-quattromila-settimane",
        "kind": "essay",
        "title": "Quattromila settimane",
        "original_title": "Four Thousand Weeks: Time Management for Mortals",
        "creators": ["Oliver Burkeman"],
        "year": 2021,
        "publisher": "Farrar, Straus and Giroux (ed. it. Rizzoli)",
        "themes": ["organizzazione-e-tempo", "tempo-e-memoria", "scelta-e-decisione"],
        "factor_codes": ["C2", "C3", "T3", "AD2"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Una vita media dura circa quattromila settimane: il libro parte da questo limite per criticare le tecniche che promettono di far entrare tutto.",
            "en": "An average life lasts about four thousand weeks: the book starts from that limit to criticize the techniques that promise to fit everything in.",
        },
        "why_i18n": {
            "it": "Sposta il problema dal fare di piu' allo scegliere che cosa lasciar cadere: utile a chi ha gia' provato ogni metodo di produttivita'.",
            "en": "Moves the problem from doing more to choosing what to drop: useful for a student who has already tried every productivity method.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Rizzoli.",
        "source_reference": "Burkeman, O. (2021). Four Thousand Weeks. Farrar, Straus and Giroux.",
        "sort_order": 178,
    },
    {
        "slug": "mcgonigal-lato-positivo-stress",
        "kind": "essay",
        "title": "Il lato positivo dello stress",
        "original_title": "The Upside of Stress",
        "creators": ["Kelly McGonigal"],
        "year": 2015,
        "publisher": "Avery (ed. it. Giunti)",
        "themes": ["ansia-e-prestazione", "emozioni", "fiducia-in-se"],
        "factor_codes": ["A1", "A7", "A6", "K2"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "de"],
        "summary_i18n": {
            "it": "La ricerca su come cambia la risposta fisiologica allo stress quando lo si considera una risorsa invece che un danno.",
            "en": "The research on how the physiological response to stress changes when it is seen as a resource rather than as harm.",
        },
        "why_i18n": {
            "it": "Utile a chi legge l'attivazione prima di un esame come il segno che andra' male, invece che come il corpo che si prepara.",
            "en": "Useful for a student who reads pre-exam arousal as a sign of failure rather than as the body getting ready.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Giunti.",
        "source_reference": "McGonigal, K. (2015). The Upside of Stress. Avery.",
        "sort_order": 179,
    },
    {
        "slug": "draaisma-tempo-vola",
        "kind": "essay",
        "title": "Perche' il tempo vola",
        "original_title": "Why Life Speeds Up As You Get Older",
        "creators": ["Douwe Draaisma"],
        "year": 2004,
        "publisher": "Cambridge University Press (ed. it. Bruno Mondadori)",
        "themes": ["tempo-e-memoria"],
        "factor_codes": ["T1", "T2", "T3"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "de"],
        "summary_i18n": {
            "it": "Perche' la memoria comprime alcuni periodi e ne dilata altri, e perche' gli anni sembrano accorciarsi con l'eta'.",
            "en": "Why memory compresses some periods and stretches others, and why the years seem to grow shorter with age.",
        },
        "why_i18n": {
            "it": "Da' una base al modo in cui si percepisce il tempo di studio, che raramente coincide con quello dell'orologio.",
            "en": "Grounds the way study time is experienced, which rarely matches the clock.",
        },
        "where_to_find": "In biblioteca; edizione italiana Bruno Mondadori.",
        "source_reference": "Draaisma, D. (2004). Why Life Speeds Up As You Get Older. Cambridge University Press.",
        "sort_order": 180,
    },
]



def seed_certified_readings(db, models_module) -> int:
    """Crea le letture mancanti. Idempotente: non tocca gli slug gia' presenti."""
    inserted = 0
    for spec in SEED_CERTIFIED_READINGS:
        exists = (
            db.query(models_module.CertifiedReading)
            .filter(models_module.CertifiedReading.slug == spec["slug"])
            .first()
        )
        if exists:
            continue
        data = dict(spec)
        db.add(models_module.CertifiedReading(
            certified_by="Seme iniziale del catalogo letture",
            # Nasce in bozza: la certificazione la da' l'admin dopo la verifica.
            status="draft",
            is_active=True,
            **data,
        ))
        inserted += 1
    if inserted:
        db.commit()
    return inserted
