"""Seme minimo del catalogo delle letture certificate.

Idempotente: crea solo gli slug mancanti e non tocca le voci gia' presenti, come
il seed delle strategie. E' un punto di partenza verificabile, non un canone: il
catalogo vero lo costruiscono gli admin dal pannello.

I testi sono seminati in italiano e inglese; il campo e' JSON per lingua, quindi
le altre quattro si aggiungono dal pannello senza migrazioni.
"""
from __future__ import annotations

from typing import Any

SEED_CERTIFIED_READINGS: list[dict[str, Any]] = [
    # --- saggistica divulgativa ---
    {
        "slug": "dweck-mindset",
        "kind": "essay",
        "title": "Mindset. Cambiare forma mentis per raggiungere il successo",
        "original_title": "Mindset: The New Psychology of Success",
        "creators": ["Carol S. Dweck"],
        "year": 2006,
        "publisher": "Random House (ed. it. Franco Angeli)",
        "themes": ["fallimento-e-attribuzione", "fiducia-in-se", "motivazione-e-volizione"],
        "factor_codes": ["A3", "A4", "A6", "K5"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "La differenza fra credere che l'intelligenza sia fissa e crederla allenabile, e come questa convinzione cambia il modo di reagire agli errori.",
            "en": "The difference between believing ability is fixed and believing it can grow, and how that belief changes the response to failure.",
        },
        "why_i18n": {
            "it": "Utile quando un risultato basso viene letto come un verdetto sulle proprie capacita' invece che su una strategia da cambiare.",
            "en": "Useful when a low score is read as a verdict on ability rather than on a strategy that can change.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Franco Angeli.",
        "source_reference": "Dweck, C. S. (2006). Mindset: The New Psychology of Success. Random House.",
        "sort_order": 10,
    },
    {
        "slug": "oakley-mind-for-numbers",
        "kind": "essay",
        "title": "Impara a imparare",
        "original_title": "A Mind for Numbers",
        "creators": ["Barbara Oakley"],
        "year": 2014,
        "publisher": "TarcherPerigee (ed. it. Vallardi)",
        "themes": ["metodo-di-studio", "organizzazione-e-tempo"],
        "factor_codes": ["C1", "C2", "C5", "C7", "S4", "K4"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["it", "en", "es", "de"],
        "summary_i18n": {
            "it": "Come funzionano attenzione diffusa e attenzione concentrata, e perche' distribuire lo studio nel tempo rende piu' di rileggere.",
            "en": "How focused and diffuse attention work, and why spacing study beats rereading.",
        },
        "why_i18n": {
            "it": "Da' una base concreta a chi studia molto ma con tecniche che non tengono, come la rilettura ripetuta.",
            "en": "Gives concrete grounding to a student who studies hard with techniques that do not hold, such as rereading.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Vallardi.",
        "source_reference": "Oakley, B. (2014). A Mind for Numbers. TarcherPerigee.",
        "sort_order": 11,
    },
    {
        "slug": "duckworth-grit",
        "kind": "essay",
        "title": "Grit. La forza della passione e della perseveranza",
        "original_title": "Grit: The Power of Passion and Perseverance",
        "creators": ["Angela Duckworth"],
        "year": 2016,
        "publisher": "Scribner (ed. it. Giunti)",
        "themes": ["motivazione-e-volizione", "fiducia-in-se"],
        "factor_codes": ["A2", "A5", "S3", "K3"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Perche' la costanza su un interesse coltivato nel tempo pesa piu' del talento dichiarato.",
            "en": "Why sustained effort on a cultivated interest matters more than declared talent.",
        },
        "why_i18n": {
            "it": "Per chi parte con slancio e si ferma dopo pochi giorni, e legge questo come mancanza di talento.",
            "en": "For a student who starts strongly, stops after a few days, and reads that as lack of talent.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Giunti.",
        "source_reference": "Duckworth, A. (2016). Grit. Scribner.",
        "sort_order": 12,
    },
    {
        "slug": "zimbardo-boyd-time-paradox",
        "kind": "essay",
        "title": "Il paradosso del tempo",
        "original_title": "The Time Paradox",
        "creators": ["Philip Zimbardo", "John Boyd"],
        "year": 2008,
        "publisher": "Free Press (ed. it. Mondadori)",
        "themes": ["tempo-e-memoria", "futuro-e-orientamento"],
        "factor_codes": ["T1", "T2", "T3", "T4", "T5"],
        "questionnaire_types": ["ZTPI"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es"],
        "summary_i18n": {
            "it": "Le cinque prospettive temporali degli autori dello ZTPI, e come uno sbilanciamento verso il passato o il presente pesa sulle scelte.",
            "en": "The five time perspectives from the authors of the ZTPI, and how leaning too far into past or present shapes choices.",
        },
        "why_i18n": {
            "it": "E' il libro degli autori dello strumento: chiarisce da dove vengono i fattori del profilo temporale.",
            "en": "Written by the authors of the instrument: it explains where the time profile factors come from.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Mondadori.",
        "source_reference": "Zimbardo, P. & Boyd, J. (2008). The Time Paradox. Free Press.",
        "sort_order": 13,
    },
    # --- articoli divulgati ---
    {
        "slug": "dunlosky-learning-techniques",
        "kind": "article",
        "title": "Improving Students' Learning With Effective Learning Techniques",
        "creators": ["John Dunlosky", "Katherine A. Rawson", "Elizabeth J. Marsh",
                     "Mitchell J. Nathan", "Daniel T. Willingham"],
        "year": 2013,
        "publisher": "Psychological Science in the Public Interest",
        "identifiers": {"doi": "10.1177/1529100612453266"},
        "themes": ["metodo-di-studio", "organizzazione-e-tempo"],
        "factor_codes": ["C1", "C2", "C5", "C7"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "La rassegna che mette in fila dieci tecniche di studio e dice quali reggono alla prova sperimentale: pratica di recupero e studio distribuito in testa.",
            "en": "The review that ranks ten study techniques by how well they hold up experimentally: retrieval practice and spacing come first.",
        },
        "why_i18n": {
            "it": "E' la fonte da cui vengono diverse strategie certificate del catalogo: utile a chi vuole vedere le prove dietro il consiglio.",
            "en": "It is the source behind several certified strategies in the catalog: for a student who wants the evidence behind the advice.",
        },
        "where_to_find": "Accesso aperto tramite il DOI indicato.",
        "source_reference": "Dunlosky et al. (2013), PSPI 14(1), 4-58.",
        "sort_order": 20,
    },
    {
        "slug": "ramirez-beilock-writing-worries",
        "kind": "article",
        "title": "Writing About Testing Worries Boosts Exam Performance in the Classroom",
        "creators": ["Gerardo Ramirez", "Sian L. Beilock"],
        "year": 2011,
        "publisher": "Science",
        "identifiers": {"doi": "10.1126/science.1199427"},
        "themes": ["ansia-e-prestazione", "emozioni"],
        "factor_codes": ["A1", "A7", "S1", "K2"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "Dieci minuti di scrittura sulle proprie preoccupazioni prima di una prova migliorano il risultato di chi soffre d'ansia da esame.",
            "en": "Ten minutes of writing about one's worries before a test improves the performance of test-anxious students.",
        },
        "why_i18n": {
            "it": "E' lo studio dietro la strategia certificata della scrittura espressiva prima della verifica.",
            "en": "It is the study behind the certified expressive-writing strategy used before a test.",
        },
        "where_to_find": "Tramite il DOI indicato; molte biblioteche universitarie hanno l'accesso.",
        "source_reference": "Ramirez, G. & Beilock, S. (2011). Science 331(6014), 211-213.",
        "sort_order": 21,
    },
    # --- narrativa ---
    {
        "slug": "pennac-diario-di-scuola",
        "kind": "fiction",
        "title": "Diario di scuola",
        "original_title": "Chagrin d'ecole",
        "creators": ["Daniel Pennac"],
        "year": 2007,
        "publisher": "Gallimard (ed. it. Feltrinelli)",
        "themes": ["fallimento-e-attribuzione", "identita-e-se", "fiducia-in-se"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "fr", "en", "es", "de"],
        "summary_i18n": {
            "it": "Il racconto di un pessimo studente diventato scrittore e insegnante, dal punto di vista di chi a scuola si sentiva un caso perso.",
            "en": "The story of a hopeless pupil who became a writer and a teacher, told from inside the experience of feeling written off.",
        },
        "why_i18n": {
            "it": "Per chi ha smesso di credere di poter cambiare rendimento: mostra il vissuto, non la teoria dell'insuccesso scolastico.",
            "en": "For a student who has stopped believing performance can change: it shows the lived side of school failure, not the theory.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Feltrinelli.",
        "source_reference": "Pennac, D. (2007). Chagrin d'ecole. Gallimard. Premio Renaudot 2007.",
        "sort_order": 30,
    },
    {
        "slug": "calvino-barone-rampante",
        "kind": "fiction",
        "title": "Il barone rampante",
        "creators": ["Italo Calvino"],
        "year": 1957,
        "publisher": "Einaudi",
        "themes": ["scelta-e-decisione", "identita-e-se"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un ragazzo sale su un albero per non obbedire e decide di non scendere piu': una scelta tenuta per tutta la vita, con quello che costa e quello che apre.",
            "en": "A boy climbs a tree in refusal and decides never to come down: a single choice held for a lifetime, with everything it costs and opens.",
        },
        "why_i18n": {
            "it": "Per ragionare su che cosa significa tenere una decisione nel tempo, invece di viverla come un bivio istantaneo.",
            "en": "To think about what it means to hold a decision over time, rather than treat it as one instantaneous fork.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione Einaudi o Mondadori.",
        "source_reference": "Calvino, I. (1957). Il barone rampante. Einaudi.",
        "sort_order": 31,
    },
    {
        "slug": "ferrante-amica-geniale",
        "kind": "fiction",
        "title": "L'amica geniale",
        "creators": ["Elena Ferrante"],
        "year": 2011,
        "publisher": "Edizioni E/O",
        "themes": ["transizione-scuola-universita", "identita-e-se", "relazioni-e-collaborazione"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Due bambine in un rione povero di Napoli: per una la scuola diventa la via d'uscita, per l'altra si chiude presto.",
            "en": "Two girls in a poor Naples neighbourhood: for one, school becomes the way out; for the other it closes early.",
        },
        "why_i18n": {
            "it": "Per chi vive lo studio come una porta stretta fra sé e la propria origine, e ne sente il peso.",
            "en": "For a student who experiences study as a narrow door between themselves and where they come from.",
        },
        "where_to_find": "In libreria e in biblioteca; edizioni E/O.",
        "source_reference": "Ferrante, E. (2011). L'amica geniale. Edizioni E/O.",
        "sort_order": 32,
    },
    # --- film e documentari ---
    {
        "slug": "bergman-posto-delle-fragole",
        "kind": "film",
        "title": "Il posto delle fragole",
        "original_title": "Smultronstallet",
        "creators": ["Ingmar Bergman"],
        "year": 1957,
        "publisher": "Svensk Filmindustri",
        "themes": ["tempo-e-memoria", "futuro-e-orientamento"],
        "factor_codes": ["T1", "T2"],
        "questionnaire_types": ["ZTPI"],
        "audience": ["universita", "adulti"],
        "available_languages": ["sv", "it", "en"],
        "summary_i18n": {
            "it": "Un anziano professore attraversa la Svezia per un premio e fa i conti con il proprio passato lungo la strada.",
            "en": "An elderly professor drives across Sweden to receive an award and settles accounts with his own past along the way.",
        },
        "why_i18n": {
            "it": "Mostra che cosa vuol dire guardare al passato con rimpianto invece che come a una risorsa: il tema centrale del profilo temporale.",
            "en": "It shows what it means to look at the past with regret rather than as a resource: the core question of the time profile.",
        },
        "where_to_find": "Disponibile in DVD e su piattaforme di cinema d'autore; spesso nelle mediateche.",
        "source_reference": "Bergman, I. (1957). Smultronstallet. Svensk Filmindustri.",
        "sort_order": 40,
    },
    {
        "slug": "weir-attimo-fuggente",
        "kind": "film",
        "title": "L'attimo fuggente",
        "original_title": "Dead Poets Society",
        "creators": ["Peter Weir"],
        "year": 1989,
        "publisher": "Touchstone Pictures",
        "themes": ["scelta-e-decisione", "identita-e-se", "futuro-e-orientamento"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "is_sensitive": True,
        "content_warning": "Il film contiene il suicidio di un personaggio adolescente. Va proposto dicendolo prima, e non a chi sta portando in conversazione un disagio personale.",
        "summary_i18n": {
            "it": "In un collegio rigido un professore di lettere spinge i suoi studenti a decidere che vita vogliono, con conseguenze che non controlla.",
            "en": "In a strict boarding school a literature teacher pushes his students to decide what life they want, with consequences he cannot control.",
        },
        "why_i18n": {
            "it": "Per ragionare sul conflitto fra le attese della famiglia e la propria scelta di studio, senza far finta che sia un conflitto semplice.",
            "en": "To think about the conflict between family expectations and one's own choice of study, without pretending it is a simple one.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Weir, P. (1989). Dead Poets Society. Touchstone Pictures.",
        "sort_order": 41,
    },
    {
        "slug": "ted-duckworth-grit",
        "kind": "video",
        "title": "Grit: the power of passion and perseverance",
        "creators": ["Angela Duckworth"],
        "year": 2013,
        "publisher": "TED Talks Education",
        "themes": ["motivazione-e-volizione"],
        "factor_codes": ["A2", "A5", "S3"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["en", "it", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Sei minuti in cui l'autrice riassume la sua ricerca sulla perseveranza, con sottotitoli in molte lingue.",
            "en": "Six minutes in which the author sums up her research on perseverance, subtitled in many languages.",
        },
        "why_i18n": {
            "it": "Un primo passo breve per chi non vuole partire da un libro intero.",
            "en": "A short first step for a student who does not want to start with a whole book.",
        },
        "where_to_find": "Archivio TED, con trascrizione e sottotitoli.",
        "source_reference": "Duckworth, A. (2013). TED Talks Education.",
        "sort_order": 50,
    },
    # --- comunicazione ---
    {
        "slug": "anderson-ted-talks",
        "kind": "essay",
        "title": "TED Talks. Il manuale ufficiale del public speaking",
        "original_title": "TED Talks: The Official TED Guide to Public Speaking",
        "creators": ["Chris Anderson"],
        "year": 2016,
        "publisher": "Houghton Mifflin Harcourt (ed. it. Rizzoli)",
        "themes": ["comunicazione"],
        "factor_codes": ["S2", "K1"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "summary_i18n": {
            "it": "Come si prepara un intervento: una sola idea da consegnare, una struttura che regge, e le prove che tolgono il resto.",
            "en": "How a talk is prepared: one idea to hand over, a structure that holds, and rehearsal that strips out the rest.",
        },
        "why_i18n": {
            "it": "Smonta l'idea che parlare in pubblico sia un talento: lo tratta come un mestiere fatto di scelte e di prove.",
            "en": "It takes public speaking apart as a craft of choices and rehearsal, not a talent one either has or lacks.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Rizzoli.",
        "source_reference": "Anderson, C. (2016). TED Talks: The Official TED Guide to Public Speaking. Houghton Mifflin Harcourt.",
        "sort_order": 60,
    },
    {
        "slug": "hooper-discorso-del-re",
        "kind": "film",
        "title": "Il discorso del re",
        "original_title": "The King's Speech",
        "creators": ["Tom Hooper"],
        "year": 2010,
        "publisher": "See-Saw Films",
        "themes": ["comunicazione", "ansia-e-prestazione"],
        "factor_codes": ["S2", "K1", "S1"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Un re balbuziente deve parlare alla nazione e lavora per anni con un logopedista senza titoli.",
            "en": "A stammering king has to address a nation, and works for years with an unaccredited speech therapist.",
        },
        "why_i18n": {
            "it": "Mostra la fatica fisica dell'esposizione, non la retorica del superare le paure di slancio.",
            "en": "It shows the physical labour of speaking, not the rhetoric of conquering fear in one leap.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Hooper, T. (2010). The King's Speech. See-Saw Films.",
        "sort_order": 61,
    },
    {
        "slug": "treasure-how-to-speak",
        "kind": "video",
        "title": "How to speak so that people want to listen",
        "creators": ["Julian Treasure"],
        "year": 2013,
        "publisher": "TED",
        "themes": ["comunicazione"],
        "factor_codes": ["S2", "K1"],
        "audience": ["secondaria", "universita"],
        "available_languages": ["en", "it", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Dieci minuti sul come si parla — voce, ritmo, silenzi — invece che sul cosa dire.",
            "en": "Ten minutes on how one speaks — voice, pace, silence — rather than on what to say.",
        },
        "why_i18n": {
            "it": "Un primo passo breve per chi non vuole partire da un libro intero.",
            "en": "A short first step for a student who will not start with a whole book.",
        },
        "where_to_find": "Archivio TED, con trascrizione e sottotitoli.",
        "source_reference": "Treasure, J. (2013). TED Talk.",
        "sort_order": 62,
    },
    # --- curiosita ed esplorazione ---
    {
        "slug": "gruber-states-of-curiosity",
        "kind": "article",
        "title": "States of Curiosity Modulate Hippocampus-Dependent Learning via the Dopaminergic Circuit",
        "creators": ["Matthias J. Gruber", "Bernard D. Gelman", "Charan Ranganath"],
        "year": 2014,
        "publisher": "Neuron",
        "identifiers": {"doi": "10.1016/j.neuron.2014.08.060"},
        "themes": ["curiosita-ed-esplorazione", "metodo-di-studio"],
        "factor_codes": ["AD3"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "Quando la curiosita' e' attiva si ricorda meglio anche cio' che non c'entra con la domanda.",
            "en": "When curiosity is high, even incidental material is remembered better.",
        },
        "why_i18n": {
            "it": "Da' una base sperimentale al perche' esplorare prima di scegliere, invece di trattarlo come un consiglio di buon senso.",
            "en": "It gives experimental grounding to exploring before choosing, instead of leaving it as common sense.",
        },
        "where_to_find": "Tramite il DOI indicato; accesso spesso disponibile in biblioteca universitaria.",
        "source_reference": "Gruber, Gelman & Ranganath (2014). Neuron 84(2), 486-496.",
        "sort_order": 70,
    },
    {
        "slug": "wenders-sale-della-terra",
        "kind": "documentary",
        "title": "Il sale della terra",
        "original_title": "The Salt of the Earth",
        "creators": ["Wim Wenders", "Juliano Ribeiro Salgado"],
        "year": 2014,
        "publisher": "Decia Films",
        "themes": ["curiosita-ed-esplorazione", "lavoro-e-vocazione"],
        "factor_codes": ["AD3", "AD1"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de"],
        "is_sensitive": True,
        "content_warning": "Contiene immagini di carestie, esodi e violenza di guerra. Va annunciato prima di proporlo.",
        "summary_i18n": {
            "it": "Quarant'anni di lavoro del fotografo Sebastiao Salgado, raccontati da suo figlio e da Wenders.",
            "en": "Forty years of photographer Sebastiao Salgado's work, told by his son and by Wenders.",
        },
        "why_i18n": {
            "it": "La vocazione che si costruisce andando, non decidendo a tavolino, e il prezzo che chiede.",
            "en": "A vocation built by going rather than by deciding in advance, and what it costs.",
        },
        "where_to_find": "Disponibile in DVD e su piattaforme di documentari.",
        "source_reference": "Wenders, W. & Salgado, J. R. (2014). The Salt of the Earth.",
        "sort_order": 71,
    },
    # --- lavoro e vocazione ---
    {
        "slug": "melfi-diritto-di-contare",
        "kind": "film",
        "title": "Il diritto di contare",
        "original_title": "Hidden Figures",
        "creators": ["Theodore Melfi"],
        "year": 2016,
        "publisher": "Fox 2000 Pictures",
        "themes": ["lavoro-e-vocazione", "relazioni-e-collaborazione", "fiducia-in-se"],
        "factor_codes": ["AD4", "AD2", "S5"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Tre matematiche afroamericane alla NASA degli anni Sessanta, fra competenza riconosciuta e barriere che non dipendono da loro.",
            "en": "Three African American mathematicians at 1960s NASA, between recognised skill and barriers not of their making.",
        },
        "why_i18n": {
            "it": "Tiene insieme la competenza personale e gli ostacoli esterni, senza ridurre la carriera al solo merito.",
            "en": "It holds personal skill and external obstacles together, without reducing a career to merit alone.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Melfi, T. (2016). Hidden Figures. Fox 2000 Pictures.",
        "sort_order": 80,
    },
    {
        "slug": "savickas-porfeli-caas",
        "kind": "article",
        "title": "Career Adapt-Abilities Scale: construction, reliability and measurement equivalence across 13 countries",
        "creators": ["Mark L. Savickas", "Erik J. Porfeli"],
        "year": 2012,
        "publisher": "Journal of Vocational Behavior",
        "identifiers": {"doi": "10.1016/j.jvb.2012.01.011"},
        "themes": ["lavoro-e-vocazione", "futuro-e-orientamento"],
        "factor_codes": ["AD1", "AD2", "AD3", "AD4"],
        "questionnaire_types": ["QAP"],
        "audience": ["adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "La costruzione della scala di adattabilita' professionale su tredici paesi: le quattro risorse e come sono state misurate.",
            "en": "The construction of the career adaptability scale across thirteen countries: the four resources and how they were measured.",
        },
        "why_i18n": {
            "it": "E' la fonte dello strumento appena compilato: chiude il cerchio per chi vuole sapere da dove vengono le quattro risorse del QAP.",
            "en": "It is the source of the instrument just completed: it closes the loop on where the QAP's four resources come from.",
        },
        "where_to_find": "Tramite il DOI indicato.",
        "source_reference": "Savickas, M. L. & Porfeli, E. J. (2012). JVB 80(3), 661-673.",
        "sort_order": 81,
    },
    # --- ansia e prestazione ---
    {
        "slug": "beilock-choke",
        "kind": "essay",
        "title": "Choke: What the Secrets of the Brain Reveal About Getting It Right When You Have To",
        "creators": ["Sian Beilock"],
        "year": 2010,
        "publisher": "Free Press",
        "themes": ["ansia-e-prestazione", "emozioni"],
        "factor_codes": ["A1", "A7", "S1", "K2"],
        "audience": ["universita", "adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "Perche' si sbaglia proprio quando conta, e perche' pensare troppo a come si fa una cosa la peggiora.",
            "en": "Why we fail exactly when it matters, and why thinking too hard about how we do something makes it worse.",
        },
        "why_i18n": {
            "it": "E' l'autrice dello studio sulla scrittura espressiva gia' in catalogo: qui c'e' il quadro completo.",
            "en": "By the author of the expressive-writing study already in the catalog: here is the full picture.",
        },
        "where_to_find": "In libreria e in biblioteca universitaria.",
        "source_reference": "Beilock, S. (2010). Choke. Free Press.",
        "sort_order": 90,
    },
    {
        "slug": "chazelle-whiplash",
        "kind": "film",
        "title": "Whiplash",
        "creators": ["Damien Chazelle"],
        "year": 2014,
        "publisher": "Bold Films",
        "themes": ["ansia-e-prestazione", "motivazione-e-volizione"],
        "factor_codes": ["A1", "A5"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "is_sensitive": True,
        "content_warning": "Contiene violenza psicologica sistematica da parte di un insegnante e autolesionismo indiretto. Va proposto come oggetto di discussione, mai come modello di impegno.",
        "summary_i18n": {
            "it": "Un batterista e un insegnante che confonde l'esigenza con l'abuso, fino a dove l'ambizione regge.",
            "en": "A drummer and a teacher who confuses demand with abuse, up to the point where ambition breaks.",
        },
        "why_i18n": {
            "it": "Per distinguere la pressione che allena da quella che rompe: utile solo se la differenza viene discussa.",
            "en": "To tell pressure that trains from pressure that breaks: useful only if the difference is discussed.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Chazelle, D. (2014). Whiplash. Bold Films.",
        "sort_order": 91,
    },
    # --- emozioni ---
    {
        "slug": "goleman-intelligenza-emotiva",
        "kind": "essay",
        "title": "Intelligenza emotiva",
        "original_title": "Emotional Intelligence",
        "creators": ["Daniel Goleman"],
        "year": 1995,
        "publisher": "Bantam Books (ed. it. Rizzoli)",
        "identifiers": {"isbn": "9788817106726"},
        "themes": ["emozioni", "fiducia-in-se"],
        "factor_codes": ["A7", "S1", "K2"],
        "audience": ["secondaria", "universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Riconoscere, dare un nome e regolare le emozioni come competenze che si allenano, non come tratti fissi.",
            "en": "Recognising, naming and regulating emotions as skills that can be trained, not fixed traits.",
        },
        "why_i18n": {
            "it": "Il testo che ha reso corrente questa idea; utile a chi tratta le proprie reazioni come qualcosa che semplicemente capita.",
            "en": "The book that made the idea current; useful for a student who treats their reactions as something that simply happens.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Rizzoli.",
        "source_reference": "Goleman, D. (1995). Emotional Intelligence. Bantam Books. ATTENZIONE: da non confondere con l'articolo omonimo di Salovey e Mayer (1990).",
        "sort_order": 100,
    },
    {
        "slug": "docter-inside-out",
        "kind": "film",
        "title": "Inside Out",
        "creators": ["Pete Docter"],
        "year": 2015,
        "publisher": "Pixar Animation Studios",
        "themes": ["emozioni", "identita-e-se"],
        "factor_codes": ["A7", "S1"],
        "audience": ["secondaria"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Le emozioni di una ragazzina di undici anni come personaggi, in un trasloco che manda tutto fuori posto.",
            "en": "The emotions of an eleven-year-old as characters, during a move that throws everything out of place.",
        },
        "why_i18n": {
            "it": "Da' una funzione anche alla tristezza, invece di trattarla come un guasto da riparare.",
            "en": "It gives sadness a function, instead of treating it as a fault to be fixed.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Docter, P. (2015). Inside Out. Pixar.",
        "sort_order": 101,
    },
    # --- relazioni ---
    {
        "slug": "palacio-wonder",
        "kind": "fiction",
        "title": "Wonder",
        "creators": ["R. J. Palacio"],
        "year": 2012,
        "publisher": "Knopf (ed. it. Giunti)",
        "themes": ["relazioni-e-collaborazione", "identita-e-se"],
        "factor_codes": ["C4", "S2"],
        "audience": ["secondaria"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "Il primo anno di scuola di un ragazzino con una malformazione al viso, raccontato a turno da lui e dai compagni.",
            "en": "The first school year of a boy with a facial difference, told in turn by him and by his classmates.",
        },
        "why_i18n": {
            "it": "La classe vista da chi ne sta ai margini e da chi lo esclude: il gruppo come problema e come risorsa.",
            "en": "The classroom seen by the one at its edge and by those excluding him: the group as problem and as resource.",
        },
        "where_to_find": "In libreria e in biblioteca; edizione italiana Giunti.",
        "source_reference": "Palacio, R. J. (2012). Wonder. Knopf.",
        "sort_order": 110,
    },
    # --- transizioni ---
    {
        "slug": "gerwig-lady-bird",
        "kind": "film",
        "title": "Lady Bird",
        "creators": ["Greta Gerwig"],
        "year": 2017,
        "publisher": "A24",
        "themes": ["transizione-scuola-universita", "scelta-e-decisione", "identita-e-se"],
        "factor_codes": ["AD1", "S5"],
        "audience": ["universita", "adulti"],
        "available_languages": ["it", "en", "es", "fr", "de", "sv"],
        "summary_i18n": {
            "it": "L'ultimo anno di scuola fra l'universita' che si vorrebbe, i soldi che non ci sono e una madre che non e' d'accordo.",
            "en": "A final school year between the university one wants, the money that is missing, and a mother who disagrees.",
        },
        "why_i18n": {
            "it": "La scelta dopo la scuola come negoziazione con la famiglia e con i vincoli reali, non come vocazione improvvisa.",
            "en": "The choice after school as a negotiation with family and real constraints, not a sudden calling.",
        },
        "where_to_find": "Disponibile in DVD e sulle principali piattaforme.",
        "source_reference": "Gerwig, G. (2017). Lady Bird. A24. Contiene una prima esperienza sessuale trattata senza enfasi: pubblico da valutare.",
        "sort_order": 120,
    },
    {
        "slug": "yeager-lay-theory-college",
        "kind": "article",
        "title": "Teaching a lay theory before college narrows achievement gaps at scale",
        "creators": ["David S. Yeager", "Gregory M. Walton", "Shannon T. Brady"],
        "year": 2016,
        "publisher": "PNAS",
        "identifiers": {"doi": "10.1073/pnas.1524360113"},
        "themes": ["transizione-scuola-universita", "fiducia-in-se"],
        "factor_codes": ["A6", "S5"],
        "audience": ["adulti"],
        "available_languages": ["en"],
        "summary_i18n": {
            "it": "Un intervento breve prima dell'ingresso all'universita' riduce il divario di risultati fra gruppi di studenti.",
            "en": "A brief intervention before college entry narrows the achievement gap between groups of students.",
        },
        "why_i18n": {
            "it": "Il primo anno come passaggio su cui si puo' agire, non come selezione naturale.",
            "en": "The first year as a transition that can be acted on, not as natural selection.",
        },
        "where_to_find": "Accesso aperto tramite il DOI indicato.",
        "source_reference": "Yeager, D. S. et al. (2016). PNAS 113(24), E3341-E3348.",
        "sort_order": 121,
    },
]


def seed_certified_readings(db, models_module) -> int:
    """Crea le letture mancanti. Idempotente: non tocca gli slug gia' presenti."""
    inserted = 0
    for spec in SEED_CERTIFIED_READINGS:
        exists = (
            db.query(models_module.CertifiedReading)
            .filter(models_module.CertifiedReading.slug == spec["slug"])
            .first()
        )
        if exists:
            continue
        data = dict(spec)
        db.add(models_module.CertifiedReading(
            certified_by="Seme iniziale del catalogo letture",
            # Nasce in bozza: la certificazione la da' l'admin dopo la verifica.
            status="draft",
            is_active=True,
            **data,
        ))
        inserted += 1
    if inserted:
        db.commit()
    return inserted
