"""Catalogo strumenti di default per il seed DB-driven (generato da _gen_catalog_py.js).

Fonte: stato attuale di frontend/src/lib/test-administrations.ts e test-scoring.ts.
NON modificare a mano: dopo il primo seed le modifiche avvengono via editor admin (DB).
Vedi questionari/PROGETTO_VALIDAZIONE_E_SVILUPPO_QSA_QSAR_SV_EN.md.
"""

INSTRUMENT_CATALOG_DEFAULTS = {
    "QSA": {
        "name_en": "Learning Strategies Questionnaire",
        "name_sv": "Frågeformulär om inlärningsstrategier",
        "response_scale_min": 1,
        "response_scale_max": 4,
        "report_scale_type": "stanine",
        "factors": [
            {"code": "C1", "dimension": "cognitive", "orientation": "resource", "label_en": "Elaborative strategies", "label_sv": "Elaborativa strategier"},
            {"code": "C5", "dimension": "cognitive", "orientation": "resource", "label_en": "Graphic organisers", "label_sv": "Grafiska organisatörer"},
            {"code": "C7", "dimension": "cognitive", "orientation": "resource", "label_en": "Self-questioning", "label_sv": "Självfrågor"},
            {"code": "C2", "dimension": "cognitive", "orientation": "resource", "label_en": "Self-regulation", "label_sv": "Självreglering"},
            {"code": "C3", "dimension": "cognitive", "orientation": "difficulty", "label_en": "Disorientation in studying", "label_sv": "Desorientering i studierna"},
            {"code": "C6", "dimension": "cognitive", "orientation": "difficulty", "label_en": "Difficulty concentrating", "label_sv": "Koncentrationssvårigheter"},
            {"code": "C4", "dimension": "cognitive", "orientation": "resource", "label_en": "Collaboration", "label_sv": "Samarbete"},
            {"code": "A1", "dimension": "affective", "orientation": "difficulty", "label_en": "Test anxiety", "label_sv": "Provängslan"},
            {"code": "A7", "dimension": "affective", "orientation": "difficulty", "label_en": "Emotional interference", "label_sv": "Känslomässig påverkan"},
            {"code": "A2", "dimension": "affective", "orientation": "resource", "label_en": "Volition", "label_sv": "Viljestyrning"},
            {"code": "A5", "dimension": "affective", "orientation": "difficulty", "label_en": "Lack of perseverance", "label_sv": "Bristande uthållighet"},
            {"code": "A3", "dimension": "affective", "orientation": "resource", "label_en": "Attribution to controllable factors", "label_sv": "Tillskrivning till kontrollerbara faktorer"},
            {"code": "A4", "dimension": "affective", "orientation": "difficulty", "label_en": "Attribution to uncontrollable factors", "label_sv": "Tillskrivning till okontrollerbara faktorer"},
            {"code": "A6", "dimension": "affective", "orientation": "resource", "label_en": "Perceived competence", "label_sv": "Upplevd kompetens"},
        ],
        "items": [
            {"item_number": 1, "factor_code": "C2", "reverse_scoring": False, "text_en": "After a lesson, I carefully review my notes in order to explore and remember the ideas better.", "text_sv": "Efter en lektion går jag noggrant igenom mina anteckningar för att fördjupa och bättre minnas idéerna."},
            {"item_number": 2, "factor_code": "C2", "reverse_scoring": False, "text_en": "When I read, I reflect on the subject and try to understand clearly what the text explains.", "text_sv": "När jag läser reflekterar jag över ämnet och försöker förstå ordentligt vad texten beskriver."},
            {"item_number": 3, "factor_code": "C3", "reverse_scoring": False, "text_en": "Sometimes I do poorly on an assignment because I cannot understand exactly what I am expected to do.", "text_sv": "Ibland går det dåligt på en uppgift eftersom jag inte kan förstå exakt vad jag ska göra."},
            {"item_number": 4, "factor_code": "A1", "reverse_scoring": False, "text_en": "When I receive a poor mark, I become discouraged.", "text_sv": "När jag får ett dåligt betyg blir jag nedstämd."},
            {"item_number": 5, "factor_code": "A3", "reverse_scoring": False, "text_en": "When I do well at school, I think it is because I studied hard.", "text_sv": "När det går bra för mig i skolan tänker jag att det beror på att jag har studerat mycket."},
            {"item_number": 6, "factor_code": "C7", "reverse_scoring": False, "text_en": "When I prepare for an exam or an oral assessment, I think about the questions the teacher may ask me.", "text_sv": "När jag förbereder mig inför ett prov eller ett muntligt förhör tänker jag på de frågor läraren kan ställa."},
            {"item_number": 7, "factor_code": "C1", "reverse_scoring": False, "text_en": "When I learn new words or ideas, I try to imagine a situation in which they could be applied.", "text_sv": "När jag lär mig nya ord eller idéer försöker jag föreställa mig en situation där de kan användas."},
            {"item_number": 8, "factor_code": "C3", "reverse_scoring": False, "text_en": "When I study, I get lost in details and cannot identify the main points.", "text_sv": "När jag studerar fastnar jag i detaljer och kan inte hitta det viktigaste."},
            {"item_number": 9, "factor_code": "A1", "reverse_scoring": False, "text_en": "I feel very uncomfortable during a written assignment or oral assessment even when I am well prepared.", "text_sv": "Jag känner mig mycket obekväm under en skriftlig uppgift eller ett muntligt förhör även när jag är väl förberedd."},
            {"item_number": 10, "factor_code": "A4", "reverse_scoring": False, "text_en": "When an oral assessment goes well, I think I was lucky that the teacher asked me something I knew.", "text_sv": "När ett muntligt förhör går bra tänker jag att jag hade tur som fick en fråga jag kunde."},
            {"item_number": 11, "factor_code": "C2", "reverse_scoring": False, "text_en": "I check whether I have understood correctly what the teacher said during the lesson.", "text_sv": "Jag kontrollerar om jag har förstått rätt vad läraren sade under lektionen."},
            {"item_number": 12, "factor_code": "C2", "reverse_scoring": False, "text_en": "To pay closer attention, I take notes during lessons.", "text_sv": "För att vara mer uppmärksam antecknar jag under lektionerna."},
            {"item_number": 13, "factor_code": "C4", "reverse_scoring": True, "text_en": "I find that studying with a classmate is a waste of time.", "text_sv": "Jag tycker att det är slöseri med tid att studera med en klasskamrat."},
            {"item_number": 14, "factor_code": "A6", "reverse_scoring": False, "text_en": "When I begin a classroom assignment, I am confident that I can do well.", "text_sv": "När jag börjar med en uppgift i klassrummet är jag övertygad om att jag kan göra bra ifrån mig."},
            {"item_number": 15, "factor_code": "A3", "reverse_scoring": False, "text_en": "When I do not succeed in an assignment or oral assessment, I think the reason is that I did not study seriously.", "text_sv": "När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att orsaken är att jag inte studerade tillräckligt seriöst."},
            {"item_number": 16, "factor_code": "A6", "reverse_scoring": False, "text_en": "I sometimes think that I am capable of completing my study commitments successfully.", "text_sv": "Jag tänker ibland att jag klarar av att genomföra mina studieåtaganden med framgång."},
            {"item_number": 17, "factor_code": "C1", "reverse_scoring": False, "text_en": "I try to find relationships between what I am learning and what I already know.", "text_sv": "Jag försöker hitta samband mellan det jag lär mig och det jag redan vet."},
            {"item_number": 18, "factor_code": "C5", "reverse_scoring": False, "text_en": "Outlines, diagrams or summary tables help me understand better what a text presents.", "text_sv": "Dispositioner, diagram eller sammanfattande tabeller hjälper mig att bättre förstå det som står i texten."},
            {"item_number": 19, "factor_code": "A1", "reverse_scoring": False, "text_en": "During an oral assessment, fear of making a mistake bothers me so much that I perform worse.", "text_sv": "Under ett muntligt förhör stör rädslan för att göra fel mig så mycket att det går sämre."},
            {"item_number": 20, "factor_code": "A6", "reverse_scoring": False, "text_en": "When an oral assessment goes well, I think I am really intelligent.", "text_sv": "När ett muntligt förhör går bra tänker jag att jag verkligen är intelligent."},
            {"item_number": 21, "factor_code": "C2", "reverse_scoring": False, "text_en": "While studying, I ask myself questions or do exercises to check whether I have understood properly.", "text_sv": "När jag studerar ställer jag frågor till mig själv eller gör övningar för att kontrollera att jag har förstått ordentligt."},
            {"item_number": 22, "factor_code": "C1", "reverse_scoring": False, "text_en": "I try to find links between what I am studying and my experiences.", "text_sv": "Jag försöker hitta kopplingar mellan det jag studerar och mina egna erfarenheter."},
            {"item_number": 23, "factor_code": "A1", "reverse_scoring": False, "text_en": "I panic when I know that I must sit an important written exam.", "text_sv": "Jag grips av panik när jag vet att jag ska göra ett viktigt skriftligt prov."},
            {"item_number": 24, "factor_code": "A4", "reverse_scoring": False, "text_en": "When I do not succeed in an assignment or oral assessment, I think I was asked something too difficult.", "text_sv": "När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att jag fick något som var för svårt."},
            {"item_number": 25, "factor_code": "C7", "reverse_scoring": False, "text_en": "When I have finished studying, I imagine the questions the teacher might ask and try to answer them.", "text_sv": "När jag har studerat klart föreställer jag mig vilka frågor läraren kan ställa och försöker besvara dem."},
            {"item_number": 26, "factor_code": "C1", "reverse_scoring": False, "text_en": "I try to see how what I study could apply to my everyday life.", "text_sv": "Jag försöker se hur det jag studerar skulle kunna användas i mitt vardagsliv."},
            {"item_number": 27, "factor_code": "C2", "reverse_scoring": False, "text_en": "When I read a text, I mark the most important points in it.", "text_sv": "När jag läser en text markerar jag det viktigaste i texten."},
            {"item_number": 28, "factor_code": "A1", "reverse_scoring": False, "text_en": "When I have to face an oral assessment or written assignment, I am so nervous that I cannot express myself as well as I could.", "text_sv": "När jag ska göra ett muntligt förhör eller en skriftlig uppgift är jag så nervös att jag inte kan uttrycka mig så bra som jag skulle kunna."},
            {"item_number": 29, "factor_code": "A3", "reverse_scoring": False, "text_en": "When an oral assessment goes well, I think it is because I studied with a great deal of effort.", "text_sv": "När ett muntligt förhör går bra tänker jag att det beror på att jag studerade mycket flitigt."},
            {"item_number": 30, "factor_code": "C4", "reverse_scoring": False, "text_en": "I find discussing or working in a group useful and stimulating.", "text_sv": "Jag tycker att det är användbart och stimulerande att diskutera eller arbeta i grupp."},
            {"item_number": 31, "factor_code": "C1", "reverse_scoring": False, "text_en": "I try to establish links between the different ideas in the text I am studying.", "text_sv": "Jag försöker skapa samband mellan de olika idéerna i texten jag studerar."},
            {"item_number": 32, "factor_code": "C3", "reverse_scoring": False, "text_en": "I find it difficult to summarise what I have heard at school or read in a book.", "text_sv": "Jag har svårt att sammanfatta det jag har hört i skolan eller läst i en bok."},
            {"item_number": 33, "factor_code": "A1", "reverse_scoring": False, "text_en": "During a classroom assignment or an oral assessment, doubts and uncertainty about my ability to do well come into my mind.", "text_sv": "Under en uppgift i klassrummet eller ett muntligt förhör får jag tvivel på min förmåga att lyckas."},
            {"item_number": 34, "factor_code": "C2", "reverse_scoring": False, "text_en": "I organise my study according to the time I have available.", "text_sv": "Jag organiserar mina studier utifrån den tid jag har till förfogande."},
            {"item_number": 35, "factor_code": "C7", "reverse_scoring": False, "text_en": "Before studying a subject, I try to clarify what the teacher expects of me.", "text_sv": "Innan jag studerar ett ämne försöker jag klargöra vad läraren förväntar sig av mig."},
            {"item_number": 36, "factor_code": "C1", "reverse_scoring": False, "text_en": "When I learn a new concept, I try to find an example to which it could apply.", "text_sv": "När jag lär mig ett nytt begrepp försöker jag hitta ett exempel där det kan användas."},
            {"item_number": 37, "factor_code": "C5", "reverse_scoring": False, "text_en": "I create outlines, diagrams or summary tables to summarise what I study.", "text_sv": "Jag gör dispositioner, diagram eller sammanfattande tabeller för att sammanfatta det jag studerar."},
            {"item_number": 38, "factor_code": "A1", "reverse_scoring": False, "text_en": "My heart beats strongly when I have to take an important exam or oral assessment.", "text_sv": "Mitt hjärta slår hårt när jag ska göra ett viktigt prov eller muntligt förhör."},
            {"item_number": 39, "factor_code": "A6", "reverse_scoring": False, "text_en": "When I do well at school, I think it is because I am a truly capable person.", "text_sv": "När det går bra för mig i skolan tänker jag att det beror på att jag är en verkligt kompetent person."},
            {"item_number": 40, "factor_code": "C3", "reverse_scoring": False, "text_en": "During an oral assessment, I sometimes realise that I studied the wrong subject.", "text_sv": "Under ett muntligt förhör händer det att jag inser att jag har studerat fel ämne."},
            {"item_number": 41, "factor_code": "C1", "reverse_scoring": False, "text_en": "When I learn a new concept, I ask myself whether there are cases in which it cannot be applied.", "text_sv": "När jag lär mig ett nytt begrepp frågar jag mig om det finns fall där det inte kan användas."},
            {"item_number": 42, "factor_code": "A2", "reverse_scoring": False, "text_en": "I enjoy having to do work that challenges me.", "text_sv": "Jag tycker om att behöva göra ett arbete som utmanar mig."},
            {"item_number": 43, "factor_code": "C3", "reverse_scoring": False, "text_en": "I memorise rules, technical terms or formulae even without understanding them.", "text_sv": "Jag lär mig regler, facktermer eller formler utantill även utan att förstå dem."},
            {"item_number": 44, "factor_code": "C5", "reverse_scoring": False, "text_en": "I make drawings and sketches that help me understand what I am studying.", "text_sv": "Jag gör teckningar och skisser som hjälper mig att förstå det jag studerar."},
            {"item_number": 45, "factor_code": "A1", "reverse_scoring": False, "text_en": "I become nervous straight away when faced with a question or problem that I do not immediately understand.", "text_sv": "Jag blir genast nervös inför en fråga eller ett problem som jag inte förstår direkt."},
            {"item_number": 46, "factor_code": "C3", "reverse_scoring": False, "text_en": "I cannot stay focused on my work for more than fifteen minutes.", "text_sv": "Jag kan inte hålla koncentrationen på arbetet i mer än en kvart."},
            {"item_number": 47, "factor_code": "A4", "reverse_scoring": False, "text_en": "I sometimes think that failures at school depend fundamentally on people not being capable.", "text_sv": "Jag tänker ibland att misslyckanden i skolan i grunden beror på att personer inte har förmågan."},
            {"item_number": 48, "factor_code": "C1", "reverse_scoring": False, "text_en": "While studying or listening to a lesson, links with other subjects I have already studied come to mind.", "text_sv": "När jag studerar eller lyssnar på en lektion kommer jag att tänka på samband med andra ämnen jag redan har studerat."},
            {"item_number": 49, "factor_code": "A2", "reverse_scoring": False, "text_en": "I go to school having completed all homework and studied all lessons.", "text_sv": "Jag går till skolan efter att ha gjort alla läxor och studerat alla lektioner."},
            {"item_number": 50, "factor_code": "C4", "reverse_scoring": False, "text_en": "When I take part in group work, I feel that I understand things better.", "text_sv": "När jag deltar i grupparbete upplever jag att jag förstår saker bättre."},
            {"item_number": 51, "factor_code": "A4", "reverse_scoring": False, "text_en": "When I do well, I think it is because the task was easy.", "text_sv": "När jag lyckas bra tänker jag att det beror på att arbetet var lätt."},
            {"item_number": 52, "factor_code": "C3", "reverse_scoring": False, "text_en": "I sometimes find that a study topic is more difficult than I expected.", "text_sv": "Ibland tycker jag att ett studieområde är svårare än jag hade väntat mig."},
            {"item_number": 53, "factor_code": "A5", "reverse_scoring": False, "text_en": "When I do not feel able to complete it, I sometimes leave a piece of work unfinished.", "text_sv": "När jag inte känner mig kapabel att slutföra ett arbete händer det att jag lämnar det halvfärdigt."},
            {"item_number": 54, "factor_code": "A2", "reverse_scoring": False, "text_en": "I make a serious effort to achieve a good mark even when I do not like the subject.", "text_sv": "Jag anstränger mig seriöst för att få ett bra betyg även när jag inte tycker om ämnet."},
            {"item_number": 55, "factor_code": "A7", "reverse_scoring": False, "text_en": "If for some reason I cannot prepare my lessons, I feel uneasy.", "text_sv": "Om jag av någon anledning inte kan förbereda lektionerna känner jag mig orolig."},
            {"item_number": 56, "factor_code": "C5", "reverse_scoring": False, "text_en": "I remember better when studying if I can use outlines, diagrams or tables.", "text_sv": "Jag minns bättre när jag studerar om jag kan använda dispositioner, diagram eller tabeller."},
            {"item_number": 57, "factor_code": "C4", "reverse_scoring": True, "text_en": "I prefer studying a lesson on my own rather than with someone else's help.", "text_sv": "Jag föredrar att studera lektionen ensam framför att få hjälp av andra."},
            {"item_number": 58, "factor_code": "A2", "reverse_scoring": False, "text_en": "When faced with a demanding task, I feel encouraged to try harder.", "text_sv": "Inför en krävande uppgift känner jag mig stimulerad att anstränga mig mer."},
            {"item_number": 59, "factor_code": "A4", "reverse_scoring": False, "text_en": "Even if I work very hard, I sometimes think that I cannot become more intelligent anyway.", "text_sv": "Även om jag anstränger mig mycket tänker jag ibland att jag ändå inte kan bli mer intelligent."},
            {"item_number": 60, "factor_code": "C6", "reverse_scoring": True, "text_en": "When I begin studying, I try to estimate how much time I need to learn a subject.", "text_sv": "När jag ska börja studera försöker jag förutse hur mycket tid jag behöver för att lära mig ett ämne."},
            {"item_number": 61, "factor_code": "A5", "reverse_scoring": False, "text_en": "If I find that a subject requires time and effort, I do not even consider it.", "text_sv": "Om jag märker att ett ämne kräver tid och ansträngning överväger jag det inte ens."},
            {"item_number": 62, "factor_code": "A2", "reverse_scoring": False, "text_en": "When for some reason I fall behind in schoolwork, I try to catch up without the teacher making me do so.", "text_sv": "Om jag av någon anledning kommer efter med skolarbetet försöker jag ta igen det utan att läraren tvingar mig."},
            {"item_number": 63, "factor_code": "C2", "reverse_scoring": False, "text_en": "When I do a boring task, I think about its less negative aspects and the satisfaction I will feel when I finish.", "text_sv": "När jag utför en tråkig uppgift tänker jag på dess mindre negativa sidor och på tillfredsställelsen när jag blir klar."},
            {"item_number": 64, "factor_code": "A4", "reverse_scoring": False, "text_en": "I sometimes think that succeeding at school depends on the intellectual ability a person has.", "text_sv": "Jag tänker ibland att förmågan att lyckas i skolan beror på den intelligens en person har."},
            {"item_number": 65, "factor_code": "C2", "reverse_scoring": False, "text_en": "I finish my homework in good time.", "text_sv": "Jag gör klart mina läxor i god tid."},
            {"item_number": 66, "factor_code": "A7", "reverse_scoring": False, "text_en": "If I cannot prepare well for school, I feel uncomfortable.", "text_sv": "Om jag inte kan förbereda mig väl inför skolan känner jag mig obekväm."},
            {"item_number": 67, "factor_code": "A2", "reverse_scoring": False, "text_en": "Even if a task is boring, I continue doing it until I have finished it.", "text_sv": "Även om en uppgift är tråkig fortsätter jag tills jag har gjort klart den."},
            {"item_number": 68, "factor_code": "A3", "reverse_scoring": False, "text_en": "I think that the ability to succeed at school depends on the effort each person puts into careful study.", "text_sv": "Jag tänker att förmågan att lyckas i skolan beror på den ansträngning var och en lägger på noggranna studier."},
            {"item_number": 69, "factor_code": "C6", "reverse_scoring": False, "text_en": "At home I do not study subjects according to a clear plan, but according to the urgency of upcoming assessments.", "text_sv": "Hemma studerar jag inte ämnena efter en tydlig plan utan efter hur nära förestående förhör är."},
            {"item_number": 70, "factor_code": "A2", "reverse_scoring": False, "text_en": "When I have decided to do something, I finish it even if it requires effort.", "text_sv": "När jag har bestämt mig för att göra något slutför jag det även om det kräver ansträngning."},
            {"item_number": 71, "factor_code": "C5", "reverse_scoring": True, "text_en": "I find it of little use to rely on drawings, diagrams or summary tables in the text when reviewing lessons.", "text_sv": "När jag repeterar lektioner tycker jag att det är till liten nytta att använda teckningar, diagram eller sammanfattande tabeller i texten."},
            {"item_number": 72, "factor_code": "A6", "reverse_scoring": False, "text_en": "I feel confident that I can obtain good marks.", "text_sv": "Jag känner mig säker på att jag kan få bra betyg."},
            {"item_number": 73, "factor_code": "A3", "reverse_scoring": False, "text_en": "I think that a person's intelligence can improve over time if they make a serious effort.", "text_sv": "Jag tänker att en persons intelligens kan förbättras med tiden om personen anstränger sig seriöst."},
            {"item_number": 74, "factor_code": "C4", "reverse_scoring": False, "text_en": "I feel that I learn better when I can compare ideas with my classmates.", "text_sv": "Jag upplever att jag lär mig bättre när jag kan jämföra mina tankar med klasskamraternas."},
            {"item_number": 75, "factor_code": "A5", "reverse_scoring": False, "text_en": "As soon as I encounter the first difficulties, I abandon a task I have only just started.", "text_sv": "Så snart jag möter de första svårigheterna överger jag ett arbete som jag just har påbörjat."},
            {"item_number": 76, "factor_code": "A5", "reverse_scoring": False, "text_en": "When something goes badly, I think it depends more on external circumstances than on my ability or lack of effort.", "text_sv": "När något går dåligt tänker jag att det beror mer på yttre omständigheter än på min förmåga eller bristande ansträngning."},
            {"item_number": 77, "factor_code": "A1", "reverse_scoring": False, "text_en": "If I realise that I no longer have enough time to finish my work, I panic.", "text_sv": "Om jag märker att jag inte längre har tid att avsluta arbetet grips jag av panik."},
            {"item_number": 78, "factor_code": "A4", "reverse_scoring": False, "text_en": "I sometimes think that a person's intelligence is something that cannot really change: it is a natural gift.", "text_sv": "Jag tänker ibland att en persons intelligens är något som egentligen inte går att förändra: den är en naturgåva."},
            {"item_number": 79, "factor_code": "C6", "reverse_scoring": False, "text_en": "Problems at home or with friends cause me to neglect my schoolwork.", "text_sv": "Problem hemma eller med vänner gör att jag försummar mitt skolarbete."},
            {"item_number": 80, "factor_code": "C2", "reverse_scoring": False, "text_en": "If I fail, I feel inclined to try again.", "text_sv": "Om jag misslyckas känner jag mig benägen att försöka igen."},
            {"item_number": 81, "factor_code": "C2", "reverse_scoring": False, "text_en": "At the start of studying, I check what I need to do.", "text_sv": "När jag börjar studera kontrollerar jag vad jag behöver göra."},
            {"item_number": 82, "factor_code": "A5", "reverse_scoring": False, "text_en": "When I think about the things I need to learn, I sometimes regard them as too difficult.", "text_sv": "När jag tänker på det jag behöver lära mig händer det att jag ser det som alltför svårt."},
            {"item_number": 83, "factor_code": "A3", "reverse_scoring": False, "text_en": "I think that a person's ability depends on the persistence and effort they put into studying.", "text_sv": "Jag tänker att en persons förmåga beror på den uthållighet och ansträngning personen lägger på studierna."},
            {"item_number": 84, "factor_code": "C6", "reverse_scoring": False, "text_en": "When my teacher explains something, I find myself thinking about other things and do not follow the explanation.", "text_sv": "När min lärare förklarar något börjar jag tänka på annat och följer inte med i förklaringen."},
            {"item_number": 85, "factor_code": "C1", "reverse_scoring": False, "text_en": "When reading, I use my imagination to reconstruct the situations, characters or events being described.", "text_sv": "När jag läser återskapar jag med min fantasi de situationer, personer eller händelser som skildras."},
            {"item_number": 86, "factor_code": "C4", "reverse_scoring": False, "text_en": "I think that in study, as in work, it is important to learn to work together.", "text_sv": "Jag tänker att det i studier, liksom i arbete, är viktigt att lära sig arbeta tillsammans."},
            {"item_number": 87, "factor_code": "A7", "reverse_scoring": False, "text_en": "If I am in a bad mood, I find it difficult to concentrate on studying.", "text_sv": "Om jag är på dåligt humör har jag svårt att koncentrera mig på studierna."},
            {"item_number": 88, "factor_code": "A4", "reverse_scoring": False, "text_en": "When I do well in an oral assessment, I think the teacher was understanding and asked me easy questions.", "text_sv": "När ett muntligt förhör går bra tänker jag att läraren var förstående och ställde lätta frågor."},
            {"item_number": 89, "factor_code": "C6", "reverse_scoring": False, "text_en": "While studying, I distract myself by daydreaming and making all kinds of plans.", "text_sv": "När jag studerar distraheras jag av dagdrömmar, projekt och planer av alla slag."},
            {"item_number": 90, "factor_code": "C5", "reverse_scoring": False, "text_en": "I understand better if the teacher uses sketches and diagrams on the board while explaining.", "text_sv": "Jag förstår bättre om läraren använder skisser och diagram på tavlan när hen förklarar."},
            {"item_number": 91, "factor_code": "A2", "reverse_scoring": False, "text_en": "At home and outside home, I sometimes enjoy talking about the things I do at school.", "text_sv": "Det händer att jag både hemma och utanför hemmet gärna talar om det jag gör i skolan."},
            {"item_number": 92, "factor_code": "A7", "reverse_scoring": False, "text_en": "If I have an emotional problem caused by difficult relationships with others or with my parents, I cannot apply myself to studying.", "text_sv": "Om jag har ett känslomässigt problem på grund av dåliga relationer med andra eller med mina föräldrar kan jag inte ägna mig åt studierna."},
            {"item_number": 93, "factor_code": "A6", "reverse_scoring": False, "text_en": "If I am prepared, I am confident that I will do well in an assignment or oral assessment.", "text_sv": "Om jag är förberedd är jag säker på att jag klarar en uppgift eller ett muntligt förhör bra."},
            {"item_number": 94, "factor_code": "A3", "reverse_scoring": False, "text_en": "I sometimes think that with serious effort a person can also develop their intelligence.", "text_sv": "Jag tänker ibland att man genom seriös ansträngning också kan utveckla sin intelligens."},
            {"item_number": 95, "factor_code": "A2", "reverse_scoring": False, "text_en": "When I encounter a difficulty, I try to overcome it by increasing my effort and concentration.", "text_sv": "När jag stöter på en svårighet försöker jag övervinna den genom att öka min ansträngning och koncentration."},
            {"item_number": 96, "factor_code": "C3", "reverse_scoring": False, "text_en": "I avoid asking questions because I think I would bother the teacher.", "text_sv": "Jag undviker att ställa frågor eftersom jag tror att jag stör läraren."},
            {"item_number": 97, "factor_code": "A1", "reverse_scoring": False, "text_en": "When I am questioned unexpectedly, I freeze and can no longer speak.", "text_sv": "När jag får en oväntad fråga låser jag mig och kan inte längre prata."},
            {"item_number": 98, "factor_code": "C3", "reverse_scoring": False, "text_en": "I find it difficult to tell whether a concept or topic is unclear to me.", "text_sv": "Jag har svårt att avgöra om ett begrepp eller ett ämne är oklart för mig."},
            {"item_number": 99, "factor_code": "C4", "reverse_scoring": True, "text_en": "When I take part in group work, I feel that I am wasting time.", "text_sv": "När jag deltar i grupparbete får jag intrycket att jag slösar bort tid."},
            {"item_number": 100, "factor_code": "C1", "reverse_scoring": False, "text_en": "To remember what I study better, I try to link the different ideas together.", "text_sv": "För att bättre minnas det jag studerar försöker jag koppla samman de olika idéerna."},
        ],
    },
    "QSAr": {
        "name_en": "Learning Strategies Questionnaire - Short Form",
        "name_sv": "Frågeformulär om inlärningsstrategier - kortversion",
        "response_scale_min": 1,
        "response_scale_max": 4,
        "report_scale_type": "stanine",
        "factors": [
            {"code": "C1r", "dimension": "cognitive", "orientation": "resource", "label_en": "Elaborative strategies for understanding and remembering", "label_sv": "Elaborativa strategier för att förstå och minnas"},
            {"code": "C2r", "dimension": "cognitive", "orientation": "resource", "label_en": "Self-regulatory strategies", "label_sv": "Självreglerande strategier"},
            {"code": "C3r", "dimension": "cognitive", "orientation": "resource", "label_en": "Graphic strategies for understanding and remembering", "label_sv": "Grafiska strategier för förståelse och minne"},
            {"code": "C4r", "dimension": "cognitive", "orientation": "difficulty", "label_en": "Difficulty controlling attention", "label_sv": "Svårigheter att kontrollera uppmärksamheten"},
            {"code": "A1r", "dimension": "affective", "orientation": "difficulty", "label_en": "Difficulty regulating anxiety", "label_sv": "Svårigheter att reglera oro"},
            {"code": "A2r", "dimension": "affective", "orientation": "resource", "label_en": "Volition", "label_sv": "Viljestyrning"},
            {"code": "A3r", "dimension": "affective", "orientation": "resource", "label_en": "Controllable causal attributions", "label_sv": "Kontrollerbara orsaksförklaringar"},
            {"code": "A4r", "dimension": "affective", "orientation": "resource", "label_en": "Perceived competence", "label_sv": "Upplevd kompetens"},
        ],
        "items": [
            {"item_number": 1, "factor_code": "C2r", "reverse_scoring": False, "text_en": "I try to understand thoroughly what I read and reflect on it.", "text_sv": "Jag försöker förstå ordentligt det jag läser och reflekterar över det."},
            {"item_number": 2, "factor_code": "A1r", "reverse_scoring": False, "text_en": "When I receive a poor mark, I become discouraged.", "text_sv": "När jag får ett dåligt betyg blir jag nedstämd."},
            {"item_number": 3, "factor_code": "C1r", "reverse_scoring": False, "text_en": "I try to find relationships between what I learn and what I already know.", "text_sv": "Jag försöker hitta samband mellan det jag lär mig och det jag redan vet."},
            {"item_number": 4, "factor_code": "A4r", "reverse_scoring": False, "text_en": "I feel capable of completing my study commitments successfully.", "text_sv": "Jag känner att jag klarar av att genomföra mina studieåtaganden med framgång."},
            {"item_number": 5, "factor_code": "A1r", "reverse_scoring": False, "text_en": "I feel very uncomfortable during a written assignment or oral assessment even when I am well prepared.", "text_sv": "Jag känner mig mycket obekväm under en skriftlig uppgift eller ett muntligt förhör även när jag är väl förberedd."},
            {"item_number": 6, "factor_code": "A3r", "reverse_scoring": True, "text_en": "When an oral assessment goes well, I think I was lucky that the teacher asked me something I knew.", "text_sv": "När ett muntligt förhör går bra tänker jag att jag hade tur som fick en fråga jag kunde."},
            {"item_number": 7, "factor_code": "C2r", "reverse_scoring": False, "text_en": "I take notes during lessons because this helps me pay closer attention.", "text_sv": "Jag antecknar under lektionerna eftersom det hjälper mig att vara mer uppmärksam."},
            {"item_number": 8, "factor_code": "A4r", "reverse_scoring": False, "text_en": "When I begin a classroom assignment, I am confident that I can do well.", "text_sv": "När jag börjar med en uppgift i klassrummet är jag övertygad om att jag kan göra bra ifrån mig."},
            {"item_number": 9, "factor_code": "A1r", "reverse_scoring": False, "text_en": "During an oral assessment, fear of making a mistake bothers me and I perform worse.", "text_sv": "Under ett muntligt förhör stör rädslan för att göra fel mig och det går sämre."},
            {"item_number": 10, "factor_code": "A3r", "reverse_scoring": False, "text_en": "When I do not succeed in an assignment or oral assessment, I think the reason is that I did not study seriously.", "text_sv": "När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att orsaken är att jag inte studerade seriöst."},
            {"item_number": 11, "factor_code": "C2r", "reverse_scoring": False, "text_en": "While studying, I ask myself questions or do exercises to check whether I have understood properly.", "text_sv": "När jag studerar ställer jag frågor till mig själv eller gör övningar för att kontrollera att jag har förstått ordentligt."},
            {"item_number": 12, "factor_code": "C1r", "reverse_scoring": False, "text_en": "I try to link what I am studying with my experiences.", "text_sv": "Jag försöker koppla det jag studerar till mina erfarenheter."},
            {"item_number": 13, "factor_code": "A3r", "reverse_scoring": True, "text_en": "When I do not succeed in an assignment or oral assessment, I think I was asked something too difficult.", "text_sv": "När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att jag fick något som var för svårt."},
            {"item_number": 14, "factor_code": "C1r", "reverse_scoring": False, "text_en": "I try to see how what I study could apply to my everyday life.", "text_sv": "Jag försöker se hur det jag studerar skulle kunna användas i mitt vardagsliv."},
            {"item_number": 15, "factor_code": "C2r", "reverse_scoring": False, "text_en": "When I read a text, I mark the most important points in it.", "text_sv": "När jag läser en text markerar jag det viktigaste i texten."},
            {"item_number": 16, "factor_code": "A1r", "reverse_scoring": False, "text_en": "When I must face an oral assessment or written assignment, I am so nervous that I cannot express myself well.", "text_sv": "När jag ska göra ett muntligt förhör eller en skriftlig uppgift är jag så nervös att jag inte kan uttrycka mig bra."},
            {"item_number": 17, "factor_code": "A3r", "reverse_scoring": False, "text_en": "When an oral assessment goes well, I think I did well to study with so much effort.", "text_sv": "När ett muntligt förhör går bra tänker jag att jag gjorde rätt som studerade så flitigt."},
            {"item_number": 18, "factor_code": "C2r", "reverse_scoring": False, "text_en": "I organise my study according to the time I have available.", "text_sv": "Jag organiserar mina studier utifrån den tid jag har till förfogande."},
            {"item_number": 19, "factor_code": "C1r", "reverse_scoring": False, "text_en": "When I learn something new, I try to find an example to which it can apply.", "text_sv": "När jag lär mig något nytt försöker jag hitta ett exempel där det kan användas."},
            {"item_number": 20, "factor_code": "C3r", "reverse_scoring": False, "text_en": "I create outlines, diagrams, maps or summary tables to summarise what I study.", "text_sv": "Jag gör dispositioner, diagram, kartor eller sammanfattande tabeller för att sammanfatta det jag studerar."},
            {"item_number": 21, "factor_code": "A4r", "reverse_scoring": False, "text_en": "When I do well at school, I think it is because I am a truly capable person.", "text_sv": "När det går bra för mig i skolan tänker jag att det beror på att jag är en verkligt kompetent person."},
            {"item_number": 22, "factor_code": "A1r", "reverse_scoring": False, "text_en": "I become nervous straight away when faced with a question or problem that I do not immediately understand.", "text_sv": "Jag blir genast nervös inför en fråga eller ett problem som jag inte förstår direkt."},
            {"item_number": 23, "factor_code": "C3r", "reverse_scoring": False, "text_en": "I make drawings or sketches that help me understand what I am studying.", "text_sv": "Jag gör teckningar eller skisser som hjälper mig att förstå det jag studerar."},
            {"item_number": 24, "factor_code": "C1r", "reverse_scoring": False, "text_en": "While studying or listening to a lesson, links with other subjects I have already studied come to mind.", "text_sv": "När jag studerar eller lyssnar på en lektion kommer jag att tänka på samband med andra ämnen jag redan har studerat."},
            {"item_number": 25, "factor_code": "A2r", "reverse_scoring": False, "text_en": "I go to school having completed my homework and studied my lessons.", "text_sv": "Jag går till skolan efter att ha gjort läxorna och studerat lektionerna."},
            {"item_number": 26, "factor_code": "A3r", "reverse_scoring": True, "text_en": "When I do well, I think it is because the task was easy.", "text_sv": "När jag lyckas bra tänker jag att det beror på att uppgiften var lätt."},
            {"item_number": 27, "factor_code": "A2r", "reverse_scoring": False, "text_en": "Even if I do not like the subject, I still make an effort to succeed.", "text_sv": "Även om jag inte tycker om ämnet anstränger jag mig ändå för att lyckas."},
            {"item_number": 28, "factor_code": "C3r", "reverse_scoring": False, "text_en": "When I study, I make outlines to understand and remember better.", "text_sv": "När jag studerar gör jag dispositioner för att förstå och minnas bättre."},
            {"item_number": 29, "factor_code": "A2r", "reverse_scoring": False, "text_en": "When faced with a demanding task, I feel encouraged to try harder.", "text_sv": "Inför en krävande uppgift känner jag mig stimulerad att anstränga mig mer."},
            {"item_number": 30, "factor_code": "A3r", "reverse_scoring": True, "text_en": "I think that not succeeding at school depends on the intelligence a person has.", "text_sv": "Jag tänker att misslyckanden i skolan beror på den intelligens en person har."},
            {"item_number": 31, "factor_code": "C2r", "reverse_scoring": False, "text_en": "I do my homework in good time.", "text_sv": "Jag gör mina läxor i god tid."},
            {"item_number": 32, "factor_code": "A2r", "reverse_scoring": False, "text_en": "Even if a task seems boring, I still try to finish it.", "text_sv": "Även om en uppgift verkar tråkig försöker jag ändå avsluta den."},
            {"item_number": 33, "factor_code": "A3r", "reverse_scoring": False, "text_en": "I think that succeeding at school depends on the persistence and effort put into studying.", "text_sv": "Jag tänker att framgång i skolan beror på uthålligheten och ansträngningen i studierna."},
            {"item_number": 34, "factor_code": "C4r", "reverse_scoring": False, "text_en": "I study only when I am going to be assessed, rather than systematically day by day.", "text_sv": "Jag studerar bara när jag ska förhöras och inte systematiskt dag för dag."},
            {"item_number": 35, "factor_code": "A2r", "reverse_scoring": False, "text_en": "When I decide to do something, I finish it even if it requires effort.", "text_sv": "När jag bestämmer mig för att göra något slutför jag det även om det kräver ansträngning."},
            {"item_number": 36, "factor_code": "C3r", "reverse_scoring": False, "text_en": "When reviewing lessons, I find it useful to use drawings, diagrams or summary tables in the text.", "text_sv": "När jag repeterar lektioner tycker jag att det är användbart att använda teckningar, diagram eller sammanfattande tabeller i texten."},
            {"item_number": 37, "factor_code": "A4r", "reverse_scoring": False, "text_en": "I feel confident that I can obtain good marks.", "text_sv": "Jag känner mig säker på att jag kan få bra betyg."},
            {"item_number": 38, "factor_code": "A1r", "reverse_scoring": False, "text_en": "If I realise that I no longer have enough time to finish a task, I panic.", "text_sv": "Om jag märker att jag inte längre har tid att avsluta ett arbete grips jag av panik."},
            {"item_number": 39, "factor_code": "A3r", "reverse_scoring": True, "text_en": "I sometimes think that a person's intelligence is something that cannot really change: it is a natural gift.", "text_sv": "Jag tänker ibland att en persons intelligens är något som egentligen inte går att förändra: den är en naturgåva."},
            {"item_number": 40, "factor_code": "C2r", "reverse_scoring": False, "text_en": "Before studying, I check what I need to do.", "text_sv": "Innan jag studerar kontrollerar jag vad jag behöver göra."},
            {"item_number": 41, "factor_code": "C4r", "reverse_scoring": False, "text_en": "While the teacher is explaining, I find myself becoming distracted.", "text_sv": "När läraren förklarar händer det att jag blir distraherad."},
            {"item_number": 42, "factor_code": "C3r", "reverse_scoring": False, "text_en": "I understand better if the teacher uses sketches and diagrams on the board while explaining.", "text_sv": "Jag förstår bättre om läraren använder skisser och diagram på tavlan när hen förklarar."},
            {"item_number": 43, "factor_code": "C1r", "reverse_scoring": False, "text_en": "To remember what I study better, I try to link the different ideas together.", "text_sv": "För att bättre minnas det jag studerar försöker jag koppla samman de olika idéerna."},
            {"item_number": 44, "factor_code": "C4r", "reverse_scoring": False, "text_en": "While studying, I sometimes find myself thinking about other things.", "text_sv": "När jag studerar händer det att jag tänker på annat."},
            {"item_number": 45, "factor_code": "A4r", "reverse_scoring": False, "text_en": "If I have prepared for an assignment or oral assessment, I am confident that I will do well.", "text_sv": "Om jag har förberett mig inför en uppgift eller ett muntligt förhör är jag säker på att jag kommer att lyckas."},
            {"item_number": 46, "factor_code": "A2r", "reverse_scoring": False, "text_en": "When I encounter a difficulty, I make a greater effort to overcome it.", "text_sv": "När jag möter en svårighet anstränger jag mig mer för att övervinna den."},
        ],
    },
    "ZTPI": {
        "name_en": "Zimbardo Time Perspective Inventory",
        "name_sv": "Zimbardos tidsperspektivinventarium",
        "response_scale_min": 1,
        "response_scale_max": 4,
        "report_scale_type": "stanine",
        "factors": [
            {"code": "T1", "dimension": "pn", "orientation": "neutral", "label_en": "Past Negative", "label_sv": "Negativt förflutet"},
            {"code": "T2", "dimension": "pp", "orientation": "neutral", "label_en": "Past Positive", "label_sv": "Positivt förflutet"},
            {"code": "T3", "dimension": "ph", "orientation": "neutral", "label_en": "Present Hedonistic", "label_sv": "Hedonistisk nutid"},
            {"code": "T4", "dimension": "pf", "orientation": "neutral", "label_en": "Present Fatalistic", "label_sv": "Fatalistisk nutid"},
            {"code": "T5", "dimension": "f", "orientation": "neutral", "label_en": "Future", "label_sv": "Framtid"},
        ],
        "items": [
            {"item_number": 1, "factor_code": "T3", "reverse_scoring": False, "text_en": "I believe that getting together with one's friends to party is one of life's important pleasures.", "text_sv": "Jag tror att att träffa vänner och festa är en av livets viktiga glädjeämnen."},
            {"item_number": 2, "factor_code": "T2", "reverse_scoring": False, "text_en": "Familiar childhood sights, sounds and smells often bring back a flood of wonderful memories.", "text_sv": "Bekanta barndomssyner, ljud och dofter väcker ofta en rad underbara minnen till liv."},
            {"item_number": 3, "factor_code": "T4", "reverse_scoring": False, "text_en": "Fate determines much of my life.", "text_sv": "Ödet bestämmer mycket av mitt liv."},
            {"item_number": 4, "factor_code": "T1", "reverse_scoring": False, "text_en": "I often think of what I should have done differently in my life.", "text_sv": "Jag tänker ofta på vad jag borde ha gjort annorlunda i mitt liv."},
            {"item_number": 5, "factor_code": "T4", "reverse_scoring": False, "text_en": "My decisions are mostly influenced by the people and things around me.", "text_sv": "Mina beslut påverkas mest av människor och saker omkring mig."},
            {"item_number": 6, "factor_code": "T5", "reverse_scoring": False, "text_en": "I believe that a person's day should be planned ahead each morning.", "text_sv": "Jag tror att en persons dag bör planeras i förväg varje morgon."},
            {"item_number": 7, "factor_code": "T2", "reverse_scoring": False, "text_en": "It gives me pleasure to think about my past.", "text_sv": "Det gläder mig att tänka på mitt förflutna."},
            {"item_number": 8, "factor_code": "T3", "reverse_scoring": False, "text_en": "I act on the spur of the moment.", "text_sv": "Jag handlar impulsivt."},
            {"item_number": 9, "factor_code": "T4", "reverse_scoring": False, "text_en": "If things don't get done on time, I don't worry about it.", "text_sv": "Om saker inte blir gjorda i tid oroar jag mig inte över det."},
            {"item_number": 10, "factor_code": "T5", "reverse_scoring": False, "text_en": "When I want to achieve something, I set goals and consider specific means for reaching those goals.", "text_sv": "När jag vill uppnå något sätter jag upp mål och överväger specifika sätt att nå dem."},
            {"item_number": 11, "factor_code": "T2", "reverse_scoring": False, "text_en": "On balance, there is much more good to recall than bad in my past.", "text_sv": "Sammantaget finns det mycket mer gott än ont att minnas från mitt förflutna."},
            {"item_number": 12, "factor_code": "T3", "reverse_scoring": False, "text_en": "When listening to my favourite music, I often lose all track of time.", "text_sv": "När jag lyssnar på min favoritmusik tappar jag ofta helt bort tiden."},
            {"item_number": 13, "factor_code": "T5", "reverse_scoring": False, "text_en": "Meeting tomorrow's deadlines and doing other necessary work comes before tonight's fun.", "text_sv": "Morgondagens deadlines och annat nödvändigt arbete kommer före kvällens nöjen."},
            {"item_number": 14, "factor_code": "T4", "reverse_scoring": False, "text_en": "Since whatever will be will be, it doesn't really matter what I do.", "text_sv": "Eftersom det som sker ändå sker spelar det ingen roll vad jag gör."},
            {"item_number": 15, "factor_code": "T2", "reverse_scoring": False, "text_en": "I enjoy stories about the past and how things were in the old days.", "text_sv": "Jag tycker om berättelser om det förflutna och hur saker var förr i tiden."},
            {"item_number": 16, "factor_code": "T1", "reverse_scoring": False, "text_en": "Painful past experiences keep being replayed in my mind.", "text_sv": "Smärtsamma tidigare erfarenheter spelas upp om och om igen i mitt huvud."},
            {"item_number": 17, "factor_code": "T3", "reverse_scoring": False, "text_en": "I try to live my life as fully as possible, one day at a time.", "text_sv": "Jag försöker leva mitt liv så fullt ut som möjligt, en dag i taget."},
            {"item_number": 18, "factor_code": "T5", "reverse_scoring": False, "text_en": "It upsets me to be late for appointments.", "text_sv": "Det gör mig upprörd att komma för sent till möten."},
            {"item_number": 19, "factor_code": "T3", "reverse_scoring": False, "text_en": "Ideally, I would live each day as if it were my last.", "text_sv": "Helst skulle jag leva varje dag som om den vore min sista."},
            {"item_number": 20, "factor_code": "T2", "reverse_scoring": False, "text_en": "Happy memories of good times spring readily to mind.", "text_sv": "Glada minnen från goda stunder dyker lätt upp."},
            {"item_number": 21, "factor_code": "T5", "reverse_scoring": False, "text_en": "I meet my obligations to friends and authorities on time.", "text_sv": "Jag uppfyller mina åtaganden gentemot vänner och auktoriteter i tid."},
            {"item_number": 22, "factor_code": "T1", "reverse_scoring": False, "text_en": "I've taken my share of abuse and rejection in the past.", "text_sv": "Jag har fått min del av övergrepp och avvisande i det förflutna."},
            {"item_number": 23, "factor_code": "T3", "reverse_scoring": False, "text_en": "I make decisions on the spur of the moment.", "text_sv": "Jag fattar beslut impulsivt."},
            {"item_number": 24, "factor_code": "T4", "reverse_scoring": False, "text_en": "I take each day as it is rather than try to plan it out.", "text_sv": "Jag tar varje dag som den kommer istället för att planera den."},
            {"item_number": 25, "factor_code": "T1", "reverse_scoring": False, "text_en": "The past has too many unpleasant memories that I prefer not to recall.", "text_sv": "Det förflutna har alltför många obehagliga minnen som jag helst inte vill tänka på."},
            {"item_number": 26, "factor_code": "T3", "reverse_scoring": False, "text_en": "It is important to put excitement in my life.", "text_sv": "Det är viktigt att skapa spänning i mitt liv."},
            {"item_number": 27, "factor_code": "T1", "reverse_scoring": False, "text_en": "I've made mistakes in the past that I wish I could undo.", "text_sv": "Jag har gjort misstag i det förflutna som jag önskar att jag kunde göra ogjorda."},
            {"item_number": 28, "factor_code": "T3", "reverse_scoring": False, "text_en": "I feel that it's more important to enjoy what you're doing than to get the job done on time.", "text_sv": "Jag tycker att det är viktigare att njuta av det man gör än att bli klar i tid."},
            {"item_number": 29, "factor_code": "T2", "reverse_scoring": False, "text_en": "I get nostalgic about my childhood.", "text_sv": "Jag blir nostalgisk över min barndom."},
            {"item_number": 30, "factor_code": "T5", "reverse_scoring": False, "text_en": "Before making a decision, I weigh the costs against the benefits.", "text_sv": "Innan jag fattar ett beslut väger jag kostnader mot fördelar."},
            {"item_number": 31, "factor_code": "T3", "reverse_scoring": False, "text_en": "Taking risks keeps my life from becoming boring.", "text_sv": "Att ta risker förhindrar att mitt liv blir tråkigt."},
            {"item_number": 32, "factor_code": "T3", "reverse_scoring": False, "text_en": "It is more important for me to enjoy life's journey than to focus only on the destination.", "text_sv": "Det är viktigare för mig att njuta av livets resa än att bara fokusera på målet."},
            {"item_number": 33, "factor_code": "T1", "reverse_scoring": False, "text_en": "Things rarely work out as I expected.", "text_sv": "Saker och ting blir sällan som jag förväntat mig."},
            {"item_number": 34, "factor_code": "T1", "reverse_scoring": False, "text_en": "It's hard for me to forget unpleasant images of my youth.", "text_sv": "Det är svårt för mig att glömma obehagliga bilder från min ungdom."},
            {"item_number": 35, "factor_code": "T3", "reverse_scoring": False, "text_en": "It takes joy out of the process of my activities if I have to think about goals and outcomes.", "text_sv": "Om jag måste tänka på mål och resultat försvinner glädjen i det jag gör."},
            {"item_number": 36, "factor_code": "T1", "reverse_scoring": False, "text_en": "Even when I am enjoying the present, I am drawn back to comparisons with similar past experiences.", "text_sv": "Även när jag njuter av nuet dras jag tillbaka till jämförelser med liknande tidigare erfarenheter."},
            {"item_number": 37, "factor_code": "T4", "reverse_scoring": False, "text_en": "You can't really plan for the future because things change so much.", "text_sv": "Man kan egentligen inte planera för framtiden eftersom saker förändras så mycket."},
            {"item_number": 38, "factor_code": "T4", "reverse_scoring": False, "text_en": "My life path is controlled by forces I cannot influence.", "text_sv": "Min livsväg styrs av krafter som jag inte kan påverka."},
            {"item_number": 39, "factor_code": "T4", "reverse_scoring": False, "text_en": "I don't like to think about the past.", "text_sv": "Jag tycker inte om att tänka på det förflutna."},
            {"item_number": 40, "factor_code": "T1", "reverse_scoring": False, "text_en": "I think about the bad things that have happened to me in the past.", "text_sv": "Jag tänker på dåliga saker som hänt mig tidigare."},
            {"item_number": 41, "factor_code": "T2", "reverse_scoring": False, "text_en": "I believe that life today is too complicated; I would rather enjoy the simpler life of the past.", "text_sv": "Jag tycker att livet idag är för komplicerat; jag skulle hellre njuta av det enklare livet förr."},
            {"item_number": 42, "factor_code": "T3", "reverse_scoring": False, "text_en": "I prefer friends who are spontaneous rather than predictable.", "text_sv": "Jag föredrar vänner som är spontana snarare än förutsägbara."},
            {"item_number": 43, "factor_code": "T5", "reverse_scoring": False, "text_en": "I keep working at a difficult uninteresting task if it will help me get ahead.", "text_sv": "Jag fortsätter arbeta med en svår ointressant uppgift om det hjälper mig att komma framåt."},
            {"item_number": 44, "factor_code": "T3", "reverse_scoring": False, "text_en": "Spending what I earn on pleasures today is better than saving for tomorrow's security.", "text_sv": "Det är bättre att spendera det jag tjänar på nöjen idag än att spara till morgondagens trygghet."},
            {"item_number": 45, "factor_code": "T1", "reverse_scoring": False, "text_en": "Often I wish I could go back in time and change what I did.", "text_sv": "Ofta önskar jag att jag kunde gå tillbaka i tiden och förändra det jag gjorde."},
            {"item_number": 46, "factor_code": "T5", "reverse_scoring": False, "text_en": "I like to get my work done before playing.", "text_sv": "Jag gör helst klart mitt arbete innan jag leker."},
            {"item_number": 47, "factor_code": "T5", "reverse_scoring": False, "text_en": "I get irritated at people who keep me from being on time.", "text_sv": "Jag blir irriterad på människor som hindrar mig från att vara i tid."},
            {"item_number": 48, "factor_code": "T5", "reverse_scoring": False, "text_en": "It is more important to save for the future than to buy what one wants today.", "text_sv": "Det är viktigare att spara för framtiden än att köpa vad man vill ha idag."},
            {"item_number": 49, "factor_code": "T5", "reverse_scoring": False, "text_en": "I complete projects on time by making steady progress.", "text_sv": "Jag slutför projekt i tid genom att göra stadiga framsteg."},
            {"item_number": 50, "factor_code": "T2", "reverse_scoring": False, "text_en": "I like to listen to elderly people talk about the old days.", "text_sv": "Jag tycker om att lyssna på äldre människor som berättar om förr i tiden."},
            {"item_number": 51, "factor_code": "T3", "reverse_scoring": False, "text_en": "I take risks to put excitement in my life.", "text_sv": "Jag tar risker för att skapa spänning i mitt liv."},
            {"item_number": 52, "factor_code": "T5", "reverse_scoring": False, "text_en": "I make lists of things to do.", "text_sv": "Jag gör listor över saker som måste göras."},
            {"item_number": 53, "factor_code": "T5", "reverse_scoring": False, "text_en": "I am able to resist temptations when there is work to be done.", "text_sv": "Jag kan motstå frestelser när det finns arbete som måste göras."},
            {"item_number": 54, "factor_code": "T3", "reverse_scoring": False, "text_en": "I find myself getting swept up in the excitement of the moment.", "text_sv": "Jag rycks ofta med av stundens spänning."},
            {"item_number": 55, "factor_code": "T3", "reverse_scoring": False, "text_en": "I am impulsive.", "text_sv": "Jag är impulsiv."},
            {"item_number": 56, "factor_code": "T3", "reverse_scoring": False, "text_en": "I try to make my life spontaneous rather than planned.", "text_sv": "Jag försöker göra mitt liv spontant snarare än planerat."},
        ],
    },
    "QPCS": {
        "name_en": "Perceived Strategic Competences Questionnaire",
        "name_sv": "Frågeformulär om upplevda strategiska kompetenser",
        "response_scale_min": 1,
        "response_scale_max": 4,
        "report_scale_type": "stanine",
        "factors": [
            {"code": "S1", "dimension": "managing_emotions", "orientation": "resource", "label_en": "Managing emotions", "label_sv": "Hantera känslor"},
            {"code": "S2", "dimension": "communicative_competence", "orientation": "resource", "label_en": "Communicative competence", "label_sv": "Kommunikativ kompetens"},
            {"code": "S3", "dimension": "will_perseverance", "orientation": "resource", "label_en": "Will & perseverance", "label_sv": "Vilja & uthållighet"},
            {"code": "S4", "dimension": "strategies_collaboration", "orientation": "resource", "label_en": "Strategies & collaboration", "label_sv": "Strategier & samarbete"},
            {"code": "S5", "dimension": "confidence_life_project", "orientation": "resource", "label_en": "Confidence & life project", "label_sv": "Tilltro & livsprojekt"},
        ],
        "items": [
            {"item_number": 1, "factor_code": "S1", "reverse_scoring": False, "text_en": "I feel calm and relaxed when I sit down to study.", "text_sv": "Jag känner mig lugn och avslappnad när jag studerar."},
            {"item_number": 2, "factor_code": "S1", "reverse_scoring": False, "text_en": "I know how to handle my anxiety before an exam.", "text_sv": "Jag vet hur jag hanterar min oro inför ett prov."},
            {"item_number": 3, "factor_code": "S1", "reverse_scoring": False, "text_en": "When I feel tense about schoolwork, I have ways to relax.", "text_sv": "När jag känner mig spänd över skolarbete har jag sätt att koppla av."},
            {"item_number": 4, "factor_code": "S1", "reverse_scoring": False, "text_en": "Worrying about tests rarely interferes with my performance.", "text_sv": "Oro inför prov påverkar sällan mina prestationer."},
            {"item_number": 5, "factor_code": "S1", "reverse_scoring": False, "text_en": "I can stay calm even when the workload is heavy.", "text_sv": "Jag kan hålla mig lugn även när arbetsbelastningen är tung."},
            {"item_number": 6, "factor_code": "S2", "reverse_scoring": False, "text_en": "I express my ideas clearly when working in a group.", "text_sv": "Jag uttrycker mina idéer tydligt när jag arbetar i grupp."},
            {"item_number": 7, "factor_code": "S2", "reverse_scoring": False, "text_en": "I find it easy to ask for help when I need it.", "text_sv": "Jag har lätt för att be om hjälp när jag behöver det."},
            {"item_number": 8, "factor_code": "S2", "reverse_scoring": False, "text_en": "I feel comfortable explaining things to my classmates.", "text_sv": "Jag känner mig bekväm med att förklara saker för mina klasskamrater."},
            {"item_number": 9, "factor_code": "S2", "reverse_scoring": False, "text_en": "I listen carefully to others' opinions during discussions.", "text_sv": "Jag lyssnar noga på andras åsikter under diskussioner."},
            {"item_number": 10, "factor_code": "S2", "reverse_scoring": False, "text_en": "I can adapt my communication style to different people.", "text_sv": "Jag kan anpassa mitt sätt att kommunicera till olika personer."},
            {"item_number": 11, "factor_code": "S3", "reverse_scoring": False, "text_en": "When I decide to do something, I see it through to the end.", "text_sv": "När jag bestämmer mig för att göra något fullföljer jag det."},
            {"item_number": 12, "factor_code": "S3", "reverse_scoring": False, "text_en": "I keep working on a task even when it becomes difficult.", "text_sv": "Jag fortsätter arbeta med en uppgift även när den blir svår."},
            {"item_number": 13, "factor_code": "S3", "reverse_scoring": False, "text_en": "I do not give up easily on challenging assignments.", "text_sv": "Jag ger inte lätt upp vid utmanande uppgifter."},
            {"item_number": 14, "factor_code": "S3", "reverse_scoring": False, "text_en": "I manage my time well and meet deadlines.", "text_sv": "Jag planerar min tid väl och håller deadline."},
            {"item_number": 15, "factor_code": "S3", "reverse_scoring": False, "text_en": "I push myself to finish my work even when I feel tired.", "text_sv": "Jag pressar mig själv att slutföra mitt arbete även när jag är trött."},
            {"item_number": 16, "factor_code": "S4", "reverse_scoring": False, "text_en": "I organise my study material in a way that helps me learn.", "text_sv": "Jag organiserar mitt studiematerial på ett sätt som hjälper mig att lära."},
            {"item_number": 17, "factor_code": "S4", "reverse_scoring": False, "text_en": "I use different learning strategies depending on the subject.", "text_sv": "Jag använder olika inlärningsstrategier beroende på ämne."},
            {"item_number": 18, "factor_code": "S4", "reverse_scoring": False, "text_en": "I review my notes regularly to reinforce my understanding.", "text_sv": "Jag går igenom mina anteckningar regelbundet för att befästa min förståelse."},
            {"item_number": 19, "factor_code": "S4", "reverse_scoring": False, "text_en": "I find it helpful to study together with classmates.", "text_sv": "Jag tycker att det är hjälpsamt att studera tillsammans med klasskamrater."},
            {"item_number": 20, "factor_code": "S4", "reverse_scoring": False, "text_en": "I contribute actively when working in a team.", "text_sv": "Jag bidrar aktivt när jag arbetar i team."},
            {"item_number": 21, "factor_code": "S5", "reverse_scoring": False, "text_en": "I believe I have the ability to succeed in my studies.", "text_sv": "Jag tror att jag har förmågan att lyckas i mina studier."},
            {"item_number": 22, "factor_code": "S5", "reverse_scoring": False, "text_en": "I feel confident about making decisions for my future.", "text_sv": "Jag känner mig trygg med att fatta beslut om min framtid."},
            {"item_number": 23, "factor_code": "S5", "reverse_scoring": False, "text_en": "I can identify my strengths and areas for improvement.", "text_sv": "Jag kan identifiera mina styrkor och områden att förbättra."},
            {"item_number": 24, "factor_code": "S5", "reverse_scoring": False, "text_en": "I have a clear sense of direction for my career path.", "text_sv": "Jag har en tydlig riktning för min karriärväg."},
            {"item_number": 25, "factor_code": "S5", "reverse_scoring": False, "text_en": "I trust that my efforts will lead to good outcomes.", "text_sv": "Jag litar på att mina ansträngningar leder till goda resultat."},
        ],
    },
    "QPCC": {
        "name_en": "Perceived Competences and Beliefs Questionnaire",
        "name_sv": "Frågeformulär om upplevda kompetenser och föreställningar",
        "response_scale_min": 1,
        "response_scale_max": 4,
        "report_scale_type": "stanine",
        "factors": [
            {"code": "K1", "dimension": "public_speaking", "orientation": "resource", "label_en": "Public speaking", "label_sv": "Tala inför andra"},
            {"code": "K2", "dimension": "anxiety_responsibility", "orientation": "resource", "label_en": "Managing anxiety & responsibility", "label_sv": "Hantera ångest & ansvar"},
            {"code": "K3", "dimension": "volition_selfregulation", "orientation": "resource", "label_en": "Volition & self-regulation", "label_sv": "Vilja & självreglering"},
            {"code": "K4", "dimension": "elaboration_strategies", "orientation": "resource", "label_en": "Elaboration strategies", "label_sv": "Bearbetningsstrategier"},
            {"code": "K5", "dimension": "beliefs_about_self", "orientation": "resource", "label_en": "Beliefs about oneself", "label_sv": "Föreställningar om sig själv"},
        ],
        "items": [
            {"item_number": 1, "factor_code": "K1", "reverse_scoring": False, "text_en": "I feel confident when I have to speak in front of a group.", "text_sv": "Jag känner mig trygg när jag ska tala inför en grupp."},
            {"item_number": 2, "factor_code": "K1", "reverse_scoring": False, "text_en": "I can present my ideas clearly to an audience.", "text_sv": "Jag kan presentera mina idéer tydligt inför en publik."},
            {"item_number": 3, "factor_code": "K1", "reverse_scoring": False, "text_en": "I enjoy participating in class presentations.", "text_sv": "Jag tycker om att delta i klasspresentationer."},
            {"item_number": 4, "factor_code": "K1", "reverse_scoring": False, "text_en": "I am able to persuade others with my arguments.", "text_sv": "Jag kan övertyga andra med mina argument."},
            {"item_number": 5, "factor_code": "K1", "reverse_scoring": False, "text_en": "I feel comfortable expressing my opinions in a meeting.", "text_sv": "Jag känner mig bekväm med att uttrycka mina åsikter i ett möte."},
            {"item_number": 6, "factor_code": "K2", "reverse_scoring": False, "text_en": "I can manage pressure when making important decisions.", "text_sv": "Jag hanterar press när jag fattar viktiga beslut."},
            {"item_number": 7, "factor_code": "K2", "reverse_scoring": False, "text_en": "I take responsibility for the consequences of my choices.", "text_sv": "Jag tar ansvar för konsekvenserna av mina val."},
            {"item_number": 8, "factor_code": "K2", "reverse_scoring": False, "text_en": "I stay calm when faced with unexpected challenges.", "text_sv": "Jag förblir lugn inför oväntade utmaningar."},
            {"item_number": 9, "factor_code": "K2", "reverse_scoring": False, "text_en": "I am able to balance multiple responsibilities at the same time.", "text_sv": "Jag kan balansera flera ansvarsområden samtidigt."},
            {"item_number": 10, "factor_code": "K2", "reverse_scoring": False, "text_en": "I handle stressful situations without losing focus.", "text_sv": "Jag hanterar stressiga situationer utan att tappa fokus."},
            {"item_number": 11, "factor_code": "K3", "reverse_scoring": False, "text_en": "I set clear goals for my studies and work.", "text_sv": "Jag sätter tydliga mål för mina studier och mitt arbete."},
            {"item_number": 12, "factor_code": "K3", "reverse_scoring": False, "text_en": "I organise my tasks in order of priority.", "text_sv": "Jag organiserar mina uppgifter i prioritetsordning."},
            {"item_number": 13, "factor_code": "K3", "reverse_scoring": False, "text_en": "I monitor my own progress towards my goals.", "text_sv": "Jag följer mina egna framsteg mot mina mål."},
            {"item_number": 14, "factor_code": "K3", "reverse_scoring": False, "text_en": "I adjust my plans when circumstances change.", "text_sv": "Jag justerar mina planer när omständigheterna förändras."},
            {"item_number": 15, "factor_code": "K3", "reverse_scoring": False, "text_en": "I reflect on my actions to learn from experience.", "text_sv": "Jag reflekterar över mina handlingar för att lära av erfarenhet."},
            {"item_number": 16, "factor_code": "K4", "reverse_scoring": False, "text_en": "I connect new information with what I already know.", "text_sv": "Jag kopplar ny information till det jag redan vet."},
            {"item_number": 17, "factor_code": "K4", "reverse_scoring": False, "text_en": "I organise ideas in my mind to understand them better.", "text_sv": "Jag organiserar idéer i mitt huvud för att förstå dem bättre."},
            {"item_number": 18, "factor_code": "K4", "reverse_scoring": False, "text_en": "I apply what I learn in one subject to other areas.", "text_sv": "Jag tillämpar det jag lärt mig i ett ämne på andra områden."},
            {"item_number": 19, "factor_code": "K4", "reverse_scoring": False, "text_en": "I use examples and analogies to deepen my understanding.", "text_sv": "Jag använder exempel och analogier för att fördjupa min förståelse."},
            {"item_number": 20, "factor_code": "K4", "reverse_scoring": False, "text_en": "I think critically about the information I receive.", "text_sv": "Jag tänker kritiskt på den information jag får."},
            {"item_number": 21, "factor_code": "K5", "reverse_scoring": False, "text_en": "I believe in my ability to learn new things.", "text_sv": "Jag tror på min förmåga att lära mig nya saker."},
            {"item_number": 22, "factor_code": "K5", "reverse_scoring": False, "text_en": "I trust that my efforts will pay off in the long run.", "text_sv": "Jag litar på att mina ansträngningar lönar sig i längden."},
            {"item_number": 23, "factor_code": "K5", "reverse_scoring": False, "text_en": "I attribute my successes to my own skills and hard work.", "text_sv": "Jag tillskriver mina framgångar mina egna färdigheter och hårda arbete."},
            {"item_number": 24, "factor_code": "K5", "reverse_scoring": False, "text_en": "I am optimistic about my ability to overcome difficulties.", "text_sv": "Jag är optimistisk om min förmåga att övervinna svårigheter."},
            {"item_number": 25, "factor_code": "K5", "reverse_scoring": False, "text_en": "I believe that I can improve through practice and dedication.", "text_sv": "Jag tror att jag kan förbättras genom övning och hängivenhet."},
        ],
    },
    "QAP": {
        "name_en": "Career Adapt-Abilities Scale",
        "name_sv": "Skala för anpassningsbarhet i karriären",
        "response_scale_min": 1,
        "response_scale_max": 4,
        "report_scale_type": "stanine",
        "factors": [
            {"code": "AD1", "dimension": "concern", "orientation": "resource", "label_en": "Concern", "label_sv": "Omsorg om framtiden"},
            {"code": "AD2", "dimension": "control", "orientation": "resource", "label_en": "Control", "label_sv": "Kontroll"},
            {"code": "AD3", "dimension": "curiosity", "orientation": "resource", "label_en": "Curiosity", "label_sv": "Nyfikenhet"},
            {"code": "AD4", "dimension": "confidence", "orientation": "resource", "label_en": "Confidence", "label_sv": "Tilltro"},
        ],
        "items": [
            {"item_number": 1, "factor_code": "AD1", "reverse_scoring": False, "text_en": "Thinking about what my future will be like.", "text_sv": "Tänka på hur min framtid kommer att se ut."},
            {"item_number": 2, "factor_code": "AD1", "reverse_scoring": False, "text_en": "Realising that today's choices shape my future.", "text_sv": "Inse att dagens val formar min framtid."},
            {"item_number": 3, "factor_code": "AD1", "reverse_scoring": False, "text_en": "Preparing for the future.", "text_sv": "Förbereda mig för framtiden."},
            {"item_number": 4, "factor_code": "AD1", "reverse_scoring": False, "text_en": "Becoming aware of the educational and career choices I have to make.", "text_sv": "Bli medveten om de utbildnings- och karriärval jag måste göra."},
            {"item_number": 5, "factor_code": "AD1", "reverse_scoring": False, "text_en": "Planning how to achieve my goals.", "text_sv": "Planera hur jag ska nå mina mål."},
            {"item_number": 6, "factor_code": "AD1", "reverse_scoring": False, "text_en": "Being concerned about my career.", "text_sv": "Vara engagerad i min karriär."},
            {"item_number": 7, "factor_code": "AD2", "reverse_scoring": False, "text_en": "Keeping upbeat.", "text_sv": "Hålla humöret uppe."},
            {"item_number": 8, "factor_code": "AD2", "reverse_scoring": False, "text_en": "Making decisions by myself.", "text_sv": "Fatta beslut på egen hand."},
            {"item_number": 9, "factor_code": "AD2", "reverse_scoring": False, "text_en": "Taking responsibility for my actions.", "text_sv": "Ta ansvar för mina handlingar."},
            {"item_number": 10, "factor_code": "AD2", "reverse_scoring": False, "text_en": "Sticking up for my beliefs.", "text_sv": "Stå upp för mina övertygelser."},
            {"item_number": 11, "factor_code": "AD2", "reverse_scoring": False, "text_en": "Counting on myself.", "text_sv": "Lita på mig själv."},
            {"item_number": 12, "factor_code": "AD2", "reverse_scoring": False, "text_en": "Doing what is right for me.", "text_sv": "Göra det som är rätt för mig."},
            {"item_number": 13, "factor_code": "AD3", "reverse_scoring": False, "text_en": "Looking for opportunities to grow as a person.", "text_sv": "Söka möjligheter att växa som person."},
            {"item_number": 14, "factor_code": "AD3", "reverse_scoring": False, "text_en": "Investigating options before making a choice.", "text_sv": "Undersöka alternativ innan jag fattar ett beslut."},
            {"item_number": 15, "factor_code": "AD3", "reverse_scoring": False, "text_en": "Observing how different people do things.", "text_sv": "Observera hur olika personer gör saker."},
            {"item_number": 16, "factor_code": "AD3", "reverse_scoring": False, "text_en": "Probing deeply into questions I have.", "text_sv": "Fördjupa mig i frågor jag har."},
            {"item_number": 17, "factor_code": "AD3", "reverse_scoring": False, "text_en": "Becoming curious about new opportunities.", "text_sv": "Bli nyfiken på nya möjligheter."},
            {"item_number": 18, "factor_code": "AD3", "reverse_scoring": False, "text_en": "Exploring my surroundings.", "text_sv": "Utforska min omgivning."},
            {"item_number": 19, "factor_code": "AD4", "reverse_scoring": False, "text_en": "Performing tasks efficiently.", "text_sv": "Utföra uppgifter effektivt."},
            {"item_number": 20, "factor_code": "AD4", "reverse_scoring": False, "text_en": "Taking care to do things well.", "text_sv": "Se till att göra saker bra."},
            {"item_number": 21, "factor_code": "AD4", "reverse_scoring": False, "text_en": "Learning new skills.", "text_sv": "Lära mig nya färdigheter."},
            {"item_number": 22, "factor_code": "AD4", "reverse_scoring": False, "text_en": "Working up to my ability.", "text_sv": "Arbeta upp till min förmåga."},
            {"item_number": 23, "factor_code": "AD4", "reverse_scoring": False, "text_en": "Overcoming obstacles.", "text_sv": "Övervinna hinder."},
            {"item_number": 24, "factor_code": "AD4", "reverse_scoring": False, "text_en": "Solving problems.", "text_sv": "Lösa problem."},
        ],
    },
}
