// Local copy is complete for every supported interface language.
export const classGroupTexts = {
    it: {
        title: "Gruppi e classi che gestisco",
        subtitle: "Gestisci classi scolastiche o gruppi di adulti, universitari e altri partecipanti. Si entra tramite link di invito (web o Telegram) o codice dall’area personale. Collega un gruppo o una classe a un piano di somministrazione per associare i risultati.",
        newGroup: "Nuovo gruppo o classe",
        namePlaceholder: "Nome (es. 3B, universitari, formazione adulti)",
        schoolPlaceholder: "Scuola, università o ente (opzionale)",
        school: "Scuola, università o ente",
        levelLabel: 'Fascia',
        levelNone: 'Fascia non indicata',
        levelSecondaria: 'Secondaria',
        levelUniversita: 'Università',
        levelAdulti: 'Adulti',
        levelHint: 'Filtra le letture consigliate: senza fascia il bot chiede al partecipante a che punto degli studi si trova.',
        institutionLabel: 'Istituto',
        institutionNone: 'Nessun istituto',
        institutionHint: "Alimenta il fallback per i partecipanti che non scelgono l'istituto nel taccuino.",
        contextTitle: 'Contesto classe',
        contextHint: 'Descrizione e metodologie della classe: con la condivisione attiva entrano nella chat guidata degli studenti iscritti e nella tua conversazione sugli obiettivi didattici.',
        descriptionLabel: 'Descrizione della classe',
        descriptionPlaceholder: 'Programma, progetti, convenzioni del gruppo (opzionale)',
        methodologyLabel: 'Metodologie con questa classe',
        methodologyPlaceholder: 'Come lavori di solito con loro (opzionale)',
        shareContextLabel: 'Condividi il contesto con gli studenti iscritti',
        save: 'Salva',
        saved: 'Salvato',
        create: 'Crea',
        cancel: 'Annulla',
        members: 'iscritti',
        inactive: 'disattivata',
        webLink: 'Link invito',
        telegramLink: 'Link Telegram',
        code: "Codice di invito",
        students: "Partecipanti",
        deactivate: 'Disattiva',
        activate: 'Riattiva',
        deleteGroup: 'Elimina',
        empty: "Non gestisci ancora gruppi o classi. Creane uno e condividi il link con i partecipanti.",
        error: 'Operazione non riuscita.',
        shareTitle: 'Condivisa con',
        shareBtn: 'Aggiungi selezionati',
        sharedWith: 'Condivisa con',
        removeShare: 'Rimuovi',
        noShares: 'Non condivisa con altri.',
        shareError: 'Condivisione non riuscita.',
        shareSelectUsers: 'Seleziona utenti da aggiungere',
        shareAlreadyShared: 'gia\' condivisa',
        shareNoUsers: 'Nessun utente disponibile.',
    },
    en: {
        title: "Groups and classes I manage",
        subtitle: "Manage school classes or groups of adults, university students and other participants. Members join via an invitation link (web or Telegram) or a code in their personal area. Link a group or class to an administration plan to associate results.",
        newGroup: "New group or class",
        namePlaceholder: "Name (e.g. 3B, university students, adult learning)",
        schoolPlaceholder: "School, university or organisation (optional)",
        school: "School, university or organisation",
        levelLabel: 'Level',
        levelNone: 'No level set',
        levelSecondaria: 'Secondary',
        levelUniversita: 'University',
        levelAdulti: 'Adults',
        levelHint: 'Filters the readings the bot may suggest: with no level it asks the participant where they are in their studies.',
        institutionLabel: 'Institution',
        institutionNone: 'No institution',
        institutionHint: 'Feeds the fallback for participants who never choose an institution in their notebook.',
        contextTitle: 'Class context',
        contextHint: 'Class description and methodologies: when sharing is on they enter the guided chat of enrolled students and your didactic-objective conversation.',
        descriptionLabel: 'Class description',
        descriptionPlaceholder: 'Curriculum, projects, group conventions (optional)',
        methodologyLabel: 'Methodologies with this class',
        methodologyPlaceholder: 'How you usually work with them (optional)',
        shareContextLabel: 'Share the context with enrolled students',
        save: 'Save',
        saved: 'Saved',
        create: 'Create',
        cancel: 'Cancel',
        members: 'members',
        inactive: 'inactive',
        webLink: 'Invitation link',
        telegramLink: 'Telegram link',
        code: "Invitation code",
        students: "Participants",
        deactivate: 'Deactivate',
        activate: 'Reactivate',
        deleteGroup: 'Delete',
        empty: "You do not manage any groups or classes yet. Create one and share the link with participants.",
        error: 'Operation failed.',
        shareTitle: 'Shared with',
        shareBtn: 'Add selected',
        sharedWith: 'Shared with',
        removeShare: 'Remove',
        noShares: 'Not shared with anyone.',
        shareError: 'Share failed.',
        shareSelectUsers: 'Select users to add',
        shareAlreadyShared: 'already shared',
        shareNoUsers: 'No users available.',
    },
    es: {
        title: "Grupos y clases que gestiono",
        subtitle: "Gestiona clases escolares o grupos de adultos, universitarios y otros participantes. Se accede mediante un enlace de invitación (web o Telegram) o un código en el área personal. Vincula un grupo o una clase a un plan de administración para asociar los resultados.",
        newGroup: "Nuevo grupo o clase", namePlaceholder: "Nombre (p. ej., 3B, universitarios, formación de adultos)",
        schoolPlaceholder: "Escuela, universidad o entidad (opcional)", school: "Escuela, universidad o entidad", levelLabel: 'Nivel', levelNone: 'Nivel no indicado',
        levelSecondaria: 'Secundaria', levelUniversita: 'Universidad', levelAdulti: 'Adultos',
        levelHint: 'Filtra las lecturas recomendadas: sin un nivel, el bot pregunta al participante en qué etapa de sus estudios se encuentra.',
        institutionLabel: 'Institución', institutionNone: 'Sin institución',
        institutionHint: 'Alimenta el resguardo para los participantes que nunca eligen una institución en su cuaderno.',
        contextTitle: 'Contexto de la clase',
        contextHint: 'Descripción y metodologías de la clase: con el uso compartido entran en el chat guiado de los estudiantes inscritos y en tu conversación sobre objetivos didácticos.',
        descriptionLabel: 'Descripción de la clase',
        descriptionPlaceholder: 'Programa, proyectos, convenciones del grupo (opcional)',
        methodologyLabel: 'Metodologías con esta clase',
        methodologyPlaceholder: 'Cómo sueles trabajar con ellos (opcional)',
        shareContextLabel: 'Compartir el contexto con los estudiantes inscritos',
        save: 'Guardar',
        saved: 'Guardado',
        create: 'Crear', cancel: 'Cancelar', members: 'miembros', inactive: 'inactiva', webLink: 'Enlace de invitación',
        telegramLink: 'Enlace de Telegram', code: "Código de invitación", students: "Participantes", deactivate: 'Desactivar',
        activate: 'Reactivar', deleteGroup: 'Eliminar', empty: "Aún no gestionas grupos ni clases. Crea uno y comparte el enlace con los participantes.",
        error: 'La operación ha fallado.', shareTitle: 'Compartida con', shareBtn: 'Añadir seleccionados', sharedWith: 'Compartida con',
        removeShare: 'Quitar', noShares: 'No compartida con nadie.', shareError: 'No se pudo compartir.',
        shareSelectUsers: 'Selecciona usuarios para añadir', shareAlreadyShared: 'ya compartida', shareNoUsers: 'No hay usuarios disponibles.',
    },
    fr: {
        title: "Groupes et classes que je gère",
        subtitle: "Gérez des classes scolaires ou des groupes d’adultes, d’étudiants universitaires et d’autres participants. L’inscription se fait par lien d’invitation (web ou Telegram) ou par code dans l’espace personnel. Associez un groupe ou une classe à un plan de passation pour relier les résultats.",
        newGroup: "Nouveau groupe ou classe", namePlaceholder: "Nom (ex. 3B, étudiants, formation pour adultes)",
        schoolPlaceholder: "École, université ou organisme (facultatif)", school: "École, université ou organisme", levelLabel: 'Niveau', levelNone: 'Niveau non indiqué',
        levelSecondaria: 'Secondaire', levelUniversita: 'Université', levelAdulti: 'Adultes',
        levelHint: 'Filtre les lectures recommandées : sans niveau, le bot demande au participant où il en est dans ses études.',
        institutionLabel: 'Établissement', institutionNone: 'Aucun établissement',
        institutionHint: "Alimente le repli pour les participants qui ne choisissent jamais d'établissement dans leur carnet.",
        contextTitle: 'Contexte de la classe',
        contextHint: 'Description et méthodologies de la classe : quand le partage est activé, elles entrent dans la conversation guidée des étudiants inscrits et dans votre échange sur les objectifs didactiques.',
        descriptionLabel: 'Description de la classe',
        descriptionPlaceholder: 'Programme, projets, conventions du groupe (facultatif)',
        methodologyLabel: 'Méthodologies avec cette classe',
        methodologyPlaceholder: 'Comment vous travaillez habituellement avec eux (facultatif)',
        shareContextLabel: 'Partager le contexte avec les étudiants inscrits',
        save: 'Enregistrer',
        saved: 'Enregistré',
        create: 'Créer', cancel: 'Annuler', members: 'membres', inactive: 'inactive', webLink: 'Lien d’invitation',
        telegramLink: 'Lien Telegram', code: "Code d’invitation", students: "Participants", deactivate: 'Désactiver',
        activate: 'Réactiver', deleteGroup: 'Supprimer', empty: "Vous ne gérez pas encore de groupes ou de classes. Créez-en un et partagez le lien avec les participants.",
        error: 'L’opération a échoué.', shareTitle: 'Partagée avec', shareBtn: 'Ajouter la sélection', sharedWith: 'Partagée avec',
        removeShare: 'Retirer', noShares: 'Partagée avec personne.', shareError: 'Échec du partage.',
        shareSelectUsers: 'Sélectionnez les utilisateurs à ajouter', shareAlreadyShared: 'déjà partagée', shareNoUsers: 'Aucun utilisateur disponible.',
    },
    de: {
        title: "Gruppen und Klassen, die ich verwalte",
        subtitle: "Verwalten Sie Schulklassen oder Gruppen von Erwachsenen, Studierenden und anderen Teilnehmenden. Der Beitritt erfolgt per Einladungslink (Web oder Telegram) oder Code im persönlichen Bereich. Verknüpfen Sie eine Gruppe oder Klasse mit einem Durchführungsplan, um Ergebnisse zuzuordnen.",
        newGroup: "Neue Gruppe oder Klasse", namePlaceholder: "Name (z. B. 3B, Studierende, Erwachsenenbildung)",
        schoolPlaceholder: "Schule, Universität oder Organisation (optional)", school: "Schule, Universität oder Organisation", levelLabel: 'Stufe', levelNone: 'Keine Stufe angegeben',
        levelSecondaria: 'Sekundarstufe', levelUniversita: 'Universität', levelAdulti: 'Erwachsene',
        levelHint: 'Filtert empfohlene Lektüren: Ohne Stufe fragt der Bot die Teilnehmenden nach ihrem Ausbildungsstand.',
        institutionLabel: 'Einrichtung', institutionNone: 'Keine Einrichtung',
        institutionHint: 'Speist den Fallback für Teilnehmende, die im Lernheft nie eine Einrichtung wählen.',
        contextTitle: 'Klassenkontext',
        contextHint: 'Beschreibung und Methoden der Klasse: Bei freigegebenem Kontext fließen sie in den geführten Chat der eingeschriebenen Teilnehmenden und in Ihr Gespräch über Unterrichtsziele ein.',
        descriptionLabel: 'Beschreibung der Klasse',
        descriptionPlaceholder: 'Lehrplan, Projekte, Absprachen der Gruppe (optional)',
        methodologyLabel: 'Methoden mit dieser Klasse',
        methodologyPlaceholder: 'Wie Sie üblicherweise mit ihnen arbeiten (optional)',
        shareContextLabel: 'Kontext mit den eingeschriebenen Teilnehmenden teilen',
        save: 'Speichern',
        saved: 'Gespeichert',
        create: 'Erstellen', cancel: 'Abbrechen', members: 'Mitglieder', inactive: 'inaktiv', webLink: 'Einladungslink',
        telegramLink: 'Telegram-Link', code: "Einladungscode", students: "Teilnehmende", deactivate: 'Deaktivieren',
        activate: 'Reaktivieren', deleteGroup: 'Löschen', empty: "Sie verwalten noch keine Gruppen oder Klassen. Erstellen Sie eine und teilen Sie den Link mit den Teilnehmenden.",
        error: 'Der Vorgang ist fehlgeschlagen.', shareTitle: 'Geteilt mit', shareBtn: 'Ausgewählte hinzufügen', sharedWith: 'Geteilt mit',
        removeShare: 'Entfernen', noShares: 'Mit niemandem geteilt.', shareError: 'Teilen fehlgeschlagen.',
        shareSelectUsers: 'Hinzuzufügende Benutzer auswählen', shareAlreadyShared: 'bereits geteilt', shareNoUsers: 'Keine Benutzer verfügbar.',
    },
    sv: {
        title: "Grupper och klasser jag hanterar",
        subtitle: "Hantera skolklasser eller grupper av vuxna, universitetsstudenter och andra deltagare. Deltagare går med via inbjudningslänk (webb eller Telegram) eller en kod i den personliga vyn. Koppla en grupp eller klass till en genomförandeplan för att knyta resultaten till den.",
        newGroup: "Ny grupp eller klass", namePlaceholder: "Namn (t.ex. 3B, universitetsstudenter, vuxenutbildning)",
        schoolPlaceholder: "Skola, universitet eller organisation (valfritt)", school: "Skola, universitet eller organisation", levelLabel: 'Nivå', levelNone: 'Ingen nivå angiven',
        levelSecondaria: 'Gymnasienivå', levelUniversita: 'Universitet', levelAdulti: 'Vuxna',
        levelHint: 'Filtrerar rekommenderad läsning: utan nivå frågar boten deltagaren var i utbildningen hen befinner sig.',
        institutionLabel: 'Institution', institutionNone: 'Ingen institution',
        institutionHint: 'Förser reservvärdet för deltagare som aldrig väljer en institution i sin anteckningsbok.',
        contextTitle: 'Klasskontext',
        contextHint: 'Klassbeskrivning och arbetssätt: när delning är på kommer de in i den vägledde chatten för inskrivna deltagare och i din samtals om undervisningsmål.',
        descriptionLabel: 'Klassbeskrivning',
        descriptionPlaceholder: 'Kursplan, projekt, gruppens överenskommelser (valfritt)',
        methodologyLabel: 'Arbetssätt med den här klassen',
        methodologyPlaceholder: 'Hur du vanligtvis arbetar med dem (valfritt)',
        shareContextLabel: 'Dela kontexten med inskrivna deltagare',
        save: 'Spara',
        saved: 'Sparat',
        create: 'Skapa', cancel: 'Avbryt', members: 'medlemmar', inactive: 'inaktiv', webLink: 'Inbjudningslänk',
        telegramLink: 'Telegram-länk', code: "Inbjudningskod", students: "Deltagare", deactivate: 'Inaktivera',
        activate: 'Återaktivera', deleteGroup: 'Ta bort', empty: "Du hanterar inga grupper eller klasser ännu. Skapa en och dela länken med deltagarna.",
        error: 'Åtgärden misslyckades.', shareTitle: 'Delad med', shareBtn: 'Lägg till valda', sharedWith: 'Delad med',
        removeShare: 'Ta bort', noShares: 'Inte delad med någon.', shareError: 'Delningen misslyckades.',
        shareSelectUsers: 'Välj användare att lägga till', shareAlreadyShared: 'redan delad', shareNoUsers: 'Inga användare tillgängliga.',
    },
};
