// Testi localizzati del laboratorio prompt. Un solo punto di verità per i sei
// idiomi dell'app: i termini del laboratorio (ruoli, stati, soglie) sono
// specifici del pilota e vivono accanto al pannello che li usa, con la stessa
// forma dei moduli lib/i18n-*.ts (Record<Lang, ...> con l'italiano come fonte).

import type { Lang } from '@/lib/i18n';

export interface PromptLabCopy {
    title: string;
    subtitle: string;
    disabledTitle: string;
    disabledHint: string;
    reasonLabel: string;
    newExperiment: string;
    formTitle: string;
    experimentTitle: string;
    titlePlaceholder: string;
    purpose: string;
    purposeVerificationHint: string;
    purposeImprovementHint: string;
    target: string;
    languages: string;
    goals: string;
    goalsHint: string;
    goalText: string;
    goalTextPlaceholder: string;
    goalCriterion: string;
    goalCriterionPlaceholder: string;
    addGoal: string;
    removeGoal: string;
    designer: string;
    proposer: string;
    proposerNone: string;
    judge: string;
    tested: string;
    testedHint: string;
    maxCalls: string;
    maxMinutes: string;
    create: string;
    creating: string;
    createValidation: string;
    listEmpty: string;
    listHint: string;
    open: string;
    created: string;
    loading: string;
    back: string;
    error: string;
    refresh: string;
    prepare: string;
    startEval: string;
    repeat: string;
    repeatConfirm: string;
    cancel: string;
    needPrepare: string;
    needReview: string;
    unsavedCases: string;
    needGoals: string;
    needTested: string;
    reviewedLabel: string;
    saveCases: string;
    savedCases: string;
    casesTitle: string;
    casesHint: string;
    caseGroup: string;
    caseMessage: string;
    caseExpected: string;
    caseSplit: string;
    caseLanguage: string;
    caseHistory: string;
    historyUser: string;
    historyAssistant: string;
    candidatesTitle: string;
    candidatesHint: string;
    candidateReason: string;
    candidateExpected: string;
    promptDiffTitle: string;
    summaryTitle: string;
    selectedCandidate: string;
    completedCalls: string;
    metricsTitle: string;
    metricPreset: string;
    metricVariant: string;
    metricSplit: string;
    metricPassed: string;
    metricTotal: string;
    metricErrors: string;
    summaryReason: string;
    summaryGoals: string;
    runsTitle: string;
    runKind: string;
    runState: string;
    runCalls: string;
    runStarted: string;
    runFinished: string;
    runsEmpty: string;
    cancelRequested: string;
    resultsTitle: string;
    resultsFilter: string;
    resultsAll: string;
    resultsNone: string;
    expectedLabel: string;
    decisionTitle: string;
    decisionNote: string;
    decisionNotePlaceholder: string;
    decisionCandidate: string;
    noCandidate: string;
    needHash: string;
    accept: string;
    acceptConfirm: string;
    reject: string;
    rejectConfirm: string;
    restore: string;
    restoreConfirm: string;
    blockersTitle: string;
    blockersHint: string;
    verificationNoActivation: string;
    decisionRecorded: string;
    states: Record<string, string>;
    purposes: Record<string, string>;
    roles: Record<string, string>;
    runKinds: Record<string, string>;
    runStates: Record<string, string>;
    eligibility: Record<string, string>;
    splits: Record<string, string>;
}

const it: PromptLabCopy = {
    title: 'Laboratorio prompt',
    subtitle: 'Esperimenti isolati su casi sintetici locali: verifica o migliora un prompt prima di attivarlo in produzione.',
    disabledTitle: 'Laboratorio prompt disattivato',
    disabledHint: 'Il laboratorio è spento: la configurazione resta visibile ma non si possono creare o avviare esperimenti.',
    reasonLabel: 'Motivo',
    newExperiment: 'Nuovo esperimento',
    formTitle: 'Nuovo esperimento',
    experimentTitle: 'Titolo',
    titlePlaceholder: 'Titolo breve e descrittivo',
    purpose: 'Scopo',
    purposeVerificationHint: 'La verifica controlla il comportamento attuale e non attiva mai il prompt in produzione.',
    purposeImprovementHint: 'Il miglioramento può essere attivato solo dopo revisione e approvazione amministrativa.',
    target: 'Prompt obiettivo',
    languages: 'Lingue',
    goals: 'Obiettivi',
    goalsHint: 'Ogni obiettivo richiede un testo e un criterio osservabile.',
    goalText: 'Obiettivo (testo)',
    goalTextPlaceholder: 'Es. rispondere sempre con empatia',
    goalCriterion: 'Criterio (osservabile)',
    goalCriterionPlaceholder: 'Es. la risposta non contiene giudizi sulla persona',
    addGoal: 'Aggiungi obiettivo',
    removeGoal: 'Rimuovi',
    designer: 'Preparazione dei casi',
    proposer: 'Proponente',
    proposerNone: 'Nessuno (facoltativo)',
    judge: 'Giudice',
    tested: 'Modelli testati',
    testedHint: 'Modelli confrontati con il baseline. Il giudice è separato dai modelli testati.',
    maxCalls: 'Chiamate massime',
    maxMinutes: 'Minuti massimi',
    create: 'Crea esperimento',
    creating: 'Creazione…',
    createValidation: 'Compila titolo, prompt obiettivo, progettista, giudice, almeno un obiettivo con criterio, almeno una lingua e un modello testato.',
    listEmpty: 'Nessun esperimento.',
    listHint: 'Seleziona un esperimento per vedere i dettagli.',
    open: 'Apri',
    created: 'Creato',
    loading: 'Caricamento…',
    back: 'Torna all’elenco',
    error: 'Errore',
    refresh: 'Ricarica',
    prepare: 'Prepara i casi',
    startEval: 'Avvia la valutazione',
    repeat: 'Ripeti la valutazione',
    repeatConfirm: 'Ripetere la valutazione con gli stessi casi? Verrà creata una nuova esecuzione.',
    cancel: 'Annulla il lavoro',
    needPrepare: 'Prepara prima i casi sintetici.',
    needReview: 'Segna i casi come revisionati prima di avviare.',
    unsavedCases: 'Salva le modifiche ai casi prima di avviare.',
    needGoals: 'L’esperimento non ha obiettivi con criterio.',
    needTested: 'L’esperimento non ha modelli testati.',
    reviewedLabel: 'Ho revisionato tutti i casi',
    saveCases: 'Salva i casi',
    savedCases: 'Casi salvati.',
    casesTitle: 'Casi',
    casesHint: 'Modifica messaggio, esito atteso, split e lingua. La cronologia è in sola lettura.',
    caseGroup: 'Gruppo',
    caseMessage: 'Messaggio',
    caseExpected: 'Esito atteso',
    caseSplit: 'Split',
    caseLanguage: 'Lingua',
    caseHistory: 'Cronologia',
    historyUser: 'Utente',
    historyAssistant: 'Assistente',
    candidatesTitle: 'Prompt candidati',
    candidatesHint: 'Confronto con il baseline: le righe rimosse e aggiunte sono evidenziate.',
    candidateReason: 'Motivazione',
    candidateExpected: 'Effetto atteso',
    promptDiffTitle: 'Confronto con il baseline',
    summaryTitle: 'Sintesi',
    selectedCandidate: 'Candidato selezionato',
    completedCalls: 'Chiamate completate',
    metricsTitle: 'Metriche',
    metricPreset: 'Modello',
    metricVariant: 'Variante',
    metricSplit: 'Split',
    metricPassed: 'Passati',
    metricTotal: 'Totali',
    metricErrors: 'Errori',
    summaryReason: 'Motivazione',
    summaryGoals: 'Obiettivi',
    runsTitle: 'Esecuzioni',
    runKind: 'Tipo',
    runState: 'Stato',
    runCalls: 'Chiamate',
    runStarted: 'Avviata',
    runFinished: 'Terminata',
    runsEmpty: 'Nessuna esecuzione.',
    cancelRequested: 'Annullamento richiesto',
    resultsTitle: 'Risultati',
    resultsFilter: 'Modello',
    resultsAll: 'Tutti',
    resultsNone: 'Nessun risultato.',
    expectedLabel: 'Esito atteso',
    decisionTitle: 'Decisione',
    decisionNote: 'Nota',
    decisionNotePlaceholder: 'Motivazione della decisione',
    decisionCandidate: 'Candidato',
    noCandidate: 'Seleziona un candidato per accettare.',
    needHash: 'Hash del manifest mancante: impossibile accettare.',
    accept: 'Accetta e attiva',
    acceptConfirm: 'Accettare il candidato e attivare il prompt in produzione?',
    reject: 'Rifiuta',
    rejectConfirm: 'Rifiutare l’esperimento?',
    restore: 'Ripristina',
    restoreConfirm: 'Ripristinare il prompt precedente?',
    blockersTitle: 'Blocchi all’approvazione',
    blockersHint: 'L’accettazione resta disabilitata finché i blocchi non sono risolti.',
    verificationNoActivation: 'Un esperimento di verifica non attiva mai un prompt.',
    decisionRecorded: 'Decisione registrata',
    states: {
        draft: 'Bozza', ready: 'Pronto', running: 'In esecuzione', completed: 'Completato',
        failed: 'Fallito', cancelled: 'Annullato', activated: 'Attivato', error: 'Errore',
    },
    purposes: { verification: 'Verifica', improvement: 'Miglioramento' },
    roles: {
        designer: 'Preparazione', proposer: 'Proponente', judge: 'Giudice',
        tested: 'Modello testato', baseline: 'Baseline', candidate: 'Candidato',
    },
    runKinds: { prepare: 'Preparazione', evaluate: 'Valutazione' },
    runStates: {
        queued: 'In coda', running: 'In corso', completed: 'Completata', failed: 'Fallita',
        cancelled: 'Annullata', budget_exceeded: 'Budget esaurito', interrupted: 'Interrotta',
    },
    eligibility: {
        eligible: 'Idoneo', not_eligible: 'Non idoneo', inconclusive: 'Non conclusivo', not_applicable: 'Non applicabile',
    },
    splits: { development: 'Sviluppo', validation: 'Validazione', final: 'Finale' },
};

const en: PromptLabCopy = {
    title: 'Prompt lab',
    subtitle: 'Isolated experiments on local synthetic cases: verify or improve a prompt before activating it in production.',
    disabledTitle: 'Prompt lab disabled',
    disabledHint: 'The lab is off: the configuration stays visible, but experiments cannot be created or run.',
    reasonLabel: 'Reason',
    newExperiment: 'New experiment',
    formTitle: 'New experiment',
    experimentTitle: 'Title',
    titlePlaceholder: 'Short, descriptive title',
    purpose: 'Purpose',
    purposeVerificationHint: 'Verification checks current behaviour and never activates the prompt in production.',
    purposeImprovementHint: 'An improvement can only be activated after admin review and approval.',
    target: 'Target prompt',
    languages: 'Languages',
    goals: 'Goals',
    goalsHint: 'Each goal needs a text and an observable criterion.',
    goalText: 'Goal (text)',
    goalTextPlaceholder: 'E.g. always answer with empathy',
    goalCriterion: 'Criterion (observable)',
    goalCriterionPlaceholder: 'E.g. the answer contains no judgement about the person',
    addGoal: 'Add goal',
    removeGoal: 'Remove',
    designer: 'Designer',
    proposer: 'Proposer',
    proposerNone: 'None (optional)',
    judge: 'Judge',
    tested: 'Tested models',
    testedHint: 'Models compared against the baseline. The judge is separate from the tested models.',
    maxCalls: 'Max calls',
    maxMinutes: 'Max minutes',
    create: 'Create experiment',
    creating: 'Creating…',
    createValidation: 'Fill in title, target prompt, designer, judge, at least one goal with criterion, at least one language and one tested model.',
    listEmpty: 'No experiments yet.',
    listHint: 'Select an experiment to see its details.',
    open: 'Open',
    created: 'Created',
    loading: 'Loading…',
    back: 'Back to list',
    error: 'Error',
    refresh: 'Reload',
    prepare: 'Prepare cases',
    startEval: 'Start evaluation',
    repeat: 'Repeat evaluation',
    repeatConfirm: 'Repeat the evaluation with the same cases? A new run will be created.',
    cancel: 'Cancel work',
    needPrepare: 'Prepare the synthetic cases first.',
    needReview: 'Mark the cases as reviewed before starting.',
    unsavedCases: 'Save the case changes before starting.',
    needGoals: 'The experiment has no goals with a criterion.',
    needTested: 'The experiment has no tested models.',
    reviewedLabel: 'I have reviewed all cases',
    saveCases: 'Save cases',
    savedCases: 'Cases saved.',
    casesTitle: 'Cases',
    casesHint: 'Edit message, expected outcome, split and language. History is read-only.',
    caseGroup: 'Group',
    caseMessage: 'Message',
    caseExpected: 'Expected outcome',
    caseSplit: 'Split',
    caseLanguage: 'Language',
    caseHistory: 'History',
    historyUser: 'User',
    historyAssistant: 'Assistant',
    candidatesTitle: 'Candidate prompts',
    candidatesHint: 'Comparison with the baseline: removed and added lines are highlighted.',
    candidateReason: 'Reason',
    candidateExpected: 'Expected effect',
    promptDiffTitle: 'Comparison with the baseline',
    summaryTitle: 'Summary',
    selectedCandidate: 'Selected candidate',
    completedCalls: 'Completed calls',
    metricsTitle: 'Metrics',
    metricPreset: 'Model',
    metricVariant: 'Variant',
    metricSplit: 'Split',
    metricPassed: 'Passed',
    metricTotal: 'Total',
    metricErrors: 'Errors',
    summaryReason: 'Reason',
    summaryGoals: 'Goals',
    runsTitle: 'Runs',
    runKind: 'Kind',
    runState: 'State',
    runCalls: 'Calls',
    runStarted: 'Started',
    runFinished: 'Finished',
    runsEmpty: 'No runs yet.',
    cancelRequested: 'Cancellation requested',
    resultsTitle: 'Results',
    resultsFilter: 'Model',
    resultsAll: 'All',
    resultsNone: 'No results yet.',
    expectedLabel: 'Expected outcome',
    decisionTitle: 'Decision',
    decisionNote: 'Note',
    decisionNotePlaceholder: 'Reason for the decision',
    decisionCandidate: 'Candidate',
    noCandidate: 'Select a candidate to accept.',
    needHash: 'Manifest hash missing: cannot accept.',
    accept: 'Accept and activate',
    acceptConfirm: 'Accept the candidate and activate the prompt in production?',
    reject: 'Reject',
    rejectConfirm: 'Reject the experiment?',
    restore: 'Restore',
    restoreConfirm: 'Restore the previous prompt?',
    blockersTitle: 'Approval blockers',
    blockersHint: 'Acceptance stays disabled until the blockers are resolved.',
    verificationNoActivation: 'A verification experiment never activates a prompt.',
    decisionRecorded: 'Decision recorded',
    states: {
        draft: 'Draft', ready: 'Ready', running: 'Running', completed: 'Completed',
        failed: 'Failed', cancelled: 'Cancelled', activated: 'Activated', error: 'Error',
    },
    purposes: { verification: 'Verification', improvement: 'Improvement' },
    roles: {
        designer: 'Designer', proposer: 'Proposer', judge: 'Judge',
        tested: 'Tested model', baseline: 'Baseline', candidate: 'Candidate',
    },
    runKinds: { prepare: 'Preparation', evaluate: 'Evaluation' },
    runStates: {
        queued: 'Queued', running: 'Running', completed: 'Completed', failed: 'Failed',
        cancelled: 'Cancelled', budget_exceeded: 'Budget exceeded', interrupted: 'Interrupted',
    },
    eligibility: {
        eligible: 'Eligible', not_eligible: 'Not eligible', inconclusive: 'Inconclusive', not_applicable: 'Not applicable',
    },
    splits: { development: 'Development', validation: 'Validation', final: 'Final' },
};

const es: PromptLabCopy = {
    title: 'Laboratorio de prompts',
    subtitle: 'Experimentos aislados con casos sintéticos locales: verifica o mejora un prompt antes de activarlo en producción.',
    disabledTitle: 'Laboratorio de prompts desactivado',
    disabledHint: 'El laboratorio está apagado: la configuración sigue visible, pero no se pueden crear ni ejecutar experimentos.',
    reasonLabel: 'Motivo',
    newExperiment: 'Nuevo experimento',
    formTitle: 'Nuevo experimento',
    experimentTitle: 'Título',
    titlePlaceholder: 'Título breve y descriptivo',
    purpose: 'Propósito',
    purposeVerificationHint: 'La verificación comprueba el comportamiento actual y nunca activa el prompt en producción.',
    purposeImprovementHint: 'Una mejora solo puede activarse tras la revisión y aprobación del administrador.',
    target: 'Prompt objetivo',
    languages: 'Idiomas',
    goals: 'Objetivos',
    goalsHint: 'Cada objetivo requiere un texto y un criterio observable.',
    goalText: 'Objetivo (texto)',
    goalTextPlaceholder: 'P. ej. responder siempre con empatía',
    goalCriterion: 'Criterio (observable)',
    goalCriterionPlaceholder: 'P. ej. la respuesta no contiene juicios sobre la persona',
    addGoal: 'Añadir objetivo',
    removeGoal: 'Quitar',
    designer: 'Diseñador (designer)',
    proposer: 'Proponente',
    proposerNone: 'Ninguno (opcional)',
    judge: 'Juez',
    tested: 'Modelos probados',
    testedHint: 'Modelos comparados con la línea base. El juez está separado de los modelos probados.',
    maxCalls: 'Llamadas máximas',
    maxMinutes: 'Minutos máximos',
    create: 'Crear experimento',
    creating: 'Creando…',
    createValidation: 'Rellena título, prompt objetivo, diseñador, juez, al menos un objetivo con criterio, un idioma y un modelo probado.',
    listEmpty: 'Ningún experimento.',
    listHint: 'Selecciona un experimento para ver los detalles.',
    open: 'Abrir',
    created: 'Creado',
    loading: 'Cargando…',
    back: 'Volver a la lista',
    error: 'Error',
    refresh: 'Recargar',
    prepare: 'Preparar los casos',
    startEval: 'Iniciar evaluación',
    repeat: 'Repetir evaluación',
    repeatConfirm: '¿Repetir la evaluación con los mismos casos? Se creará una nueva ejecución.',
    cancel: 'Cancelar el trabajo',
    needPrepare: 'Prepara primero los casos sintéticos.',
    needReview: 'Marca los casos como revisados antes de empezar.',
    unsavedCases: 'Guarda los cambios de los casos antes de empezar.',
    needGoals: 'El experimento no tiene objetivos con criterio.',
    needTested: 'El experimento no tiene modelos probados.',
    reviewedLabel: 'He revisado todos los casos',
    saveCases: 'Guardar casos',
    savedCases: 'Casos guardados.',
    casesTitle: 'Casos',
    casesHint: 'Edita mensaje, resultado esperado, división e idioma. El historial es de solo lectura.',
    caseGroup: 'Grupo',
    caseMessage: 'Mensaje',
    caseExpected: 'Resultado esperado',
    caseSplit: 'División',
    caseLanguage: 'Idioma',
    caseHistory: 'Historial',
    historyUser: 'Usuario',
    historyAssistant: 'Asistente',
    candidatesTitle: 'Prompts candidatos',
    candidatesHint: 'Comparación con la línea base: las líneas eliminadas y añadidas están resaltadas.',
    candidateReason: 'Motivo',
    candidateExpected: 'Efecto esperado',
    promptDiffTitle: 'Comparación con la línea base',
    summaryTitle: 'Resumen',
    selectedCandidate: 'Candidato seleccionado',
    completedCalls: 'Llamadas completadas',
    metricsTitle: 'Métricas',
    metricPreset: 'Modelo',
    metricVariant: 'Variante',
    metricSplit: 'División',
    metricPassed: 'Superados',
    metricTotal: 'Totales',
    metricErrors: 'Errores',
    summaryReason: 'Motivo',
    summaryGoals: 'Objetivos',
    runsTitle: 'Ejecuciones',
    runKind: 'Tipo',
    runState: 'Estado',
    runCalls: 'Llamadas',
    runStarted: 'Iniciada',
    runFinished: 'Terminada',
    runsEmpty: 'Ninguna ejecución.',
    cancelRequested: 'Cancelación solicitada',
    resultsTitle: 'Resultados',
    resultsFilter: 'Modelo',
    resultsAll: 'Todos',
    resultsNone: 'Ningún resultado.',
    expectedLabel: 'Resultado esperado',
    decisionTitle: 'Decisión',
    decisionNote: 'Nota',
    decisionNotePlaceholder: 'Motivo de la decisión',
    decisionCandidate: 'Candidato',
    noCandidate: 'Selecciona un candidato para aceptar.',
    needHash: 'Falta el hash del manifiesto: no se puede aceptar.',
    accept: 'Aceptar y activar',
    acceptConfirm: '¿Aceptar el candidato y activar el prompt en producción?',
    reject: 'Rechazar',
    rejectConfirm: '¿Rechazar el experimento?',
    restore: 'Restaurar',
    restoreConfirm: '¿Restaurar el prompt anterior?',
    blockersTitle: 'Bloqueos de aprobación',
    blockersHint: 'La aceptación queda desactivada hasta resolver los bloqueos.',
    verificationNoActivation: 'Un experimento de verificación nunca activa un prompt.',
    decisionRecorded: 'Decisión registrada',
    states: {
        draft: 'Borrador', ready: 'Listo', running: 'En ejecución', completed: 'Completado',
        failed: 'Fallido', cancelled: 'Cancelado', activated: 'Activado', error: 'Error',
    },
    purposes: { verification: 'Verificación', improvement: 'Mejora' },
    roles: {
        designer: 'Diseñador', proposer: 'Proponente', judge: 'Juez',
        tested: 'Modelo probado', baseline: 'Línea base', candidate: 'Candidato',
    },
    runKinds: { prepare: 'Preparación', evaluate: 'Evaluación' },
    runStates: {
        queued: 'En cola', running: 'En curso', completed: 'Completada', failed: 'Fallida',
        cancelled: 'Cancelada', budget_exceeded: 'Presupuesto agotado', interrupted: 'Interrumpida',
    },
    eligibility: {
        eligible: 'Elegible', not_eligible: 'No elegible', inconclusive: 'No concluyente', not_applicable: 'No aplicable',
    },
    splits: { development: 'Desarrollo', validation: 'Validación', final: 'Final' },
};

const fr: PromptLabCopy = {
    title: 'Laboratoire de prompts',
    subtitle: 'Expériences isolées sur des cas synthétiques locaux : vérifier ou améliorer un prompt avant de l’activer en production.',
    disabledTitle: 'Laboratoire de prompts désactivé',
    disabledHint: 'Le laboratoire est éteint : la configuration reste visible, mais les expériences ne peuvent ni être créées ni exécutées.',
    reasonLabel: 'Motif',
    newExperiment: 'Nouvelle expérience',
    formTitle: 'Nouvelle expérience',
    experimentTitle: 'Titre',
    titlePlaceholder: 'Titre court et descriptif',
    purpose: 'Objet',
    purposeVerificationHint: 'La vérification contrôle le comportement actuel et n’active jamais le prompt en production.',
    purposeImprovementHint: 'Une amélioration ne peut être activée qu’après révision et approbation administrative.',
    target: 'Prompt cible',
    languages: 'Langues',
    goals: 'Objectifs',
    goalsHint: 'Chaque objectif exige un texte et un critère observable.',
    goalText: 'Objectif (texte)',
    goalTextPlaceholder: 'Ex. répondre toujours avec empathie',
    goalCriterion: 'Critère (observable)',
    goalCriterionPlaceholder: 'Ex. la réponse ne contient aucun jugement sur la personne',
    addGoal: 'Ajouter un objectif',
    removeGoal: 'Retirer',
    designer: 'Concepteur (designer)',
    proposer: 'Proposeur',
    proposerNone: 'Aucun (facultatif)',
    judge: 'Juge',
    tested: 'Modèles testés',
    testedHint: 'Modèles comparés à la référence. Le juge est séparé des modèles testés.',
    maxCalls: 'Appels maximum',
    maxMinutes: 'Minutes maximum',
    create: 'Créer l’expérience',
    creating: 'Création…',
    createValidation: 'Renseignez le titre, le prompt cible, le concepteur, le juge, au moins un objectif avec critère, une langue et un modèle testé.',
    listEmpty: 'Aucune expérience.',
    listHint: 'Sélectionnez une expérience pour voir les détails.',
    open: 'Ouvrir',
    created: 'Créée',
    loading: 'Chargement…',
    back: 'Retour à la liste',
    error: 'Erreur',
    refresh: 'Recharger',
    prepare: 'Préparer les cas',
    startEval: 'Lancer l’évaluation',
    repeat: 'Répéter l’évaluation',
    repeatConfirm: 'Répéter l’évaluation avec les mêmes cas ? Une nouvelle exécution sera créée.',
    cancel: 'Annuler le travail',
    needPrepare: 'Préparez d’abord les cas synthétiques.',
    needReview: 'Marquez les cas comme relus avant de lancer.',
    unsavedCases: 'Enregistrez les modifications des cas avant de lancer.',
    needGoals: 'L’expérience n’a pas d’objectif avec critère.',
    needTested: 'L’expérience n’a pas de modèle testé.',
    reviewedLabel: 'J’ai relu tous les cas',
    saveCases: 'Enregistrer les cas',
    savedCases: 'Cas enregistrés.',
    casesTitle: 'Cas',
    casesHint: 'Modifiez le message, le résultat attendu, la répartition et la langue. L’historique est en lecture seule.',
    caseGroup: 'Groupe',
    caseMessage: 'Message',
    caseExpected: 'Résultat attendu',
    caseSplit: 'Répartition',
    caseLanguage: 'Langue',
    caseHistory: 'Historique',
    historyUser: 'Utilisateur',
    historyAssistant: 'Assistant',
    candidatesTitle: 'Prompts candidats',
    candidatesHint: 'Comparaison avec la référence : les lignes supprimées et ajoutées sont surlignées.',
    candidateReason: 'Motif',
    candidateExpected: 'Effet attendu',
    promptDiffTitle: 'Comparaison avec la référence',
    summaryTitle: 'Synthèse',
    selectedCandidate: 'Candidat retenu',
    completedCalls: 'Appels terminés',
    metricsTitle: 'Métriques',
    metricPreset: 'Modèle',
    metricVariant: 'Variante',
    metricSplit: 'Répartition',
    metricPassed: 'Réussis',
    metricTotal: 'Total',
    metricErrors: 'Erreurs',
    summaryReason: 'Motif',
    summaryGoals: 'Objectifs',
    runsTitle: 'Exécutions',
    runKind: 'Type',
    runState: 'État',
    runCalls: 'Appels',
    runStarted: 'Lancée',
    runFinished: 'Terminée',
    runsEmpty: 'Aucune exécution.',
    cancelRequested: 'Annulation demandée',
    resultsTitle: 'Résultats',
    resultsFilter: 'Modèle',
    resultsAll: 'Tous',
    resultsNone: 'Aucun résultat.',
    expectedLabel: 'Résultat attendu',
    decisionTitle: 'Décision',
    decisionNote: 'Note',
    decisionNotePlaceholder: 'Motif de la décision',
    decisionCandidate: 'Candidat',
    noCandidate: 'Sélectionnez un candidat pour accepter.',
    needHash: 'Empreinte du manifeste manquante : acceptation impossible.',
    accept: 'Accepter et activer',
    acceptConfirm: 'Accepter le candidat et activer le prompt en production ?',
    reject: 'Rejeter',
    rejectConfirm: 'Rejeter l’expérience ?',
    restore: 'Restaurer',
    restoreConfirm: 'Restaurer le prompt précédent ?',
    blockersTitle: 'Blocages d’approbation',
    blockersHint: 'L’acceptation reste désactivée tant que les blocages ne sont pas levés.',
    verificationNoActivation: 'Une expérience de vérification n’active jamais un prompt.',
    decisionRecorded: 'Décision enregistrée',
    states: {
        draft: 'Brouillon', ready: 'Prêt', running: 'En cours', completed: 'Terminée',
        failed: 'Échouée', cancelled: 'Annulée', activated: 'Activée', error: 'Erreur',
    },
    purposes: { verification: 'Vérification', improvement: 'Amélioration' },
    roles: {
        designer: 'Concepteur', proposer: 'Proposeur', judge: 'Juge',
        tested: 'Modèle testé', baseline: 'Référence', candidate: 'Candidat',
    },
    runKinds: { prepare: 'Préparation', evaluate: 'Évaluation' },
    runStates: {
        queued: 'En file', running: 'En cours', completed: 'Terminée', failed: 'Échouée',
        cancelled: 'Annulée', budget_exceeded: 'Budget dépassé', interrupted: 'Interrompue',
    },
    eligibility: {
        eligible: 'Éligible', not_eligible: 'Non éligible', inconclusive: 'Non concluant', not_applicable: 'Non applicable',
    },
    splits: { development: 'Développement', validation: 'Validation', final: 'Final' },
};

const de: PromptLabCopy = {
    title: 'Prompt-Labor',
    subtitle: 'Isolierte Experimente mit lokalen synthetischen Fällen: einen Prompt prüfen oder verbessern, bevor er produktiv geschaltet wird.',
    disabledTitle: 'Prompt-Labor deaktiviert',
    disabledHint: 'Das Labor ist aus: Die Konfiguration bleibt sichtbar, aber Experimente können weder erstellt noch ausgeführt werden.',
    reasonLabel: 'Grund',
    newExperiment: 'Neues Experiment',
    formTitle: 'Neues Experiment',
    experimentTitle: 'Titel',
    titlePlaceholder: 'Kurzer, beschreibender Titel',
    purpose: 'Zweck',
    purposeVerificationHint: 'Die Prüfung kontrolliert das aktuelle Verhalten und schaltet den Prompt nie produktiv.',
    purposeImprovementHint: 'Eine Verbesserung kann erst nach Prüfung und Freigabe durch die Verwaltung aktiviert werden.',
    target: 'Ziel-Prompt',
    languages: 'Sprachen',
    goals: 'Ziele',
    goalsHint: 'Jedes Ziel braucht einen Text und ein beobachtbares Kriterium.',
    goalText: 'Ziel (Text)',
    goalTextPlaceholder: 'Z. B. immer einfühlsam antworten',
    goalCriterion: 'Kriterium (beobachtbar)',
    goalCriterionPlaceholder: 'Z. B. die Antwort enthält keine Bewertung der Person',
    addGoal: 'Ziel hinzufügen',
    removeGoal: 'Entfernen',
    designer: 'Designer',
    proposer: 'Vorschlagender',
    proposerNone: 'Keiner (optional)',
    judge: 'Richter',
    tested: 'Getestete Modelle',
    testedHint: 'Modelle, die mit der Basislinie verglichen werden. Der Richter ist von den getesteten Modellen getrennt.',
    maxCalls: 'Max. Aufrufe',
    maxMinutes: 'Max. Minuten',
    create: 'Experiment erstellen',
    creating: 'Wird erstellt…',
    createValidation: 'Titel, Ziel-Prompt, Designer, Richter, mindestens ein Ziel mit Kriterium, eine Sprache und ein getestetes Modell angeben.',
    listEmpty: 'Keine Experimente.',
    listHint: 'Wähle ein Experiment, um die Details zu sehen.',
    open: 'Öffnen',
    created: 'Erstellt',
    loading: 'Wird geladen…',
    back: 'Zurück zur Liste',
    error: 'Fehler',
    refresh: 'Neu laden',
    prepare: 'Fälle vorbereiten',
    startEval: 'Auswertung starten',
    repeat: 'Auswertung wiederholen',
    repeatConfirm: 'Die Auswertung mit denselben Fällen wiederholen? Ein neuer Lauf wird erstellt.',
    cancel: 'Arbeit abbrechen',
    needPrepare: 'Bereite zuerst die synthetischen Fälle vor.',
    needReview: 'Markiere die Fälle als geprüft, bevor du startest.',
    unsavedCases: 'Speichere die Änderungen an den Fällen, bevor du startest.',
    needGoals: 'Das Experiment hat keine Ziele mit Kriterium.',
    needTested: 'Das Experiment hat keine getesteten Modelle.',
    reviewedLabel: 'Ich habe alle Fälle geprüft',
    saveCases: 'Fälle speichern',
    savedCases: 'Fälle gespeichert.',
    casesTitle: 'Fälle',
    casesHint: 'Nachricht, erwartetes Ergebnis, Aufteilung und Sprache bearbeiten. Der Verlauf ist schreibgeschützt.',
    caseGroup: 'Gruppe',
    caseMessage: 'Nachricht',
    caseExpected: 'Erwartetes Ergebnis',
    caseSplit: 'Aufteilung',
    caseLanguage: 'Sprache',
    caseHistory: 'Verlauf',
    historyUser: 'Nutzer',
    historyAssistant: 'Assistent',
    candidatesTitle: 'Kandidaten-Prompts',
    candidatesHint: 'Vergleich mit der Basislinie: entfernte und hinzugefügte Zeilen sind hervorgehoben.',
    candidateReason: 'Begründung',
    candidateExpected: 'Erwartete Wirkung',
    promptDiffTitle: 'Vergleich mit der Basislinie',
    summaryTitle: 'Zusammenfassung',
    selectedCandidate: 'Gewählter Kandidat',
    completedCalls: 'Abgeschlossene Aufrufe',
    metricsTitle: 'Kennzahlen',
    metricPreset: 'Modell',
    metricVariant: 'Variante',
    metricSplit: 'Aufteilung',
    metricPassed: 'Bestanden',
    metricTotal: 'Gesamt',
    metricErrors: 'Fehler',
    summaryReason: 'Begründung',
    summaryGoals: 'Ziele',
    runsTitle: 'Läufe',
    runKind: 'Art',
    runState: 'Zustand',
    runCalls: 'Aufrufe',
    runStarted: 'Gestartet',
    runFinished: 'Beendet',
    runsEmpty: 'Noch keine Läufe.',
    cancelRequested: 'Abbruch angefordert',
    resultsTitle: 'Ergebnisse',
    resultsFilter: 'Modell',
    resultsAll: 'Alle',
    resultsNone: 'Noch keine Ergebnisse.',
    expectedLabel: 'Erwartetes Ergebnis',
    decisionTitle: 'Entscheidung',
    decisionNote: 'Notiz',
    decisionNotePlaceholder: 'Begründung der Entscheidung',
    decisionCandidate: 'Kandidat',
    noCandidate: 'Wähle einen Kandidaten, um anzunehmen.',
    needHash: 'Manifest-Hash fehlt: Annahme nicht möglich.',
    accept: 'Annehmen und aktivieren',
    acceptConfirm: 'Den Kandidaten annehmen und den Prompt produktiv schalten?',
    reject: 'Ablehnen',
    rejectConfirm: 'Das Experiment ablehnen?',
    restore: 'Wiederherstellen',
    restoreConfirm: 'Den vorherigen Prompt wiederherstellen?',
    blockersTitle: 'Freigabe-Blocker',
    blockersHint: 'Die Annahme bleibt gesperrt, bis die Blocker gelöst sind.',
    verificationNoActivation: 'Ein Prüfungsexperiment schaltet nie einen Prompt frei.',
    decisionRecorded: 'Entscheidung erfasst',
    states: {
        draft: 'Entwurf', ready: 'Bereit', running: 'Läuft', completed: 'Abgeschlossen',
        failed: 'Fehlgeschlagen', cancelled: 'Abgebrochen', activated: 'Aktiviert', error: 'Fehler',
    },
    purposes: { verification: 'Prüfung', improvement: 'Verbesserung' },
    roles: {
        designer: 'Designer', proposer: 'Vorschlagender', judge: 'Richter',
        tested: 'Getestetes Modell', baseline: 'Basislinie', candidate: 'Kandidat',
    },
    runKinds: { prepare: 'Vorbereitung', evaluate: 'Auswertung' },
    runStates: {
        queued: 'In Warteschlange', running: 'Läuft', completed: 'Abgeschlossen', failed: 'Fehlgeschlagen',
        cancelled: 'Abgebrochen', budget_exceeded: 'Budget überschritten', interrupted: 'Unterbrochen',
    },
    eligibility: {
        eligible: 'Geeignet', not_eligible: 'Nicht geeignet', inconclusive: 'Nicht schlüssig', not_applicable: 'Nicht anwendbar',
    },
    splits: { development: 'Entwicklung', validation: 'Validierung', final: 'Final' },
};

const sv: PromptLabCopy = {
    title: 'Promptlabb',
    subtitle: 'Isolerade experiment med lokala syntetiska fall: verifiera eller förbättra en prompt innan den aktiveras i produktion.',
    disabledTitle: 'Promptlabbet är inaktiverat',
    disabledHint: 'Labbet är avstängt: konfigurationen visas, men experiment kan varken skapas eller köras.',
    reasonLabel: 'Orsak',
    newExperiment: 'Nytt experiment',
    formTitle: 'Nytt experiment',
    experimentTitle: 'Titel',
    titlePlaceholder: 'Kort, beskrivande titel',
    purpose: 'Syfte',
    purposeVerificationHint: 'Verifiering kontrollerar nuvarande beteende och aktiverar aldrig prompten i produktion.',
    purposeImprovementHint: 'En förbättring kan bara aktiveras efter granskning och godkännande.',
    target: 'Mål-prompt',
    languages: 'Språk',
    goals: 'Mål',
    goalsHint: 'Varje mål kräver en text och ett observerbart kriterium.',
    goalText: 'Mål (text)',
    goalTextPlaceholder: 'T.ex. svara alltid med empati',
    goalCriterion: 'Kriterium (observerbart)',
    goalCriterionPlaceholder: 'T.ex. svaret innehåller ingen värdering av personen',
    addGoal: 'Lägg till mål',
    removeGoal: 'Ta bort',
    designer: 'Designer',
    proposer: 'Förslagsställare',
    proposerNone: 'Ingen (valfritt)',
    judge: 'Domare',
    tested: 'Testade modeller',
    testedHint: 'Modeller som jämförs med baslinjen. Domaren är skild från de testade modellerna.',
    maxCalls: 'Max anrop',
    maxMinutes: 'Max minuter',
    create: 'Skapa experiment',
    creating: 'Skapar…',
    createValidation: 'Fyll i titel, mål-prompt, designer, domare, minst ett mål med kriterium, ett språk och en testad modell.',
    listEmpty: 'Inga experiment ännu.',
    listHint: 'Välj ett experiment för att se detaljerna.',
    open: 'Öppna',
    created: 'Skapad',
    loading: 'Läser…',
    back: 'Tillbaka till listan',
    error: 'Fel',
    refresh: 'Ladda om',
    prepare: 'Förbered fall',
    startEval: 'Starta utvärdering',
    repeat: 'Upprepa utvärdering',
    repeatConfirm: 'Upprepa utvärderingen med samma fall? En ny körning skapas.',
    cancel: 'Avbryt arbete',
    needPrepare: 'Förbered de syntetiska fallen först.',
    needReview: 'Markera fallen som granskade innan du startar.',
    unsavedCases: 'Spara ändringarna i fallen innan du startar.',
    needGoals: 'Experimentet har inga mål med kriterium.',
    needTested: 'Experimentet har inga testade modeller.',
    reviewedLabel: 'Jag har granskat alla fall',
    saveCases: 'Spara fall',
    savedCases: 'Fallen är sparade.',
    casesTitle: 'Fall',
    casesHint: 'Redigera meddelande, förväntat utfall, uppdelning och språk. Historiken är skrivskyddad.',
    caseGroup: 'Grupp',
    caseMessage: 'Meddelande',
    caseExpected: 'Förväntat utfall',
    caseSplit: 'Uppdelning',
    caseLanguage: 'Språk',
    caseHistory: 'Historik',
    historyUser: 'Användare',
    historyAssistant: 'Assistent',
    candidatesTitle: 'Kandidatprompter',
    candidatesHint: 'Jämförelse med baslinjen: borttagna och tillagda rader är markerade.',
    candidateReason: 'Motiv',
    candidateExpected: 'Förväntad effekt',
    promptDiffTitle: 'Jämförelse med baslinjen',
    summaryTitle: 'Sammanfattning',
    selectedCandidate: 'Vald kandidat',
    completedCalls: 'Genomförda anrop',
    metricsTitle: 'Mått',
    metricPreset: 'Modell',
    metricVariant: 'Variant',
    metricSplit: 'Uppdelning',
    metricPassed: 'Godkända',
    metricTotal: 'Totalt',
    metricErrors: 'Fel',
    summaryReason: 'Motivering',
    summaryGoals: 'Mål',
    runsTitle: 'Körningar',
    runKind: 'Typ',
    runState: 'Tillstånd',
    runCalls: 'Anrop',
    runStarted: 'Startad',
    runFinished: 'Avslutad',
    runsEmpty: 'Inga körningar ännu.',
    cancelRequested: 'Avbrott begärt',
    resultsTitle: 'Resultat',
    resultsFilter: 'Modell',
    resultsAll: 'Alla',
    resultsNone: 'Inga resultat ännu.',
    expectedLabel: 'Förväntat utfall',
    decisionTitle: 'Beslut',
    decisionNote: 'Anteckning',
    decisionNotePlaceholder: 'Motivering till beslutet',
    decisionCandidate: 'Kandidat',
    noCandidate: 'Välj en kandidat för att acceptera.',
    needHash: 'Manifest-hash saknas: kan inte acceptera.',
    accept: 'Acceptera och aktivera',
    acceptConfirm: 'Acceptera kandidaten och aktivera prompten i produktion?',
    reject: 'Avvisa',
    rejectConfirm: 'Avvisa experimentet?',
    restore: 'Återställ',
    restoreConfirm: 'Återställ den tidigare prompten?',
    blockersTitle: 'Godkännandeblockerare',
    blockersHint: 'Accepterande förblir låst tills blockeringarna är lösta.',
    verificationNoActivation: 'Ett verifieringsexperiment aktiverar aldrig en prompt.',
    decisionRecorded: 'Beslut registrerat',
    states: {
        draft: 'Utkast', ready: 'Klar', running: 'Körs', completed: 'Slutförd',
        failed: 'Misslyckad', cancelled: 'Avbruten', activated: 'Aktiverad', error: 'Fel',
    },
    purposes: { verification: 'Verifiering', improvement: 'Förbättring' },
    roles: {
        designer: 'Designer', proposer: 'Förslagsställare', judge: 'Domare',
        tested: 'Testad modell', baseline: 'Baslinje', candidate: 'Kandidat',
    },
    runKinds: { prepare: 'Förberedelse', evaluate: 'Utvärdering' },
    runStates: {
        queued: 'I kö', running: 'Körs', completed: 'Slutförd', failed: 'Misslyckad',
        cancelled: 'Avbruten', budget_exceeded: 'Budget överskriden', interrupted: 'Avbruten',
    },
    eligibility: {
        eligible: 'Godkänd', not_eligible: 'Ej godkänd', inconclusive: 'Ej avgjord', not_applicable: 'Ej tillämplig',
    },
    splits: { development: 'Utveckling', validation: 'Validering', final: 'Final' },
};

const COPIES: Record<Lang, PromptLabCopy> = { it, en, es, fr, de, sv };

export function promptLabCopy(lang: Lang): PromptLabCopy {
    return COPIES[lang] ?? it;
}
