const labels: Record<string, Record<string, string>> = {
    it: { interrupted: "Risposta interrotta. Puoi completarla.", continue: "Continua", resumeError: "Impossibile aggiornare le sessioni da riprendere.", retry: "Riprova", close: 'Chiudi finestra', write: 'Scrivi…', messageActions: 'Azioni del messaggio', options: 'Opzioni della conversazione', panel: 'Pannello', panelTitle: 'Percorso e risorse', show: 'Mostra pannello', hide: 'Nascondi pannello', narrow: 'Riduci larghezza del pannello', widen: 'Aumenta larghezza del pannello', resize: 'Larghezza del pannello: usa le frecce per regolarla', resources: 'Risorse disponibili', step: 'Passo', navigation: 'Avanzamento del percorso' },
    en: { interrupted: "Response interrupted. You can complete it.", continue: "Continue", resumeError: "Unable to refresh resumable sessions.", retry: "Retry", close: 'Close window', write: 'Write…', messageActions: 'Message actions', options: 'Conversation options', panel: 'Panel', panelTitle: 'Path and resources', show: 'Show panel', hide: 'Hide panel', narrow: 'Narrow the panel', widen: 'Widen the panel', resize: 'Panel width: use arrow keys to adjust', resources: 'Available resources', step: 'Step', navigation: 'Path navigation' },
    es: { interrupted: "Respuesta interrumpida. Puedes completarla.", continue: "Continuar", resumeError: "No se pueden actualizar las sesiones para reanudar.", retry: "Reintentar", close: 'Cerrar ventana', write: 'Escribe…', messageActions: 'Acciones del mensaje', options: 'Opciones de la conversación', panel: 'Panel', panelTitle: 'Recorrido y recursos', show: 'Mostrar panel', hide: 'Ocultar panel', narrow: 'Reducir el ancho del panel', widen: 'Aumentar el ancho del panel', resize: 'Ancho del panel: usa las flechas para ajustarlo', resources: 'Recursos disponibles', step: 'Paso', navigation: 'Avance del recorrido' },
    fr: { interrupted: "Réponse interrompue. Vous pouvez la compléter.", continue: "Continuer", resumeError: "Impossible de mettre à jour les sessions à reprendre.", retry: "Réessayer", close: 'Fermer la fenêtre', write: 'Écris…', messageActions: 'Actions du message', options: 'Options de la conversation', panel: 'Panneau', panelTitle: 'Parcours et ressources', show: 'Afficher le panneau', hide: 'Masquer le panneau', narrow: 'Réduire la largeur du panneau', widen: 'Augmenter la largeur du panneau', resize: 'Largeur du panneau : utilisez les flèches pour ajuster', resources: 'Ressources disponibles', step: 'Étape', navigation: 'Avancement du parcours' },
    de: { interrupted: "Antwort unterbrochen. Du kannst sie vervollständigen.", continue: "Fortsetzen", resumeError: "Fortsetzbare Sitzungen konnten nicht aktualisiert werden.", retry: "Erneut versuchen", close: 'Fenster schließen', write: 'Schreibe…', messageActions: 'Nachrichtenaktionen', options: 'Gesprächsoptionen', panel: 'Seitenleiste', panelTitle: 'Verlauf und Ressourcen', show: 'Seitenleiste anzeigen', hide: 'Seitenleiste ausblenden', narrow: 'Seitenleiste schmaler machen', widen: 'Seitenleiste breiter machen', resize: 'Breite der Seitenleiste: mit Pfeiltasten anpassen', resources: 'Verfügbare Ressourcen', step: 'Schritt', navigation: 'Navigation durch den Verlauf' },
    sv: { interrupted: "Svaret avbröts. Du kan slutföra det.", continue: "Fortsätt", resumeError: "Det gick inte att uppdatera sessionerna att återuppta.", retry: "Försök igen", close: 'Stäng fönstret', write: 'Skriv…', messageActions: 'Meddelandeåtgärder', options: 'Samtalsalternativ', panel: 'Panel', panelTitle: 'Steg och resurser', show: 'Visa panelen', hide: 'Dölj panelen', narrow: 'Gör panelen smalare', widen: 'Gör panelen bredare', resize: 'Panelens bredd: justera med piltangenterna', resources: 'Tillgängliga resurser', step: 'Steg', navigation: 'Navigering mellan steg' },
};

export function chatLayoutLabel(locale: string, key: string): string {
    return (labels[locale.slice(0, 2)] ?? labels.en)[key] ?? labels.en[key] ?? key;
}
