import type { Lang } from './i18n';

const languages: Lang[] = ['it', 'en', 'es', 'fr', 'de', 'sv'];
type Localized = readonly [string, string, string, string, string, string];
const texts = {
    sectionTitle: ['API e ChatGPT', 'APIs and ChatGPT', 'API y ChatGPT', 'API et ChatGPT', 'APIs und ChatGPT', 'API:er och ChatGPT'],
    sectionLocation: ['I collegamenti alle API personali e a ChatGPT si trovano in fondo all’Area personale e all’Area docenti, nella sezione «API e ChatGPT».', 'Links to personal APIs and ChatGPT are at the bottom of the Personal area and Teacher area, in the “APIs and ChatGPT” section.', 'Los enlaces a las API personales y a ChatGPT están al final del Área personal y del Área docente, en la sección «API y ChatGPT».', 'Les liens vers les API personnelles et ChatGPT se trouvent en bas de l’Espace personnel et de l’Espace enseignant, dans la section « API et ChatGPT ».', 'Die Links zu eigenen APIs und ChatGPT stehen unten im persönlichen Bereich und im Lehrkräftebereich unter „APIs und ChatGPT“.', 'Länkarna till egna API:er och ChatGPT finns längst ned i det personliga området och lärarområdet, i avsnittet ”API:er och ChatGPT”.'],
    errChatConnection: ['Non riesco a raggiungere il servizio della chat. Riprova tra poco; se il problema continua, contatta l’amministratore.', 'The chat service cannot be reached. Try again shortly; if the problem continues, contact the administrator.', 'No se puede acceder al servicio de chat. Inténtalo de nuevo en unos instantes; si el problema continúa, contacta con el administrador.', 'Le service de chat est inaccessible. Réessaie dans un instant ; si le problème persiste, contacte l’administrateur.', 'Der Chatdienst ist nicht erreichbar. Versuche es gleich erneut; wenn das Problem anhält, wende dich an die Administration.', 'Chattjänsten kan inte nås. Försök igen om en stund; om problemet kvarstår, kontakta administratören.'],
    errChatAccess: ['La sessione di accesso non è valida oppure non hai accesso a questa chat. Accedi di nuovo; se il problema continua, contatta l’amministratore.', 'Your sign-in session is invalid or you do not have access to this chat. Sign in again; if the problem continues, contact the administrator.', 'Tu sesión no es válida o no tienes acceso a este chat. Inicia sesión de nuevo; si el problema continúa, contacta con el administrador.', 'Ta session est invalide ou tu n’as pas accès à ce chat. Reconnecte-toi ; si le problème persiste, contacte l’administrateur.', 'Deine Sitzung ist ungültig oder du hast keinen Zugriff auf diesen Chat. Melde dich erneut an; wenn das Problem anhält, wende dich an die Administration.', 'Din inloggningssession är ogiltig eller du saknar åtkomst till chatten. Logga in igen; om problemet kvarstår, kontakta administratören.'],
    errChatConfiguration: ['Non è stato possibile avviare questo passaggio con la configurazione corrente. Ripeti il passaggio; se il problema continua, chiedi all’amministratore di controllare il percorso e il counselor.', 'This step could not start with the current settings. Repeat the step; if the problem continues, ask the administrator to check the path and counselor.', 'No se ha podido iniciar este paso con la configuración actual. Repite el paso; si el problema continúa, pide al administrador que revise el recorrido y el counselor.', 'Cette étape n’a pas pu démarrer avec la configuration actuelle. Répète l’étape ; si le problème persiste, demande à l’administrateur de vérifier le parcours et le counselor.', 'Dieser Schritt konnte mit den aktuellen Einstellungen nicht gestartet werden. Wiederhole den Schritt; wenn das Problem anhält, bitte die Administration, den Ablauf und den Counselor zu prüfen.', 'Det här steget kunde inte starta med de aktuella inställningarna. Upprepa steget; om problemet kvarstår, be administratören kontrollera flödet och counselorn.'],
    title: ['API personali', 'Personal APIs', 'API personales', 'API personnelles', 'Eigene APIs', 'Egna API:er'],
    description: ["Gestisci le tue connessioni AI e i modelli dei counselor.", "Manage your AI connections and counselor models.", "Gestiona tus conexiones de IA y los modelos de los counselors.", "Gère tes connexions IA et les modèles des counselors.", "Verwalte deine KI-Verbindungen und die Modelle der Counselor.", "Hantera dina AI-anslutningar och counselorernas modeller."],
    notice: ['La chiave è cifrata sul server e non viene mostrata dopo il salvataggio. I costi delle richieste personali sono a carico del tuo account presso il provider. Questa scelta vale per chat, Bussola, studio da PDF, analisi combinata, Tavolo e diagrammi. I servizi locali, audio e gli strumenti tecnici mantengono la configurazione di sistema.', 'The key is encrypted on the server and hidden after saving. Personal requests are billed to your provider account. This choice applies to chat, Compass, PDF study, combined analysis, Tavolo and diagrams. Local services, audio and technical tools keep the system configuration.', 'La clave se cifra en el servidor y se oculta tras guardarla. Las solicitudes personales se facturan a tu cuenta del proveedor. La elección se aplica al chat, Brújula, estudio de PDF, análisis combinado, Tavolo y diagramas. Los servicios locales, audio y herramientas técnicas conservan la configuración del sistema.', 'La clé est chiffrée sur le serveur et masquée après enregistrement. Les requêtes personnelles sont facturées à ton compte fournisseur. Ce choix concerne le chat, la Boussole, l’étude de PDF, l’analyse combinée, Tavolo et les diagrammes. Les services locaux, audio et outils techniques gardent la configuration du système.', 'Der Schlüssel wird auf dem Server verschlüsselt und nach dem Speichern verborgen. Eigene Anfragen werden deinem Anbieterkonto berechnet. Die Auswahl gilt für Chat, Kompass, PDF-Lernen, kombinierte Analyse, Tavolo und Diagramme. Lokale Dienste, Audio und technische Werkzeuge behalten die Systemkonfiguration.', 'Nyckeln krypteras på servern och visas inte efter att den sparats. Egna anrop debiteras ditt konto hos leverantören. Valet gäller chatt, Kompassen, PDF-studier, kombinerad analys, Tavolo och diagram. Lokala tjänster, ljud och tekniska verktyg behåller systemets inställningar.'],
    unavailable: ['L’amministratore ha disabilitato le API personali. Le nuove richieste usano le API di sistema. Puoi comunque eliminare la tua chiave salvata.', 'The administrator has disabled personal APIs. New requests use system APIs. You can still delete your saved key.', 'El administrador ha desactivado las API personales. Las nuevas solicitudes usan las API del sistema. Aún puedes eliminar tu clave guardada.', 'L’administrateur a désactivé les API personnelles. Les nouvelles requêtes utilisent les API du système. Tu peux toujours supprimer ta clé enregistrée.', 'Die Administration hat eigene APIs deaktiviert. Neue Anfragen nutzen System-APIs. Du kannst deinen gespeicherten Schlüssel weiterhin löschen.', 'Administratören har stängt av egna API:er. Nya anrop använder systemets API:er. Du kan fortfarande ta bort din sparade nyckel.'],
    provider: ['Provider', 'Provider', 'Proveedor', 'Fournisseur', 'Anbieter', 'Leverantör'],
    model: ['Modello', 'Model', 'Modelo', 'Modèle', 'Modell', 'Modell'],
    modelHelp: ['Inserisci l’identificativo esatto di un modello disponibile nel tuo account.', 'Enter the exact ID of a model available to your account.', 'Introduce el ID exacto de un modelo disponible en tu cuenta.', 'Saisis l’identifiant exact d’un modèle disponible dans ton compte.', 'Gib die genaue ID eines für dein Konto verfügbaren Modells ein.', 'Ange exakt ID för en modell som är tillgänglig för ditt konto.'],
    key: ['Chiave API', 'API key', 'Clave API', 'Clé API', 'API-Schlüssel', 'API-nyckel'],
    keySaved: ['Chiave salvata: lascia vuoto per mantenerla. Inserisci una nuova chiave quando cambi provider.', 'Key saved: leave blank to keep it. Enter a new key when changing provider.', 'Clave guardada: déjalo vacío para conservarla. Introduce una nueva clave al cambiar de proveedor.', 'Clé enregistrée : laisse vide pour la conserver. Saisis une nouvelle clé si tu changes de fournisseur.', 'Schlüssel gespeichert: leer lassen, um ihn beizubehalten. Bei Anbieterwechsel einen neuen Schlüssel eingeben.', 'Nyckel sparad: lämna tomt för att behålla den. Ange en ny nyckel när du byter leverantör.'],
    usePersonal: ['Usa le mie API personali', 'Use my personal APIs', 'Usar mis API personales', 'Utiliser mes API personnelles', 'Meine eigenen APIs verwenden', 'Använd mina egna API:er'],
    system: ['API di sistema in uso', 'Using system APIs', 'Usando las API del sistema', 'API du système utilisées', 'System-APIs aktiv', 'Systemets API:er används'],
    active: ['API personali in uso', 'Using personal APIs', 'Usando las API personales', 'API personnelles utilisées', 'Eigene APIs aktiv', 'Egna API:er används'],
    saved: ['Configurazione salvata.', 'Settings saved.', 'Configuración guardada.', 'Configuration enregistrée.', 'Einstellungen gespeichert.', 'Inställningarna har sparats.'],
    save: ['Salva configurazione', 'Save settings', 'Guardar configuración', 'Enregistrer', 'Einstellungen speichern', 'Spara inställningar'],
    verify: ['Verifica chiave salvata', 'Verify saved key', 'Verificar clave guardada', 'Vérifier la clé enregistrée', 'Gespeicherten Schlüssel prüfen', 'Kontrollera sparad nyckel'],
    working: ['La chiave è valida. La disponibilità del modello dipende dal tuo account.', 'The key is valid. Model availability depends on your account.', 'La clave es válida. La disponibilidad del modelo depende de tu cuenta.', 'La clé est valide. La disponibilité du modèle dépend de ton compte.', 'Der Schlüssel ist gültig. Die Modellverfügbarkeit hängt von deinem Konto ab.', 'Nyckeln är giltig. Modellens tillgänglighet beror på ditt konto.'],
    failed: ['Verifica non riuscita. Controlla la chiave e l’accesso al provider.', 'Verification failed. Check the key and provider access.', 'La verificación ha fallado. Comprueba la clave y el acceso al proveedor.', 'Échec de vérification. Vérifie la clé et l’accès au fournisseur.', 'Prüfung fehlgeschlagen. Prüfe Schlüssel und Anbieterzugang.', 'Kontrollen misslyckades. Kontrollera nyckeln och åtkomsten till leverantören.'],
    remove: ['Elimina chiave personale', 'Delete personal key', 'Eliminar clave personal', 'Supprimer la clé personnelle', 'Eigenen Schlüssel löschen', 'Ta bort egen nyckel'],
    confirm: ['Eliminare la chiave e tornare alle API di sistema?', 'Delete the key and return to system APIs?', '¿Eliminar la clave y volver a las API del sistema?', 'Supprimer la clé et revenir aux API du système ?', 'Schlüssel löschen und zu System-APIs wechseln?', 'Ta bort nyckeln och återgå till systemets API:er?'],
    error: ['Operazione non riuscita. Riprova; se la funzione è stata disabilitata, ricarica la pagina.', 'Operation failed. Retry; if the feature was disabled, reload the page.', 'La operación ha fallado. Reintenta; si se ha desactivado la función, recarga la página.', 'Échec de l’opération. Réessaie ; si la fonction a été désactivée, recharge la page.', 'Vorgang fehlgeschlagen. Versuche es erneut; falls die Funktion deaktiviert wurde, lade die Seite neu.', 'Åtgärden misslyckades. Försök igen; om funktionen har stängts av, ladda om sidan.'],
    loading: ['Caricamento…', 'Loading…', 'Cargando…', 'Chargement…', 'Wird geladen…', 'Laddar…'],
    retry: ['Riprova', 'Retry', 'Reintentar', 'Réessayer', 'Erneut versuchen', 'Försök igen'],
    login: ['Accedi per configurare le tue API.', 'Sign in to configure your APIs.', 'Inicia sesión para configurar tus API.', 'Connecte-toi pour configurer tes API.', 'Melde dich an, um deine APIs einzurichten.', 'Logga in för att konfigurera dina API:er.'],
    signIn: ['Accedi', 'Sign in', 'Iniciar sesión', 'Se connecter', 'Anmelden', 'Logga in'],
    dirty: ['Hai modifiche non salvate. Uscire dalla pagina?', 'You have unsaved changes. Leave this page?', 'Tienes cambios sin guardar. ¿Salir de la página?', 'Tu as des modifications non enregistrées. Quitter la page ?', 'Du hast ungespeicherte Änderungen. Seite verlassen?', 'Du har osparade ändringar. Lämna sidan?'],
    adminToggle: ['Consenti API personali a studenti e docenti', 'Allow personal APIs for students and teachers', 'Permitir API personales a estudiantes y docentes', 'Autoriser les API personnelles pour les élèves et enseignants', 'Eigene APIs für Lernende und Lehrkräfte erlauben', 'Tillåt egna API:er för elever och lärare'],
    adminHelp: ["La disattivazione nasconde la funzione nelle aree personali di studenti e docenti. Le chiavi salvate restano cifrate; le nuove richieste tornano al modello dell’installazione.", "Disabling hides the feature in student and teacher personal areas. Saved keys remain encrypted; new requests return to the installation model.", "Al desactivarla, la función se oculta en las áreas personales de estudiantes y docentes. Las claves permanecen cifradas; las nuevas solicitudes vuelven al modelo de la instalación.", "La désactivation masque la fonction dans les espaces personnels des élèves et enseignants. Les clés restent chiffrées ; les nouvelles requêtes utilisent le modèle de l’installation.", "Die Deaktivierung blendet die Funktion in den persönlichen Bereichen der Lernenden und Lehrkräfte aus. Gespeicherte Schlüssel bleiben verschlüsselt; neue Anfragen nutzen das Modell der Installation.", "Avaktivering döljer funktionen i elevernas och lärarnas personliga områden. Sparade nycklar förblir krypterade; nya anrop använder installationens modell."],
    automatic: ["La protezione delle chiavi viene preparata automaticamente quando abiliti la funzione. Non servono comandi sul server.", "Key protection is prepared automatically when you enable the feature. No server commands are needed.", "La protección de las claves se prepara automáticamente al activar la función. No se necesitan comandos en el servidor.", "La protection des clés est préparée automatiquement à l’activation. Aucune commande sur le serveur n’est nécessaire.", "Der Schlüsselschutz wird beim Aktivieren automatisch eingerichtet. Es sind keine Serverbefehle erforderlich.", "Nyckelskyddet förbereds automatiskt när du aktiverar funktionen. Inga serverkommandon behövs."],
    protected: ["La protezione delle chiavi è pronta.", "Key protection is ready.", "La protección de las claves está lista.", "La protection des clés est prête.", "Der Schlüsselschutz ist bereit.", "Nyckelskyddet är klart."],
    backup: ["Includi l’archivio protetto delle credenziali nei backup del server per conservare le chiavi personali dopo un ripristino.", "Include protected credential storage in server backups to preserve personal keys after a restore.", "Incluye el almacenamiento protegido de credenciales en las copias del servidor para conservar las claves personales tras una restauración.", "Incluez le stockage protégé des identifiants dans les sauvegardes du serveur pour conserver les clés personnelles après restauration.", "Sichere den geschützten Anmeldedatenspeicher mit dem Server, damit persönliche Schlüssel nach einer Wiederherstellung erhalten bleiben.", "Ta med den skyddade lagringen av inloggningsuppgifter i serverns säkerhetskopior så att personliga nycklar finns kvar efter återställning."],
    keyMissing: ["La chiave di protezione manca e sono già presenti chiavi personali salvate. Ripristina la chiave dal backup prima di riattivare la funzione.", "The protection key is missing and personal keys are already saved. Restore it from backup before enabling the feature again.", "Falta la clave de protección y ya hay claves personales guardadas. Restáurala desde la copia antes de reactivar la función.", "La clé de protection manque alors que des clés personnelles sont enregistrées. Restaurez-la depuis la sauvegarde avant de réactiver la fonction.", "Der Schutzschlüssel fehlt, obwohl persönliche Schlüssel gespeichert sind. Stelle ihn aus der Sicherung wieder her, bevor du die Funktion erneut aktivierst.", "Skyddsnyckeln saknas och personliga nycklar har redan sparats. Återställ den från säkerhetskopian innan du aktiverar funktionen igen."],
    notConfigured: ["Non è stato possibile preparare la protezione delle credenziali. Controlla i permessi dell’archivio o eventuali impostazioni avanzate del server.", "Credential protection could not be prepared. Check storage permissions or any advanced server settings.", "No se pudo preparar la protección de credenciales. Comprueba los permisos del almacenamiento o la configuración avanzada del servidor.", "La protection des identifiants n’a pas pu être préparée. Vérifiez les permissions du stockage ou les réglages avancés du serveur.", "Der Schutz der Anmeldedaten konnte nicht eingerichtet werden. Prüfe die Speicherrechte oder erweiterte Servereinstellungen.", "Skyddet för inloggningsuppgifterna kunde inte förberedas. Kontrollera lagringens behörigheter eller avancerade serverinställningar."],
    choiceHelp: ["Attivando le tue API personali disattivi l’uso del tuo abbonamento ChatGPT. Entrambe le credenziali restano salvate.", "Enabling your personal APIs switches off use of your ChatGPT subscription. Both sets of credentials remain saved.", "Al activar tus API personales desactivas el uso de tu suscripción ChatGPT. Ambas credenciales permanecen guardadas.", "Activer tes API personnelles désactive l’utilisation de ton abonnement ChatGPT. Les deux identifiants restent enregistrés.", "Das Aktivieren eigener APIs deaktiviert die Nutzung deines ChatGPT-Abonnements. Beide Anmeldedaten bleiben gespeichert.", "När du aktiverar egna API:er stängs användningen av ditt ChatGPT-abonnemang av. Båda inloggningsuppgifterna finns kvar."],
    counselors: ["Modelli dei counselor", "Counselor models", "Modelos de los counselors", "Modèles des counselors", "Modelle der Counselor", "Counselorernas modeller"],
    allCounselors: ["Usa questo modello con tutti i counselor", "Use this model with all counselors", "Usar este modelo con todos los counselors", "Utiliser ce modèle avec tous les counselors", "Dieses Modell für alle Counselor verwenden", "Använd modellen med alla counselors"],
    associationHelp: ["Seleziona uno o più counselor: useranno questo modello con la tua chiave. Gli altri mantengono il modello di sistema. Le funzioni senza counselor usano le tue API quando attive.", "Select one or more counselors to use this model with your key. Others keep the system model. Features without a counselor use your APIs when active.", "Selecciona uno o varios counselors para usar este modelo con tu clave. Los demás mantienen el modelo del sistema. Las funciones sin counselor usan tus API cuando están activas.", "Choisis un ou plusieurs counselors qui utiliseront ce modèle avec ta clé. Les autres gardent le modèle du système. Les fonctions sans counselor utilisent tes API lorsqu’elles sont actives.", "Wähle einen oder mehrere Counselor aus, die dieses Modell mit deinem Schlüssel nutzen. Andere behalten das Systemmodell. Funktionen ohne Counselor nutzen deine APIs, wenn sie aktiv sind.", "Välj en eller flera counselors som använder modellen med din nyckel. Övriga behåller systemets modell. Funktioner utan counselor använder dina API:er när de är aktiva."],
    ownCounselors: ["I tuoi counselor", "Your counselors", "Tus counselors", "Tes counselors", "Deine Counselor", "Dina counselors"],
    ownHelp: ["Crea un counselor privato per il tuo account. Puoi associarlo al modello qui sopra e sceglierlo nelle nuove conversazioni.", "Create a private counselor for your account. Link it to the model above and select it for new conversations.", "Crea un counselor privado para tu cuenta. Asócialo al modelo de arriba y elígelo en nuevas conversaciones.", "Crée un counselor privé pour ton compte. Associe-le au modèle ci-dessus et choisis-le dans de nouvelles conversations.", "Erstelle einen privaten Counselor für dein Konto. Verknüpfe ihn mit dem Modell oben und wähle ihn für neue Gespräche.", "Skapa en privat counselor för ditt konto. Koppla den till modellen ovan och välj den i nya samtal."],
    createCounselor: ["Crea un counselor", "Create a counselor", "Crear un counselor", "Créer un counselor", "Counselor erstellen", "Skapa en counselor"],
    counselorName: ["Nome del counselor", "Counselor name", "Nombre del counselor", "Nom du counselor", "Name des Counselors", "Counselorns namn"],
    counselorDescription: ["Descrizione", "Description", "Descripción", "Description", "Beschreibung", "Beskrivning"],
    counselorInstructions: ["Istruzioni del counselor", "Counselor instructions", "Instrucciones del counselor", "Instructions du counselor", "Anweisungen für den Counselor", "Instruktioner för counselorn"],
    instructionsHelp: ["Scrivi nella tua lingua come vuoi che il counselor ti aiuti. Le istruzioni si aggiungono alle regole e ai prompt del percorso.", "Write in your own language how you want the counselor to help. These instructions are added to the path’s rules and prompts.", "Escribe en tu idioma cómo quieres que te ayude el counselor. Las instrucciones se añaden a las reglas y los prompts del recorrido.", "Écris dans ta langue comment tu souhaites être aidé. Ces instructions s’ajoutent aux règles et aux prompts du parcours.", "Beschreibe in deiner Sprache, wie der Counselor helfen soll. Die Anweisungen ergänzen die Regeln und Prompts des Ablaufs.", "Skriv på ditt språk hur du vill att counselorn ska hjälpa dig. Instruktionerna läggs till i flödets regler och promptar."],
    saveCounselor: ["Salva counselor", "Save counselor", "Guardar counselor", "Enregistrer le counselor", "Counselor speichern", "Spara counselor"],
    editCounselor: ["Modifica", "Edit", "Editar", "Modifier", "Bearbeiten", "Redigera"],
    deleteCounselor: ["Elimina counselor", "Delete counselor", "Eliminar counselor", "Supprimer le counselor", "Counselor löschen", "Ta bort counselor"],
    confirmCounselor: ["Eliminare questo counselor e le sue associazioni?", "Delete this counselor and its associations?", "¿Eliminar este counselor y sus asociaciones?", "Supprimer ce counselor et ses associations ?", "Diesen Counselor und seine Verknüpfungen löschen?", "Ta bort counselorn och dess kopplingar?"],
    personalCounselor: ["Personale", "Personal", "Personal", "Personnel", "Persönlich", "Personlig"],
    chooseCounselor: ["Seleziona almeno un counselor oppure scegli tutti.", "Select at least one counselor or choose all.", "Selecciona al menos un counselor o elige todos.", "Choisis au moins un counselor ou sélectionne-les tous.", "Wähle mindestens einen Counselor oder alle aus.", "Välj minst en counselor eller välj alla."],
    counselorSaved: ["Counselor salvato. Salva anche la configurazione se hai cambiato le associazioni al modello.", "Counselor saved. Also save the configuration if you changed the model associations.", "Counselor guardado. Guarda también la configuración si has cambiado las asociaciones al modelo.", "Counselor enregistré. Enregistre aussi la configuration si tu as modifié les associations au modèle.", "Counselor gespeichert. Speichere auch die Konfiguration, wenn du Modellverknüpfungen geändert hast.", "Counselorn sparades. Spara även inställningarna om du ändrade modellkopplingarna."],
    counselorRemoved: ["Counselor eliminato.", "Counselor deleted.", "Counselor eliminado.", "Counselor supprimé.", "Counselor gelöscht.", "Counselorn togs bort."],
    noCounselors: ["Non ci sono counselor disponibili. Puoi crearne uno personale qui sotto.", "No counselors are available. You can create your own below.", "No hay counselors disponibles. Puedes crear uno propio abajo.", "Aucun counselor disponible. Tu peux créer le tien ci-dessous.", "Keine Counselor verfügbar. Du kannst unten einen eigenen erstellen.", "Inga counselors är tillgängliga. Du kan skapa en egen nedan."],
    modelTest: ["Prova connessione e modello", "Test connection and model", "Probar conexión y modelo", "Tester la connexion et le modèle", "Verbindung und Modell testen", "Testa anslutning och modell"],
    modelTestHelp: ["La prova invia un breve messaggio di test usando la chiave e il modello salvati. Consuma quota e può avere un costo secondo il provider.", "The test sends a short test message using the saved key and model. It uses quota and may incur a provider charge.", "La prueba envía un mensaje breve con la clave y el modelo guardados. Consume cuota y puede tener un coste del proveedor.", "Le test envoie un bref message avec la clé et le modèle enregistrés. Il consomme du quota et peut être facturé par le fournisseur.", "Der Test sendet eine kurze Nachricht mit dem gespeicherten Schlüssel und Modell. Er verbraucht Kontingent und kann beim Anbieter Kosten verursachen.", "Testet skickar ett kort meddelande med den sparade nyckeln och modellen. Det använder kvot och kan medföra en kostnad hos leverantören."],
    modelWorking: ["Il modello ha risposto al messaggio di test.", "The model answered the test message.", "El modelo ha respondido al mensaje de prueba.", "Le modèle a répondu au message de test.", "Das Modell hat die Testnachricht beantwortet.", "Modellen svarade på testmeddelandet."],
    errAuthentication: ["Il provider ha rifiutato la chiave o i suoi permessi. Controlla le API personali.", "The provider rejected the key or its permissions. Check Personal APIs.", "El proveedor ha rechazado la clave o sus permisos. Revisa tus API personales.", "Le fournisseur a refusé la clé ou ses permissions. Vérifie tes API personnelles.", "Der Anbieter hat den Schlüssel oder seine Berechtigungen abgelehnt. Prüfe deine eigenen APIs.", "Leverantören nekade nyckeln eller dess behörigheter. Kontrollera egna API:er."],
    errModelUnavailable: ["Il modello scelto non è disponibile per questa chiave o non ha provider disponibili. Controlla l’identificativo del modello e le impostazioni OpenRouter.", "The selected model is unavailable for this key or has no available providers. Check the model ID and OpenRouter settings.", "El modelo no está disponible para esta clave o no tiene proveedores disponibles. Revisa el ID y la configuración de OpenRouter.", "Le modèle choisi est indisponible pour cette clé ou n’a aucun fournisseur disponible. Vérifie son identifiant et les réglages OpenRouter.", "Das Modell ist für diesen Schlüssel nicht verfügbar oder hat keine verfügbaren Anbieter. Prüfe die Modell-ID und die OpenRouter-Einstellungen.", "Modellen är inte tillgänglig för nyckeln eller saknar tillgängliga leverantörer. Kontrollera modellens ID och OpenRouter-inställningarna."],
    errQuota: ["Il provider segnala quota esaurita o credito insufficiente. Anche i modelli gratuiti possono avere limiti. Controlla il tuo account provider.", "The provider reports exhausted quota or insufficient credit. Free models can also have limits. Check your provider account.", "El proveedor indica cuota agotada o crédito insuficiente. Los modelos gratuitos también pueden tener límites. Revisa tu cuenta.", "Le fournisseur indique un quota épuisé ou un crédit insuffisant. Les modèles gratuits peuvent aussi avoir des limites. Vérifie ton compte fournisseur.", "Der Anbieter meldet ein erschöpftes Kontingent oder unzureichendes Guthaben. Auch kostenlose Modelle können Grenzen haben. Prüfe dein Anbieterkonto.", "Leverantören anger slut på kvoten eller otillräckligt saldo. Även gratis modeller kan ha begränsningar. Kontrollera ditt leverantörskonto."],
    errRateLimit: ["Il provider limita temporaneamente le richieste a questo modello. Attendi e riprova oppure scegli un altro modello nelle API personali.", "The provider is temporarily limiting requests to this model. Wait and retry or choose another model in Personal APIs.", "El proveedor limita temporalmente las solicitudes al modelo. Espera y reintenta o elige otro modelo en tus API personales.", "Le fournisseur limite temporairement les requêtes à ce modèle. Attends puis réessaie, ou choisis un autre modèle dans tes API personnelles.", "Der Anbieter begrenzt Anfragen an dieses Modell vorübergehend. Warte und versuche es erneut oder wähle ein anderes Modell in deinen APIs.", "Leverantören begränsar tillfälligt anrop till modellen. Vänta och försök igen eller välj en annan modell i egna API:er."],
    errPrivacy: ["La richiesta è stata bloccata perché il servizio locale di protezione dei dati non risponde. L’amministratore deve controllare le impostazioni di anonimizzazione.", "The request was blocked because the local data protection service is unavailable. Ask the administrator to check anonymization settings.", "La solicitud se ha bloqueado porque no responde el servicio local de protección de datos. El administrador debe revisar la anonimización.", "La requête a été bloquée car le service local de protection des données ne répond pas. L’administrateur doit vérifier l’anonymisation.", "Die Anfrage wurde blockiert, weil der lokale Datenschutzdienst nicht erreichbar ist. Die Administration muss die Anonymisierung prüfen.", "Anropet blockerades eftersom den lokala dataskyddstjänsten inte svarar. Administratören behöver kontrollera anonymiseringsinställningarna."],
    errInvalidRequest: ["Il provider non accetta questa richiesta con il modello scelto. Controlla che sia un modello per conversazioni e prova un altro modello.", "The provider does not accept this request with the selected model. Check that it is a chat model and try another model.", "El proveedor no acepta esta solicitud con el modelo elegido. Comprueba que sea un modelo de chat y prueba otro.", "Le fournisseur refuse cette requête avec le modèle choisi. Vérifie qu’il s’agit d’un modèle de conversation et essaie un autre modèle.", "Der Anbieter akzeptiert die Anfrage mit diesem Modell nicht. Prüfe, ob es ein Chatmodell ist, und versuche ein anderes.", "Leverantören godtar inte anropet med den valda modellen. Kontrollera att det är en chattmodell och prova en annan."],
    errConnection: ["Non è stato possibile raggiungere il modello personale. Prova la connessione dalla pagina API personali.", "The personal model could not be reached. Test the connection from Personal APIs.", "No se ha podido contactar con el modelo personal. Prueba la conexión desde API personales.", "Le modèle personnel n’a pas pu être joint. Teste la connexion dans API personnelles.", "Das persönliche Modell war nicht erreichbar. Teste die Verbindung unter Eigene APIs.", "Den personliga modellen kunde inte nås. Testa anslutningen under Egna API:er."],
    errConfiguration: ["Controlla la chiave e la configurazione salvate nelle API personali.", "Check the saved key and configuration in Personal APIs.", "Revisa la clave y la configuración guardadas en API personales.", "Vérifie la clé et la configuration enregistrées dans API personnelles.", "Prüfe den gespeicherten Schlüssel und die Konfiguration unter Eigene APIs.", "Kontrollera den sparade nyckeln och inställningarna under Egna API:er."],
    errCounselor: ["Uno dei counselor selezionati non è più disponibile per il tuo account. Aggiorna le associazioni nelle API personali.", "A selected counselor is no longer available to your account. Update the associations in Personal APIs.", "Un counselor seleccionado ya no está disponible para tu cuenta. Actualiza las asociaciones en API personales.", "Un counselor sélectionné n’est plus disponible pour ton compte. Mets à jour les associations dans API personnelles.", "Ein ausgewählter Counselor ist für dein Konto nicht mehr verfügbar. Aktualisiere die Verknüpfungen unter Eigene APIs.", "En vald counselor är inte längre tillgänglig för ditt konto. Uppdatera kopplingarna under Egna API:er."],
    connections: ["Le tue connessioni AI", "Your AI connections", "Tus conexiones de IA", "Tes connexions IA", "Deine KI-Verbindungen", "Dina AI-anslutningar"],
    addConnection: ["Aggiungi connessione", "Add connection", "Añadir conexión", "Ajouter une connexion", "Verbindung hinzufügen", "Lägg till anslutning"],
    connectionsHelp: ["Puoi salvare più chiavi, anche dello stesso provider o di account diversi. Ogni connessione ha un nome, una chiave e un modello.", "Save multiple keys, including keys for the same provider or different accounts. Each connection has a name, key and model.", "Guarda varias claves, incluso del mismo proveedor o de cuentas distintas. Cada conexión tiene un nombre, una clave y un modelo.", "Enregistre plusieurs clés, y compris du même fournisseur ou de comptes différents. Chaque connexion a un nom, une clé et un modèle.", "Speichere mehrere Schlüssel, auch für denselben Anbieter oder verschiedene Konten. Jede Verbindung hat einen Namen, Schlüssel und ein Modell.", "Spara flera nycklar, även från samma leverantör eller olika konton. Varje anslutning har ett namn, en nyckel och en modell."],
    noConnections: ["Aggiungi una connessione per configurare le tue chiavi e i tuoi modelli.", "Add a connection to set up your keys and models.", "Añade una conexión para configurar tus claves y modelos.", "Ajoute une connexion pour configurer tes clés et modèles.", "Füge eine Verbindung hinzu, um deine Schlüssel und Modelle einzurichten.", "Lägg till en anslutning för att ställa in dina nycklar och modeller."],
    connectionName: ["Nome della connessione", "Connection name", "Nombre de la conexión", "Nom de la connexion", "Name der Verbindung", "Anslutningens namn"],
    connectionNameHelp: ["Un nome per riconoscere la chiave e l’account, per esempio «OpenRouter personale» o «OpenAI università».", "A name to identify the key and account, such as “Personal OpenRouter” or “University OpenAI”.", "Un nombre para identificar la clave y la cuenta, como «OpenRouter personal» u «OpenAI universidad».", "Un nom pour identifier la clé et le compte, comme «OpenRouter personnel» ou «OpenAI université».", "Ein Name zum Erkennen des Schlüssels und Kontos, etwa „OpenRouter privat“ oder „OpenAI Universität“.", "Ett namn för att känna igen nyckeln och kontot, till exempel ”Privat OpenRouter” eller ”OpenAI universitet”."],
    saveConnection: ["Salva connessione", "Save connection", "Guardar conexión", "Enregistrer la connexion", "Verbindung speichern", "Spara anslutning"],
    removeConnection: ["Elimina connessione", "Delete connection", "Eliminar conexión", "Supprimer la connexion", "Verbindung löschen", "Ta bort anslutning"],
    confirmConnection: ["Eliminare questa chiave e le associazioni alla connessione? I counselor restano salvati. Le associazioni eliminate torneranno alla scelta predefinita.", "Delete this key and its connection associations? Counselors remain saved. Removed associations return to the default choice.", "¿Eliminar esta clave y sus asociaciones? Los counselors se conservan. Las asociaciones eliminadas vuelven a la opción predeterminada.", "Supprimer cette clé et ses associations ? Les counselors restent enregistrés. Les associations supprimées reviennent au choix par défaut.", "Diesen Schlüssel und seine Verknüpfungen löschen? Counselor bleiben gespeichert. Gelöschte Verknüpfungen verwenden wieder die Standardauswahl.", "Ta bort nyckeln och dess kopplingar? Counselors finns kvar. Borttagna kopplingar återgår till standardvalet."],
    routingHelp: ["Associa una connessione a uno o più counselor. Ciascun counselor mantiene la propria personalità e le istruzioni del percorso, e usa il modello e la chiave della connessione assegnata.", "Link a connection to one or more counselors. Each counselor keeps their personality and the path’s instructions, using the model and key of the assigned connection.", "Asocia una conexión a uno o varios counselors. Cada counselor mantiene su personalidad y las instrucciones del recorrido, y usa el modelo y la clave asignados.", "Associe une connexion à un ou plusieurs counselors. Chacun garde sa personnalité et les instructions du parcours, et utilise le modèle et la clé de la connexion associée.", "Verknüpfe eine Verbindung mit einem oder mehreren Counselorn. Jeder behält seine Persönlichkeit und die Anweisungen des Ablaufs und nutzt Modell und Schlüssel der zugewiesenen Verbindung.", "Koppla en anslutning till en eller flera counselors. Varje counselor behåller sin personlighet och flödets instruktioner och använder den tilldelade anslutningens modell och nyckel."],
    defaultConnection: ["Connessione predefinita", "Default connection", "Conexión predeterminada", "Connexion par défaut", "Standardverbindung", "Standardanslutning"],
    defaultHelp: ["Si applica ai counselor senza un’associazione specifica e alle funzioni senza counselor. Puoi scegliere le API di sistema. Se disattivi le API personali, tutte le nuove richieste usano la configurazione di sistema.", "Applies to counselors without a specific association and features without a counselor. You can choose system APIs. Disabling personal APIs makes all new requests use the system configuration.", "Se aplica a counselors sin una asociación específica y a funciones sin counselor. Puedes elegir las API del sistema. Al desactivar las API personales, todas las solicitudes nuevas usan la configuración del sistema.", "S’applique aux counselors sans association spécifique et aux fonctions sans counselor. Tu peux choisir les API du système. Désactiver les API personnelles fait utiliser le système à toutes les nouvelles requêtes.", "Gilt für Counselor ohne eigene Verknüpfung und Funktionen ohne Counselor. Du kannst System-APIs wählen. Bei deaktivierten eigenen APIs verwenden alle neuen Anfragen die Systemkonfiguration.", "Gäller counselors utan särskild koppling och funktioner utan counselor. Du kan välja systemets API:er. När egna API:er stängs av använder alla nya anrop systemets inställningar."],
    useDefault: ["Usa la scelta predefinita", "Use the default choice", "Usar la opción predeterminada", "Utiliser le choix par défaut", "Standardauswahl verwenden", "Använd standardvalet"],
    saveRouting: ["Salva associazioni e utilizzo", "Save associations and usage", "Guardar asociaciones y uso", "Enregistrer les associations et l’utilisation", "Verknüpfungen und Nutzung speichern", "Spara kopplingar och användning"],
} satisfies Record<string, Localized>;
export const personalAPIText = (lang: Lang, key: keyof typeof texts): string => texts[key][Math.max(0, languages.indexOf(lang))];

const errorKeys = { authentication: "errAuthentication", modelUnavailable: "errModelUnavailable", quota: "errQuota", rateLimit: "errRateLimit", privacy: "errPrivacy", invalidRequest: "errInvalidRequest", connection: "errConnection", configuration: "errConfiguration", counselor: "errCounselor" } as const;
export function personalAPIErrorText(lang: Lang, code: unknown): string | null {
    if (typeof code !== "string" || !code.startsWith("personalAPI.errors.")) return null;
    const key = code.slice("personalAPI.errors.".length);
    if (!Object.prototype.hasOwnProperty.call(errorKeys, key)) return null;
    return personalAPIText(lang, errorKeys[key as keyof typeof errorKeys]);
}

export function chatErrorText(lang: Lang, code: unknown): string | null {
    const personal = personalAPIErrorText(lang, code);
    if (personal) return personal;
    if (code === 'chat.errors.connection') return personalAPIText(lang, 'errChatConnection');
    if (code === 'chat.errors.access') return personalAPIText(lang, 'errChatAccess');
    if (code === 'chat.errors.configuration') return personalAPIText(lang, 'errChatConfiguration');
    return null;
}
