import type { Lang } from './i18n';

const languages: Lang[] = ['it', 'en', 'es', 'fr', 'de', 'sv'];
type Localized = readonly [string, string, string, string, string, string];
const texts = {
    title: ['Protezione dei dati per i modelli esterni', 'Data protection for external models', 'Protección de datos para modelos externos', 'Protection des données pour les modèles externes', 'Datenschutz für externe Modelle', 'Dataskydd för externa modeller'],
    help: ['Scegli come filtrare i dati prima di inviarli ai modelli esterni. Vale anche per API personali e abbonamento ChatGPT.', 'Choose how to filter data before sending it to external models. This also applies to personal APIs and ChatGPT subscriptions.', 'Elige cómo filtrar los datos antes de enviarlos a modelos externos. También se aplica a las API personales y a ChatGPT.', 'Choisis comment filtrer les données avant de les envoyer aux modèles externes. Cela concerne aussi les API personnelles et ChatGPT.', 'Wähle, wie Daten vor dem Versand an externe Modelle gefiltert werden. Dies gilt auch für eigene APIs und ChatGPT-Abonnements.', 'Välj hur data filtreras innan de skickas till externa modeller. Det gäller även egna API:er och ChatGPT-abonnemang.'],
    mode: ['Modalità di protezione', 'Protection mode', 'Modo de protección', 'Mode de protection', 'Schutzmodus', 'Skyddsläge'],
    local: ['Filtro di base + modello locale', 'Basic filter + local model', 'Filtro básico + modelo local', 'Filtre de base + modèle local', 'Basisfilter + lokales Modell', 'Basfilter + lokal modell'],
    basic: ['Solo filtro di base (senza Ollama)', 'Basic filter only (without Ollama)', 'Solo filtro básico (sin Ollama)', 'Filtre de base seul (sans Ollama)', 'Nur Basisfilter (ohne Ollama)', 'Endast basfilter (utan Ollama)'],
    custom: ['Configurazione precedente: scegli una modalità per cambiarla', 'Existing configuration: choose a mode to change it', 'Configuración anterior: elige un modo para cambiarla', 'Configuration précédente : choisis un mode pour la modifier', 'Bisherige Konfiguration: zum Ändern einen Modus wählen', 'Befintlig inställning: välj ett läge för att ändra den'],
    localHelp: ['Il filtro di base rimane attivo; il modello locale aggiunge il riconoscimento di nomi, indirizzi e altri dati nel testo libero. Se non risponde, la richiesta esterna viene bloccata. Modello locale configurato:', 'The basic filter remains active; the local model adds recognition of names, addresses and other data in free text. If it is unavailable, the external request is blocked. Configured local model:', 'El filtro básico sigue activo; el modelo local añade reconocimiento de nombres, direcciones y otros datos en texto libre. Si no responde, se bloquea la solicitud externa. Modelo local configurado:', 'Le filtre de base reste actif ; le modèle local ajoute la reconnaissance des noms, adresses et autres données en texte libre. S’il ne répond pas, la requête externe est bloquée. Modèle local configuré :', 'Der Basisfilter bleibt aktiv; das lokale Modell erkennt zusätzlich Namen, Adressen und weitere Daten im Freitext. Ist es nicht erreichbar, wird die externe Anfrage blockiert. Konfiguriertes lokales Modell:', 'Basfiltret förblir aktivt; den lokala modellen känner även igen namn, adresser och andra uppgifter i fritext. Om den inte svarar blockeras det externa anropet. Inställd lokal modell:'],
    basicHelp: ['Funziona senza modelli locali: filtra email, telefoni e gli identificativi riconosciuti dalle regole automatiche. I dati riconosciuti vengono ripristinati nella risposta.', 'Works without local models: filters email, phone numbers and identifiers recognized by automatic rules. Recognized data is restored in the answer.', 'Funciona sin modelos locales: filtra correos, teléfonos e identificadores reconocidos por reglas automáticas. Los datos reconocidos se restauran en la respuesta.', 'Fonctionne sans modèles locaux : filtre les e-mails, téléphones et identifiants reconnus par les règles automatiques. Les données reconnues sont rétablies dans la réponse.', 'Funktioniert ohne lokale Modelle: filtert E-Mails, Telefonnummern und von automatischen Regeln erkannte Kennungen. Erkannte Daten werden in der Antwort wiederhergestellt.', 'Fungerar utan lokala modeller: filtrerar e-post, telefonnummer och identifierare som de automatiska reglerna känner igen. Uppgifterna återställs i svaret.'],
    limits: ['Il filtro di base non garantisce la rimozione di nomi, indirizzi o tutte le informazioni sanitarie dal testo libero. Per le prove in cloud usa dati fittizi; questa modalità non garantisce l’anonimato.', 'The basic filter does not guarantee removal of names, addresses or all health information from free text. Use fictional data for cloud tests; this mode does not guarantee anonymity.', 'El filtro básico no garantiza eliminar nombres, direcciones ni toda la información sanitaria del texto libre. Usa datos ficticios en pruebas en la nube; este modo no garantiza el anonimato.', 'Le filtre de base ne garantit pas la suppression des noms, adresses ou de toutes les données de santé en texte libre. Utilise des données fictives pour les essais cloud ; ce mode ne garantit pas l’anonymat.', 'Der Basisfilter garantiert nicht die Entfernung von Namen, Adressen oder sämtlichen Gesundheitsdaten aus Freitext. Verwende für Cloud-Tests fiktive Daten; dieser Modus garantiert keine Anonymität.', 'Basfiltret garanterar inte att namn, adresser eller alla hälsouppgifter tas bort ur fritext. Använd påhittade data vid molntester; läget garanterar inte anonymitet.'],
    customHelp: ['La configurazione esistente è conservata. Salvando una delle due modalità attivi il filtro e mantieni il blocco quando il modello locale è richiesto ma non disponibile.', 'The existing configuration is preserved. Saving either mode enables the filter and keeps requests blocked when a required local model is unavailable.', 'Se conserva la configuración existente. Al guardar un modo se activa el filtro y se mantiene el bloqueo si el modelo local requerido no está disponible.', 'La configuration existante est conservée. Enregistrer un mode active le filtre et maintient le blocage si le modèle local requis est indisponible.', 'Die bisherige Konfiguration bleibt erhalten. Das Speichern eines Modus aktiviert den Filter und blockiert Anfragen bei fehlendem erforderlichem lokalen Modell.', 'Den befintliga inställningen bevaras. När ett läge sparas aktiveras filtret och anrop blockeras om en nödvändig lokal modell saknas.'],
    save: ['Salva protezione dei dati', 'Save data protection', 'Guardar protección de datos', 'Enregistrer la protection des données', 'Datenschutz speichern', 'Spara dataskydd'],
    saved: ['Protezione salvata. Le nuove richieste usano questa modalità senza riavviare il server.', 'Protection saved. New requests use this mode without restarting the server.', 'Protección guardada. Las nuevas solicitudes usan este modo sin reiniciar el servidor.', 'Protection enregistrée. Les nouvelles requêtes utilisent ce mode sans redémarrage du serveur.', 'Schutz gespeichert. Neue Anfragen verwenden den Modus ohne Serverneustart.', 'Skyddet har sparats. Nya anrop använder läget utan att servern behöver startas om.'],
    error: ['Non è stato possibile aggiornare la protezione. La modalità precedente resta attiva.', 'Protection could not be updated. The previous mode remains active.', 'No se ha podido actualizar la protección. Sigue activo el modo anterior.', 'La protection n’a pas pu être mise à jour. Le mode précédent reste actif.', 'Der Schutz konnte nicht aktualisiert werden. Der bisherige Modus bleibt aktiv.', 'Skyddet kunde inte uppdateras. Det tidigare läget förblir aktivt.'],
    loading: ['Caricamento della protezione dei dati…', 'Loading data protection…', 'Cargando protección de datos…', 'Chargement de la protection des données…', 'Datenschutz wird geladen…', 'Läser in dataskydd…'],
    retry: ['Riprova', 'Retry', 'Reintentar', 'Réessayer', 'Erneut versuchen', 'Försök igen'],
    dirty: ['Le modifiche alla protezione dei dati non sono salvate. Uscire dalla pagina?', 'Data protection changes are not saved. Leave this page?', 'Los cambios de protección no están guardados. ¿Salir de la página?', 'Les modifications de protection ne sont pas enregistrées. Quitter la page ?', 'Die Änderungen am Datenschutz sind nicht gespeichert. Seite verlassen?', 'Ändringarna av dataskyddet är inte sparade. Lämna sidan?'],
    guide: ['Se una richiesta è bloccata perché il servizio locale di protezione non risponde, l’amministratore può ripristinarlo oppure scegliere il filtro di base senza Ollama da Configurazione → Generale. Questa scelta va salvata ed è limitata: non garantisce anonimato. Poi puoi riprovare la connessione e lo step.', 'If a request is blocked because the local protection service is unavailable, the administrator can restore it or choose the basic filter without Ollama under Configuration → General. This choice must be saved and has limits: it does not guarantee anonymity. Then retry the connection and the step.', 'Si una solicitud se bloquea porque no responde el servicio local de protección, el administrador puede restaurarlo o elegir el filtro básico sin Ollama en Configuración → General. Hay que guardar esta elección y tiene límites: no garantiza anonimato. Después reintenta la conexión y el paso.', 'Si une requête est bloquée car le service local de protection ne répond pas, l’administrateur peut le rétablir ou choisir le filtre de base sans Ollama dans Configuration → Général. Ce choix doit être enregistré et reste limité : il ne garantit pas l’anonymat. Réessaie ensuite la connexion et l’étape.', 'Wird eine Anfrage wegen eines fehlenden lokalen Schutzdienstes blockiert, kann die Administration ihn wiederherstellen oder unter Konfiguration → Allgemein den Basisfilter ohne Ollama wählen. Die Wahl muss gespeichert werden und ist begrenzt: Sie garantiert keine Anonymität. Versuche danach Verbindung und Schritt erneut.', 'Om ett anrop blockeras för att den lokala skyddstjänsten inte svarar kan administratören återställa den eller välja basfiltret utan Ollama under Konfiguration → Allmänt. Valet måste sparas och har begränsningar: det garanterar inte anonymitet. Försök sedan med anslutningen och steget igen.'],
} satisfies Record<string, Localized>;
export const externalPrivacyText = (lang: Lang, key: keyof typeof texts): string => texts[key][Math.max(0, languages.indexOf(lang))];
