import type { Lang } from './i18n';

const languages: readonly Lang[] = ['it', 'en', 'es', 'fr', 'de', 'sv'];
export const credentialTexts = {
    // Teacher institute editor
    setCredentials: ['Inserisci credenziali esterne', 'Enter external credentials', 'Introducir credenciales externas', 'Saisir les identifiants externes', 'Externe Zugangsdaten eingeben', 'Ange externa inloggningsuppgifter'],
    replaceCredentials: ['Sostituisci credenziali esterne', 'Replace external credentials', 'Sustituir credenciales externas', 'Remplacer les identifiants externes', 'Externe Zugangsdaten ersetzen', 'Ersätt externa inloggningsuppgifter'],
    code: ['Codice istituto (rilasciato da competenzestrategiche.it)', 'Institution code (issued by competenzestrategiche.it)', 'Código del instituto (emitido por competenzestrategiche.it)', 'Code de l’établissement (délivré par competenzestrategiche.it)', 'Einrichtungscode (von competenzestrategiche.it ausgestellt)', 'Lärosätets kod (utfärdad av competenzestrategiche.it)'],
    password: ['Password istituto', 'Institution password', 'Contraseña del instituto', 'Mot de passe de l’établissement', 'Passwort der Einrichtung', 'Lärosätets lösenord'],
    codeLabel: ['Codice', 'Code', 'Código', 'Code', 'Code', 'Kod'],
    writeOnly: ['La password si può solo scrivere: CounselorBot salva soltanto un verificatore e non può mostrarla di nuovo. Consegna le credenziali agli studenti separatamente. Il controllo avviene solo in CounselorBot: nulla viene verificato su competenzestrategiche.it.', 'The password is write-only: CounselorBot stores only a verifier and can never show it again. Give students the login separately. Entries are checked only inside CounselorBot; nothing is verified on competenzestrategiche.it.', 'La contraseña solo se puede escribir: CounselorBot guarda únicamente un verificador y no puede volver a mostrarla. Entrega las credenciales a los estudiantes por separado. La comprobación es solo local: no se verifica nada en competenzestrategiche.it.', 'Le mot de passe est en écriture seule : CounselorBot n’enregistre qu’un vérificateur et ne peut jamais le réafficher. Transmettez les identifiants aux élèves séparément. Le contrôle est uniquement local : rien n’est vérifié sur competenzestrategiche.it.', 'Das Passwort kann nur geschrieben werden: CounselorBot speichert nur einen Prüfwert und kann es nie wieder anzeigen. Geben Sie die Zugangsdaten den Lernenden separat. Geprüft wird nur in CounselorBot, nicht bei competenzestrategiche.it.', 'Lösenordet kan bara skrivas: CounselorBot sparar endast en verifierare och kan aldrig visa det igen. Ge eleverna inloggningen separat. Kontrollen sker bara i CounselorBot; inget verifieras på competenzestrategiche.it.'],
    saveCredentials: ['Salva credenziali', 'Save credentials', 'Guardar credenciales', 'Enregistrer les identifiants', 'Zugangsdaten speichern', 'Spara inloggningsuppgifter'],
    invalidCode: ['Usa solo lettere, cifre e trattini (massimo 50).', 'Use letters, digits and hyphens only (max 50).', 'Usa solo letras, cifras y guiones (máximo 50).', 'Utilisez uniquement lettres, chiffres et tirets (50 max.).', 'Nur Buchstaben, Ziffern und Bindestriche (max. 50).', 'Använd bara bokstäver, siffror och bindestreck (högst 50).'],
    invalidPassword: ['Inserisci la password esattamente come rilasciata (massimo 72 byte).', 'Enter the password exactly as issued (max 72 bytes).', 'Introduce la contraseña tal como fue emitida (máximo 72 bytes).', 'Saisissez le mot de passe tel qu’il a été délivré (72 octets max.).', 'Passwort genau wie ausgestellt eingeben (max. 72 Byte).', 'Ange lösenordet exakt som det utfärdades (högst 72 byte).'],
    codeConflict: ['Un altro istituto usa già questo codice. Controlla il codice o contatta l’amministratore.', 'Another institute already uses this code. Check the code or contact the administrator.', 'Otro instituto ya usa este código. Revisa el código o contacta con el administrador.', 'Un autre établissement utilise déjà ce code. Vérifiez-le ou contactez l’administrateur.', 'Eine andere Einrichtung verwendet diesen Code bereits. Prüfen Sie ihn oder wenden Sie sich an die Administration.', 'Ett annat lärosäte använder redan koden. Kontrollera koden eller kontakta administratören.'],
    conflict: ['L’istituto è stato modificato altrove. Ricarica: i dati inseriti restano qui.', 'The institute changed elsewhere. Reload; your entries stay here.', 'El instituto cambió en otro lugar. Recarga; tus datos se conservan aquí.', 'L’établissement a été modifié ailleurs. Rechargez ; vos saisies restent ici.', 'Die Einrichtung wurde anderswo geändert. Neu laden; Ihre Eingaben bleiben erhalten.', 'Lärosätet ändrades någon annanstans. Läs in igen; dina uppgifter finns kvar här.'],
    error: ['Salvataggio delle credenziali non riuscito. Riprova.', 'Could not save the credentials. Try again.', 'No se pudieron guardar las credenciales. Inténtalo de nuevo.', 'Impossible d’enregistrer les identifiants. Réessayez.', 'Zugangsdaten konnten nicht gespeichert werden. Erneut versuchen.', 'Det gick inte att spara inloggningsuppgifterna. Försök igen.'],
    // Administration plan editor
    planInstitute: ['Istituto', 'Institute', 'Instituto', 'Établissement', 'Einrichtung', 'Lärosäte'],
    noInstitute: ['Nessun istituto (solo ricerca, senza verifica)', 'No institute (research only, no verification)', 'Sin instituto (solo investigación, sin verificación)', 'Aucun établissement (recherche seule, sans vérification)', 'Keine Einrichtung (nur Forschung, ohne Prüfung)', 'Inget lärosäte (endast forskning, utan verifiering)'],
    planInstituteHelp: ['Le credenziali appartengono all’istituto. Per una somministrazione d’istituto gli studenti inseriscono codice e password dell’istituto prima che i risultati vengano salvati.', 'Credentials belong to the institute. In an institute administration, students enter the institute code and password before results are saved.', 'Las credenciales pertenecen al instituto. En una administración del instituto, los estudiantes introducen su código y contraseña antes de guardar los resultados.', 'Les identifiants appartiennent à l’établissement. Pour une passation d’établissement, les élèves saisissent son code et son mot de passe avant l’enregistrement des résultats.', 'Die Zugangsdaten gehören der Einrichtung. Bei einer Einrichtungsdurchführung geben Lernende Code und Passwort ein, bevor Ergebnisse gespeichert werden.', 'Inloggningsuppgifterna tillhör lärosätet. Vid en administrering för lärosätet anger eleverna dess kod och lösenord innan resultaten sparas.'],
    credentialsMissing: ['credenziali mancanti', 'credentials missing', 'faltan credenciales', 'identifiants manquants', 'Zugangsdaten fehlen', 'inloggningsuppgifter saknas'],
    needsReconciliation: ['Da riconciliare', 'Needs reconciliation', 'Pendiente de conciliar', 'À rapprocher', 'Abgleich erforderlich', 'Behöver stämmas av'],
    reason_institution_not_found: ['Il codice del piano non corrisponde a nessun istituto.', 'The plan code matches no institute.', 'El código del plan no coincide con ningún instituto.', 'Le code du plan ne correspond à aucun établissement.', 'Der Plancode passt zu keiner Einrichtung.', 'Planens kod matchar inget lärosäte.'],
    reason_ambiguous_institution: ['Il codice del piano corrisponde a più istituti.', 'The plan code matches several institutes.', 'El código del plan coincide con varios institutos.', 'Le code du plan correspond à plusieurs établissements.', 'Der Plancode passt zu mehreren Einrichtungen.', 'Planens kod matchar flera lärosäten.'],
    reason_institution_inactive: ['L’istituto corrispondente non è attivo.', 'The matching institute is inactive.', 'El instituto correspondiente no está activo.', 'L’établissement correspondant est inactif.', 'Die passende Einrichtung ist inaktiv.', 'Det matchande lärosätet är inaktivt.'],
    reason_class_institution_mismatch: ['La classe appartiene a un istituto diverso.', 'The class belongs to a different institute.', 'La clase pertenece a otro instituto.', 'La classe appartient à un autre établissement.', 'Die Klasse gehört zu einer anderen Einrichtung.', 'Klassen tillhör ett annat lärosäte.'],
    reason_credential_conflict: ['La vecchia password del piano non coincide con quella dell’istituto.', 'The plan’s old password differs from the institute’s.', 'La antigua contraseña del plan difiere de la del instituto.', 'L’ancien mot de passe du plan diffère de celui de l’établissement.', 'Das alte Planpasswort weicht von dem der Einrichtung ab.', 'Planens gamla lösenord skiljer sig från lärosätets.'],
    reason_credential_reentry_required: ['Password precedenti in conflitto: un docente dell’istituto deve reinserire le credenziali.', 'Conflicting previous passwords: an institute teacher must re-enter the credentials.', 'Contraseñas anteriores en conflicto: un docente del instituto debe volver a introducirlas.', 'Anciens mots de passe contradictoires : un enseignant de l’établissement doit ressaisir les identifiants.', 'Widersprüchliche alte Passwörter: Eine Lehrkraft der Einrichtung muss die Zugangsdaten neu eingeben.', 'Motstridiga tidigare lösenord: en lärare vid lärosätet måste ange uppgifterna igen.'],
    legacyCode: ['Codice precedente', 'Previous code', 'Código anterior', 'Ancien code', 'Bisheriger Code', 'Tidigare kod'],
    confirmReconciliation: ['Confermo questa scelta di istituto (risolve la riconciliazione)', 'Confirm this institute choice (resolves reconciliation)', 'Confirmo esta elección de instituto (resuelve la conciliación)', 'Je confirme ce choix d’établissement (résout le rapprochement)', 'Diese Einrichtung bestätigen (löst den Abgleich)', 'Bekräfta valet av lärosäte (löser avstämningen)'],
    revisionConflict: ['Il piano è stato modificato altrove. Ricarica l’elenco: la bozza resta nel modulo.', 'This plan changed elsewhere. Reload the list; your draft stays in the form.', 'El plan cambió en otro lugar. Recarga la lista; el borrador se conserva en el formulario.', 'Le plan a été modifié ailleurs. Rechargez la liste ; le brouillon reste dans le formulaire.', 'Der Plan wurde anderswo geändert. Liste neu laden; der Entwurf bleibt im Formular.', 'Planen ändrades någon annanstans. Läs in listan igen; utkastet finns kvar i formuläret.'],
    linkForbidden: ['Puoi collegare solo gli istituti di cui fai parte.', 'You can link only institutes you belong to.', 'Solo puedes vincular institutos de los que formas parte.', 'Vous ne pouvez lier que vos établissements.', 'Sie können nur Einrichtungen verknüpfen, denen Sie angehören.', 'Du kan bara koppla lärosäten som du tillhör.'],
    institutesLoadError: ['Impossibile caricare gli istituti.', 'Could not load institutes.', 'No se pudieron cargar los institutos.', 'Impossible de charger les établissements.', 'Einrichtungen konnten nicht geladen werden.', 'Det gick inte att läsa in lärosätena.'],
    // Student verification in the questionnaire runner
    verifyTitle: ['Verifica dell’istituto', 'Institute verification', 'Verificación del instituto', 'Vérification de l’établissement', 'Prüfung der Einrichtung', 'Verifiering av lärosäte'],
    verifyIntro: ['Questa somministrazione appartiene a {institute}. Inserisci codice e password dell’istituto forniti dal docente: le risposte restano salvate in questa pagina.', 'This administration belongs to {institute}. Enter the institute code and password provided by your teacher; your answers stay on this page.', 'Esta administración pertenece a {institute}. Introduce el código y la contraseña del instituto que te dio tu docente; tus respuestas se conservan en esta página.', 'Cette passation appartient à {institute}. Saisis le code et le mot de passe fournis par ton enseignant ; tes réponses restent sur cette page.', 'Diese Durchführung gehört zu {institute}. Gib Code und Passwort ein, die du von deiner Lehrkraft erhalten hast; deine Antworten bleiben auf dieser Seite.', 'Den här administreringen tillhör {institute}. Ange koden och lösenordet från din lärare; dina svar finns kvar på sidan.'],
    verifyNotice: ['Il controllo avviene solo in CounselorBot, sulle credenziali salvate dall’istituto.', 'Checked only inside CounselorBot, against the credentials saved by the institute.', 'Se comprueba solo en CounselorBot, con las credenciales guardadas por el instituto.', 'Vérifié uniquement dans CounselorBot, avec les identifiants enregistrés par l’établissement.', 'Geprüft wird nur in CounselorBot, mit den von der Einrichtung gespeicherten Zugangsdaten.', 'Kontrolleras bara i CounselorBot, mot de uppgifter som lärosätet har sparat.'],
    verifyAction: ['Verifica e salva', 'Verify and save', 'Verificar y guardar', 'Vérifier et enregistrer', 'Prüfen und speichern', 'Verifiera och spara'],
    verifyFailed: ['Codice o password non validi.', 'Code or password not valid.', 'Código o contraseña no válidos.', 'Code ou mot de passe non valide.', 'Code oder Passwort ungültig.', 'Ogiltig kod eller ogiltigt lösenord.'],
    verifyThrottled: ['Troppi tentativi. Attendi qualche minuto e riprova.', 'Too many attempts. Wait a few minutes and try again.', 'Demasiados intentos. Espera unos minutos y vuelve a intentarlo.', 'Trop de tentatives. Patiente quelques minutes puis réessaie.', 'Zu viele Versuche. Warte einige Minuten und versuche es erneut.', 'För många försök. Vänta några minuter och försök igen.'],
    verifyUnavailable: ['Questa somministrazione non può ricevere risultati in questo momento. Chiedi al docente.', 'This administration cannot accept results right now. Ask your teacher.', 'Esta administración no puede recibir resultados ahora. Pregunta a tu docente.', 'Cette passation ne peut pas recevoir de résultats pour le moment. Demande à ton enseignant.', 'Diese Durchführung kann derzeit keine Ergebnisse annehmen. Frag deine Lehrkraft.', 'Den här administreringen kan inte ta emot resultat just nu. Fråga din lärare.'],
    verifyError: ['Verifica non riuscita. Riprova.', 'Verification failed. Try again.', 'La verificación falló. Inténtalo de nuevo.', 'La vérification a échoué. Réessaie.', 'Prüfung fehlgeschlagen. Erneut versuchen.', 'Verifieringen misslyckades. Försök igen.'],
} satisfies Record<string, readonly [string, string, string, string, string, string]>;
export type CredentialTextKey = keyof typeof credentialTexts;
export const credentialText = (lang: Lang, key: CredentialTextKey, values: Record<string, string> = {}) =>
    Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, value),
        credentialTexts[key][Math.max(0, languages.indexOf(lang))] as string);
