export type AdministrationInstrument = 'QSA' | 'QSAr' | 'ZTPI' | 'QPCS' | 'QPCC' | 'QAP';
export type AdministrationLocale = 'en' | 'es' | 'sv';

export const INSTRUMENT_NAMES: Record<AdministrationInstrument, { en: string; es: string; sv: string }> = {
    QSA: { en: 'Learning Strategies Questionnaire', es: 'Cuestionario sobre Estrategias de Aprendizaje', sv: 'Frågeformulär om inlärningsstrategier' },
    QSAr: { en: 'Learning Strategies Questionnaire - Short Form', es: 'Cuestionario sobre Estrategias de Aprendizaje - versión reducida', sv: 'Frågeformulär om inlärningsstrategier - kortversion' },
    ZTPI: { en: 'Zimbardo Time Perspective Inventory', es: 'Inventario de Perspectiva Temporal de Zimbardo', sv: 'Zimbardos tidsperspektivinventarium' },
    QPCS: { en: 'Perceived Strategic Competences Questionnaire', es: 'Cuestionario de Competencias Estratégicas Percibidas', sv: 'Frågeformulär om upplevda strategiska kompetenser' },
    QPCC: { en: 'Perceived Competences and Beliefs Questionnaire', es: 'Cuestionario de Competencias y Creencias Percibidas', sv: 'Frågeformulär om upplevda kompetenser och föreställningar' },
    QAP: { en: 'Career Adapt-Abilities Scale', es: 'Escala de Adaptabilidad de Carrera', sv: 'Skala för anpassningsbarhet i karriären' },
};

export const INSTRUMENT_ITEM_COUNTS: Record<AdministrationInstrument, number> = {
    QSA: 100,
    QSAr: 46,
    ZTPI: 56,
    QPCS: 25,
    QPCC: 25,
    QAP: 24,
};

export interface AdministrationCopy {
    title: string;
    shortName: string;
    testBadge: string;
    warningTitle: string;
    warningBody: string;
    instructions: string;
    privacyNote: string;
    scale: [string, string, string, string];
    items: string[];
    progress: string;
    missingAnswers: string;
    submit: string;
    submittedTitle: string;
    submittedBody: string;
    profileMethod: string;
    dimensionTitles: Record<string, string>;
    rawAverage: string;
    restart: string;
    back: string;
    startChat: string;
    stanineScore: string;
}

const QSA_EN: string[] = [
    'After a lesson, I carefully review my notes in order to explore and remember the ideas better.',
    'When I read, I reflect on the subject and try to understand clearly what the text explains.',
    'Sometimes I do poorly on an assignment because I cannot understand exactly what I am expected to do.',
    'When I receive a poor mark, I become discouraged.',
    'When I do well at school, I think it is because I studied hard.',
    'When I prepare for an exam or an oral assessment, I think about the questions the teacher may ask me.',
    'When I learn new words or ideas, I try to imagine a situation in which they could be applied.',
    'When I study, I get lost in details and cannot identify the main points.',
    'I feel very uncomfortable during a written assignment or oral assessment even when I am well prepared.',
    'When an oral assessment goes well, I think I was lucky that the teacher asked me something I knew.',
    'I check whether I have understood correctly what the teacher said during the lesson.',
    'To pay closer attention, I take notes during lessons.',
    'I find that studying with a classmate is a waste of time.',
    'When I begin a classroom assignment, I am confident that I can do well.',
    'When I do not succeed in an assignment or oral assessment, I think the reason is that I did not study seriously.',
    'I sometimes think that I am capable of completing my study commitments successfully.',
    'I try to find relationships between what I am learning and what I already know.',
    'Outlines, diagrams or summary tables help me understand better what a text presents.',
    'During an oral assessment, fear of making a mistake bothers me so much that I perform worse.',
    'When an oral assessment goes well, I think I am really intelligent.',
    'While studying, I ask myself questions or do exercises to check whether I have understood properly.',
    'I try to find links between what I am studying and my experiences.',
    'I panic when I know that I must sit an important written exam.',
    'When I do not succeed in an assignment or oral assessment, I think I was asked something too difficult.',
    'When I have finished studying, I imagine the questions the teacher might ask and try to answer them.',
    'I try to see how what I study could apply to my everyday life.',
    'When I read a text, I mark the most important points in it.',
    'When I have to face an oral assessment or written assignment, I am so nervous that I cannot express myself as well as I could.',
    'When an oral assessment goes well, I think it is because I studied with a great deal of effort.',
    'I find discussing or working in a group useful and stimulating.',
    'I try to establish links between the different ideas in the text I am studying.',
    'I find it difficult to summarise what I have heard at school or read in a book.',
    'During a classroom assignment or an oral assessment, doubts and uncertainty about my ability to do well come into my mind.',
    'I organise my study according to the time I have available.',
    'Before studying a subject, I try to clarify what the teacher expects of me.',
    'When I learn a new concept, I try to find an example to which it could apply.',
    'I create outlines, diagrams or summary tables to summarise what I study.',
    'My heart beats strongly when I have to take an important exam or oral assessment.',
    'When I do well at school, I think it is because I am a truly capable person.',
    'During an oral assessment, I sometimes realise that I studied the wrong subject.',
    'When I learn a new concept, I ask myself whether there are cases in which it cannot be applied.',
    'I enjoy having to do work that challenges me.',
    'I memorise rules, technical terms or formulae even without understanding them.',
    'I make drawings and sketches that help me understand what I am studying.',
    'I become nervous straight away when faced with a question or problem that I do not immediately understand.',
    'I cannot stay focused on my work for more than fifteen minutes.',
    'I sometimes think that failures at school depend fundamentally on people not being capable.',
    'While studying or listening to a lesson, links with other subjects I have already studied come to mind.',
    'I go to school having completed all homework and studied all lessons.',
    'When I take part in group work, I feel that I understand things better.',
    'When I do well, I think it is because the task was easy.',
    'I sometimes find that a study topic is more difficult than I expected.',
    'When I do not feel able to complete it, I sometimes leave a piece of work unfinished.',
    'I make a serious effort to achieve a good mark even when I do not like the subject.',
    'If for some reason I cannot prepare my lessons, I feel uneasy.',
    'I remember better when studying if I can use outlines, diagrams or tables.',
    'I prefer studying a lesson on my own rather than with someone else\'s help.',
    'When faced with a demanding task, I feel encouraged to try harder.',
    'Even if I work very hard, I sometimes think that I cannot become more intelligent anyway.',
    'When I begin studying, I try to estimate how much time I need to learn a subject.',
    'If I find that a subject requires time and effort, I do not even consider it.',
    'When for some reason I fall behind in schoolwork, I try to catch up without the teacher making me do so.',
    'When I do a boring task, I think about its less negative aspects and the satisfaction I will feel when I finish.',
    'I sometimes think that succeeding at school depends on the intellectual ability a person has.',
    'I finish my homework in good time.',
    'If I cannot prepare well for school, I feel uncomfortable.',
    'Even if a task is boring, I continue doing it until I have finished it.',
    'I think that the ability to succeed at school depends on the effort each person puts into careful study.',
    'At home I do not study subjects according to a clear plan, but according to the urgency of upcoming assessments.',
    'When I have decided to do something, I finish it even if it requires effort.',
    'I find it of little use to rely on drawings, diagrams or summary tables in the text when reviewing lessons.',
    'I feel confident that I can obtain good marks.',
    'I think that a person\'s intelligence can improve over time if they make a serious effort.',
    'I feel that I learn better when I can compare ideas with my classmates.',
    'As soon as I encounter the first difficulties, I abandon a task I have only just started.',
    'When something goes badly, I think it depends more on external circumstances than on my ability or lack of effort.',
    'If I realise that I no longer have enough time to finish my work, I panic.',
    'I sometimes think that a person\'s intelligence is something that cannot really change: it is a natural gift.',
    'Problems at home or with friends cause me to neglect my schoolwork.',
    'If I fail, I feel inclined to try again.',
    'At the start of studying, I check what I need to do.',
    'When I think about the things I need to learn, I sometimes regard them as too difficult.',
    'I think that a person\'s ability depends on the persistence and effort they put into studying.',
    'When my teacher explains something, I find myself thinking about other things and do not follow the explanation.',
    'When reading, I use my imagination to reconstruct the situations, characters or events being described.',
    'I think that in study, as in work, it is important to learn to work together.',
    'If I am in a bad mood, I find it difficult to concentrate on studying.',
    'When I do well in an oral assessment, I think the teacher was understanding and asked me easy questions.',
    'While studying, I distract myself by daydreaming and making all kinds of plans.',
    'I understand better if the teacher uses sketches and diagrams on the board while explaining.',
    'At home and outside home, I sometimes enjoy talking about the things I do at school.',
    'If I have an emotional problem caused by difficult relationships with others or with my parents, I cannot apply myself to studying.',
    'If I am prepared, I am confident that I will do well in an assignment or oral assessment.',
    'I sometimes think that with serious effort a person can also develop their intelligence.',
    'When I encounter a difficulty, I try to overcome it by increasing my effort and concentration.',
    'I avoid asking questions because I think I would bother the teacher.',
    'When I am questioned unexpectedly, I freeze and can no longer speak.',
    'I find it difficult to tell whether a concept or topic is unclear to me.',
    'When I take part in group work, I feel that I am wasting time.',
    'To remember what I study better, I try to link the different ideas together.',
];

const QSA_SV: string[] = [
    'Efter en lektion går jag noggrant igenom mina anteckningar för att fördjupa och bättre minnas idéerna.',
    'När jag läser reflekterar jag över ämnet och försöker förstå ordentligt vad texten beskriver.',
    'Ibland går det dåligt på en uppgift eftersom jag inte kan förstå exakt vad jag ska göra.',
    'När jag får ett dåligt betyg blir jag nedstämd.',
    'När det går bra för mig i skolan tänker jag att det beror på att jag har studerat mycket.',
    'När jag förbereder mig inför ett prov eller ett muntligt förhör tänker jag på de frågor läraren kan ställa.',
    'När jag lär mig nya ord eller idéer försöker jag föreställa mig en situation där de kan användas.',
    'När jag studerar fastnar jag i detaljer och kan inte hitta det viktigaste.',
    'Jag känner mig mycket obekväm under en skriftlig uppgift eller ett muntligt förhör även när jag är väl förberedd.',
    'När ett muntligt förhör går bra tänker jag att jag hade tur som fick en fråga jag kunde.',
    'Jag kontrollerar om jag har förstått rätt vad läraren sade under lektionen.',
    'För att vara mer uppmärksam antecknar jag under lektionerna.',
    'Jag tycker att det är slöseri med tid att studera med en klasskamrat.',
    'När jag börjar med en uppgift i klassrummet är jag övertygad om att jag kan göra bra ifrån mig.',
    'När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att orsaken är att jag inte studerade tillräckligt seriöst.',
    'Jag tänker ibland att jag klarar av att genomföra mina studieåtaganden med framgång.',
    'Jag försöker hitta samband mellan det jag lär mig och det jag redan vet.',
    'Dispositioner, diagram eller sammanfattande tabeller hjälper mig att bättre förstå det som står i texten.',
    'Under ett muntligt förhör stör rädslan för att göra fel mig så mycket att det går sämre.',
    'När ett muntligt förhör går bra tänker jag att jag verkligen är intelligent.',
    'När jag studerar ställer jag frågor till mig själv eller gör övningar för att kontrollera att jag har förstått ordentligt.',
    'Jag försöker hitta kopplingar mellan det jag studerar och mina egna erfarenheter.',
    'Jag grips av panik när jag vet att jag ska göra ett viktigt skriftligt prov.',
    'När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att jag fick något som var för svårt.',
    'När jag har studerat klart föreställer jag mig vilka frågor läraren kan ställa och försöker besvara dem.',
    'Jag försöker se hur det jag studerar skulle kunna användas i mitt vardagsliv.',
    'När jag läser en text markerar jag det viktigaste i texten.',
    'När jag ska göra ett muntligt förhör eller en skriftlig uppgift är jag så nervös att jag inte kan uttrycka mig så bra som jag skulle kunna.',
    'När ett muntligt förhör går bra tänker jag att det beror på att jag studerade mycket flitigt.',
    'Jag tycker att det är användbart och stimulerande att diskutera eller arbeta i grupp.',
    'Jag försöker skapa samband mellan de olika idéerna i texten jag studerar.',
    'Jag har svårt att sammanfatta det jag har hört i skolan eller läst i en bok.',
    'Under en uppgift i klassrummet eller ett muntligt förhör får jag tvivel på min förmåga att lyckas.',
    'Jag organiserar mina studier utifrån den tid jag har till förfogande.',
    'Innan jag studerar ett ämne försöker jag klargöra vad läraren förväntar sig av mig.',
    'När jag lär mig ett nytt begrepp försöker jag hitta ett exempel där det kan användas.',
    'Jag gör dispositioner, diagram eller sammanfattande tabeller för att sammanfatta det jag studerar.',
    'Mitt hjärta slår hårt när jag ska göra ett viktigt prov eller muntligt förhör.',
    'När det går bra för mig i skolan tänker jag att det beror på att jag är en verkligt kompetent person.',
    'Under ett muntligt förhör händer det att jag inser att jag har studerat fel ämne.',
    'När jag lär mig ett nytt begrepp frågar jag mig om det finns fall där det inte kan användas.',
    'Jag tycker om att behöva göra ett arbete som utmanar mig.',
    'Jag lär mig regler, facktermer eller formler utantill även utan att förstå dem.',
    'Jag gör teckningar och skisser som hjälper mig att förstå det jag studerar.',
    'Jag blir genast nervös inför en fråga eller ett problem som jag inte förstår direkt.',
    'Jag kan inte hålla koncentrationen på arbetet i mer än en kvart.',
    'Jag tänker ibland att misslyckanden i skolan i grunden beror på att personer inte har förmågan.',
    'När jag studerar eller lyssnar på en lektion kommer jag att tänka på samband med andra ämnen jag redan har studerat.',
    'Jag går till skolan efter att ha gjort alla läxor och studerat alla lektioner.',
    'När jag deltar i grupparbete upplever jag att jag förstår saker bättre.',
    'När jag lyckas bra tänker jag att det beror på att arbetet var lätt.',
    'Ibland tycker jag att ett studieområde är svårare än jag hade väntat mig.',
    'När jag inte känner mig kapabel att slutföra ett arbete händer det att jag lämnar det halvfärdigt.',
    'Jag anstränger mig seriöst för att få ett bra betyg även när jag inte tycker om ämnet.',
    'Om jag av någon anledning inte kan förbereda lektionerna känner jag mig orolig.',
    'Jag minns bättre när jag studerar om jag kan använda dispositioner, diagram eller tabeller.',
    'Jag föredrar att studera lektionen ensam framför att få hjälp av andra.',
    'Inför en krävande uppgift känner jag mig stimulerad att anstränga mig mer.',
    'Även om jag anstränger mig mycket tänker jag ibland att jag ändå inte kan bli mer intelligent.',
    'När jag ska börja studera försöker jag förutse hur mycket tid jag behöver för att lära mig ett ämne.',
    'Om jag märker att ett ämne kräver tid och ansträngning överväger jag det inte ens.',
    'Om jag av någon anledning kommer efter med skolarbetet försöker jag ta igen det utan att läraren tvingar mig.',
    'När jag utför en tråkig uppgift tänker jag på dess mindre negativa sidor och på tillfredsställelsen när jag blir klar.',
    'Jag tänker ibland att förmågan att lyckas i skolan beror på den intelligens en person har.',
    'Jag gör klart mina läxor i god tid.',
    'Om jag inte kan förbereda mig väl inför skolan känner jag mig obekväm.',
    'Även om en uppgift är tråkig fortsätter jag tills jag har gjort klart den.',
    'Jag tänker att förmågan att lyckas i skolan beror på den ansträngning var och en lägger på noggranna studier.',
    'Hemma studerar jag inte ämnena efter en tydlig plan utan efter hur nära förestående förhör är.',
    'När jag har bestämt mig för att göra något slutför jag det även om det kräver ansträngning.',
    'När jag repeterar lektioner tycker jag att det är till liten nytta att använda teckningar, diagram eller sammanfattande tabeller i texten.',
    'Jag känner mig säker på att jag kan få bra betyg.',
    'Jag tänker att en persons intelligens kan förbättras med tiden om personen anstränger sig seriöst.',
    'Jag upplever att jag lär mig bättre när jag kan jämföra mina tankar med klasskamraternas.',
    'Så snart jag möter de första svårigheterna överger jag ett arbete som jag just har påbörjat.',
    'När något går dåligt tänker jag att det beror mer på yttre omständigheter än på min förmåga eller bristande ansträngning.',
    'Om jag märker att jag inte längre har tid att avsluta arbetet grips jag av panik.',
    'Jag tänker ibland att en persons intelligens är något som egentligen inte går att förändra: den är en naturgåva.',
    'Problem hemma eller med vänner gör att jag försummar mitt skolarbete.',
    'Om jag misslyckas känner jag mig benägen att försöka igen.',
    'När jag börjar studera kontrollerar jag vad jag behöver göra.',
    'När jag tänker på det jag behöver lära mig händer det att jag ser det som alltför svårt.',
    'Jag tänker att en persons förmåga beror på den uthållighet och ansträngning personen lägger på studierna.',
    'När min lärare förklarar något börjar jag tänka på annat och följer inte med i förklaringen.',
    'När jag läser återskapar jag med min fantasi de situationer, personer eller händelser som skildras.',
    'Jag tänker att det i studier, liksom i arbete, är viktigt att lära sig arbeta tillsammans.',
    'Om jag är på dåligt humör har jag svårt att koncentrera mig på studierna.',
    'När ett muntligt förhör går bra tänker jag att läraren var förstående och ställde lätta frågor.',
    'När jag studerar distraheras jag av dagdrömmar, projekt och planer av alla slag.',
    'Jag förstår bättre om läraren använder skisser och diagram på tavlan när hen förklarar.',
    'Det händer att jag både hemma och utanför hemmet gärna talar om det jag gör i skolan.',
    'Om jag har ett känslomässigt problem på grund av dåliga relationer med andra eller med mina föräldrar kan jag inte ägna mig åt studierna.',
    'Om jag är förberedd är jag säker på att jag klarar en uppgift eller ett muntligt förhör bra.',
    'Jag tänker ibland att man genom seriös ansträngning också kan utveckla sin intelligens.',
    'När jag stöter på en svårighet försöker jag övervinna den genom att öka min ansträngning och koncentration.',
    'Jag undviker att ställa frågor eftersom jag tror att jag stör läraren.',
    'När jag får en oväntad fråga låser jag mig och kan inte längre prata.',
    'Jag har svårt att avgöra om ett begrepp eller ett ämne är oklart för mig.',
    'När jag deltar i grupparbete får jag intrycket att jag slösar bort tid.',
    'För att bättre minnas det jag studerar försöker jag koppla samman de olika idéerna.',
];

const QSAR_EN: string[] = [
    'I try to understand thoroughly what I read and reflect on it.',
    'When I receive a poor mark, I become discouraged.',
    'I try to find relationships between what I learn and what I already know.',
    'I feel capable of completing my study commitments successfully.',
    'I feel very uncomfortable during a written assignment or oral assessment even when I am well prepared.',
    'When an oral assessment goes well, I think I was lucky that the teacher asked me something I knew.',
    'I take notes during lessons because this helps me pay closer attention.',
    'When I begin a classroom assignment, I am confident that I can do well.',
    'During an oral assessment, fear of making a mistake bothers me and I perform worse.',
    'When I do not succeed in an assignment or oral assessment, I think the reason is that I did not study seriously.',
    'While studying, I ask myself questions or do exercises to check whether I have understood properly.',
    'I try to link what I am studying with my experiences.',
    'When I do not succeed in an assignment or oral assessment, I think I was asked something too difficult.',
    'I try to see how what I study could apply to my everyday life.',
    'When I read a text, I mark the most important points in it.',
    'When I must face an oral assessment or written assignment, I am so nervous that I cannot express myself well.',
    'When an oral assessment goes well, I think I did well to study with so much effort.',
    'I organise my study according to the time I have available.',
    'When I learn something new, I try to find an example to which it can apply.',
    'I create outlines, diagrams, maps or summary tables to summarise what I study.',
    'When I do well at school, I think it is because I am a truly capable person.',
    'I become nervous straight away when faced with a question or problem that I do not immediately understand.',
    'I make drawings or sketches that help me understand what I am studying.',
    'While studying or listening to a lesson, links with other subjects I have already studied come to mind.',
    'I go to school having completed my homework and studied my lessons.',
    'When I do well, I think it is because the task was easy.',
    'Even if I do not like the subject, I still make an effort to succeed.',
    'When I study, I make outlines to understand and remember better.',
    'When faced with a demanding task, I feel encouraged to try harder.',
    'I think that not succeeding at school depends on the intelligence a person has.',
    'I do my homework in good time.',
    'Even if a task seems boring, I still try to finish it.',
    'I think that succeeding at school depends on the persistence and effort put into studying.',
    'I study only when I am going to be assessed, rather than systematically day by day.',
    'When I decide to do something, I finish it even if it requires effort.',
    'When reviewing lessons, I find it useful to use drawings, diagrams or summary tables in the text.',
    'I feel confident that I can obtain good marks.',
    'If I realise that I no longer have enough time to finish a task, I panic.',
    'I sometimes think that a person\'s intelligence is something that cannot really change: it is a natural gift.',
    'Before studying, I check what I need to do.',
    'While the teacher is explaining, I find myself becoming distracted.',
    'I understand better if the teacher uses sketches and diagrams on the board while explaining.',
    'To remember what I study better, I try to link the different ideas together.',
    'While studying, I sometimes find myself thinking about other things.',
    'If I have prepared for an assignment or oral assessment, I am confident that I will do well.',
    'When I encounter a difficulty, I make a greater effort to overcome it.',
];

const QSAR_SV: string[] = [
    'Jag försöker förstå ordentligt det jag läser och reflekterar över det.',
    'När jag får ett dåligt betyg blir jag nedstämd.',
    'Jag försöker hitta samband mellan det jag lär mig och det jag redan vet.',
    'Jag känner att jag klarar av att genomföra mina studieåtaganden med framgång.',
    'Jag känner mig mycket obekväm under en skriftlig uppgift eller ett muntligt förhör även när jag är väl förberedd.',
    'När ett muntligt förhör går bra tänker jag att jag hade tur som fick en fråga jag kunde.',
    'Jag antecknar under lektionerna eftersom det hjälper mig att vara mer uppmärksam.',
    'När jag börjar med en uppgift i klassrummet är jag övertygad om att jag kan göra bra ifrån mig.',
    'Under ett muntligt förhör stör rädslan för att göra fel mig och det går sämre.',
    'När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att orsaken är att jag inte studerade seriöst.',
    'När jag studerar ställer jag frågor till mig själv eller gör övningar för att kontrollera att jag har förstått ordentligt.',
    'Jag försöker koppla det jag studerar till mina erfarenheter.',
    'När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att jag fick något som var för svårt.',
    'Jag försöker se hur det jag studerar skulle kunna användas i mitt vardagsliv.',
    'När jag läser en text markerar jag det viktigaste i texten.',
    'När jag ska göra ett muntligt förhör eller en skriftlig uppgift är jag så nervös att jag inte kan uttrycka mig bra.',
    'När ett muntligt förhör går bra tänker jag att jag gjorde rätt som studerade så flitigt.',
    'Jag organiserar mina studier utifrån den tid jag har till förfogande.',
    'När jag lär mig något nytt försöker jag hitta ett exempel där det kan användas.',
    'Jag gör dispositioner, diagram, kartor eller sammanfattande tabeller för att sammanfatta det jag studerar.',
    'När det går bra för mig i skolan tänker jag att det beror på att jag är en verkligt kompetent person.',
    'Jag blir genast nervös inför en fråga eller ett problem som jag inte förstår direkt.',
    'Jag gör teckningar eller skisser som hjälper mig att förstå det jag studerar.',
    'När jag studerar eller lyssnar på en lektion kommer jag att tänka på samband med andra ämnen jag redan har studerat.',
    'Jag går till skolan efter att ha gjort läxorna och studerat lektionerna.',
    'När jag lyckas bra tänker jag att det beror på att uppgiften var lätt.',
    'Även om jag inte tycker om ämnet anstränger jag mig ändå för att lyckas.',
    'När jag studerar gör jag dispositioner för att förstå och minnas bättre.',
    'Inför en krävande uppgift känner jag mig stimulerad att anstränga mig mer.',
    'Jag tänker att misslyckanden i skolan beror på den intelligens en person har.',
    'Jag gör mina läxor i god tid.',
    'Även om en uppgift verkar tråkig försöker jag ändå avsluta den.',
    'Jag tänker att framgång i skolan beror på uthålligheten och ansträngningen i studierna.',
    'Jag studerar bara när jag ska förhöras och inte systematiskt dag för dag.',
    'När jag bestämmer mig för att göra något slutför jag det även om det kräver ansträngning.',
    'När jag repeterar lektioner tycker jag att det är användbart att använda teckningar, diagram eller sammanfattande tabeller i texten.',
    'Jag känner mig säker på att jag kan få bra betyg.',
    'Om jag märker att jag inte längre har tid att avsluta ett arbete grips jag av panik.',
    'Jag tänker ibland att en persons intelligens är något som egentligen inte går att förändra: den är en naturgåva.',
    'Innan jag studerar kontrollerar jag vad jag behöver göra.',
    'När läraren förklarar händer det att jag blir distraherad.',
    'Jag förstår bättre om läraren använder skisser och diagram på tavlan när hen förklarar.',
    'För att bättre minnas det jag studerar försöker jag koppla samman de olika idéerna.',
    'När jag studerar händer det att jag tänker på annat.',
    'Om jag har förberett mig inför en uppgift eller ett muntligt förhör är jag säker på att jag kommer att lyckas.',
    'När jag möter en svårighet anstränger jag mig mer för att övervinna den.',
];

// ZTPI items (Zimbardo Time Perspective Inventory)
// Sources: Zimbardo & Boyd (1999) J Pers Soc Psychol; Swedish adaptation by Carelli et al.
const ZTPI_EN: string[] = [
    'I believe that getting together with one\'s friends to party is one of life\'s important pleasures.',
    'Familiar childhood sights, sounds and smells often bring back a flood of wonderful memories.',
    'Fate determines much of my life.',
    'I often think of what I should have done differently in my life.',
    'My decisions are mostly influenced by the people and things around me.',
    'I believe that a person\'s day should be planned ahead each morning.',
    'It gives me pleasure to think about my past.',
    'I act on the spur of the moment.',
    'If things don\'t get done on time, I don\'t worry about it.',
    'When I want to achieve something, I set goals and consider specific means for reaching those goals.',
    'On balance, there is much more good to recall than bad in my past.',
    'When listening to my favourite music, I often lose all track of time.',
    'Meeting tomorrow\'s deadlines and doing other necessary work comes before tonight\'s fun.',
    'Since whatever will be will be, it doesn\'t really matter what I do.',
    'I enjoy stories about the past and how things were in the old days.',
    'Painful past experiences keep being replayed in my mind.',
    'I try to live my life as fully as possible, one day at a time.',
    'It upsets me to be late for appointments.',
    'Ideally, I would live each day as if it were my last.',
    'Happy memories of good times spring readily to mind.',
    'I meet my obligations to friends and authorities on time.',
    'I\'ve taken my share of abuse and rejection in the past.',
    'I make decisions on the spur of the moment.',
    'I take each day as it is rather than try to plan it out.',
    'The past has too many unpleasant memories that I prefer not to recall.',
    'It is important to put excitement in my life.',
    'I\'ve made mistakes in the past that I wish I could undo.',
    'I feel that it\'s more important to enjoy what you\'re doing than to get the job done on time.',
    'I get nostalgic about my childhood.',
    'Before making a decision, I weigh the costs against the benefits.',
    'Taking risks keeps my life from becoming boring.',
    'It is more important for me to enjoy life\'s journey than to focus only on the destination.',
    'Things rarely work out as I expected.',
    'It\'s hard for me to forget unpleasant images of my youth.',
    'It takes joy out of the process of my activities if I have to think about goals and outcomes.',
    'Even when I am enjoying the present, I am drawn back to comparisons with similar past experiences.',
    'You can\'t really plan for the future because things change so much.',
    'My life path is controlled by forces I cannot influence.',
    'I don\'t like to think about the past.',
    'I think about the bad things that have happened to me in the past.',
    'I believe that life today is too complicated; I would rather enjoy the simpler life of the past.',
    'I prefer friends who are spontaneous rather than predictable.',
    'I keep working at a difficult uninteresting task if it will help me get ahead.',
    'Spending what I earn on pleasures today is better than saving for tomorrow\'s security.',
    'Often I wish I could go back in time and change what I did.',
    'I like to get my work done before playing.',
    'I get irritated at people who keep me from being on time.',
    'It is more important to save for the future than to buy what one wants today.',
    'I complete projects on time by making steady progress.',
    'I like to listen to elderly people talk about the old days.',
    'I take risks to put excitement in my life.',
    'I make lists of things to do.',
    'I am able to resist temptations when there is work to be done.',
    'I find myself getting swept up in the excitement of the moment.',
    'I am impulsive.',
    'I try to make my life spontaneous rather than planned.',
];

const ZTPI_SV: string[] = [
    'Jag tror att att träffa vänner och festa är en av livets viktiga glädjeämnen.',
    'Bekanta barndomssyner, ljud och dofter väcker ofta en rad underbara minnen till liv.',
    'Ödet bestämmer mycket av mitt liv.',
    'Jag tänker ofta på vad jag borde ha gjort annorlunda i mitt liv.',
    'Mina beslut påverkas mest av människor och saker omkring mig.',
    'Jag tror att en persons dag bör planeras i förväg varje morgon.',
    'Det gläder mig att tänka på mitt förflutna.',
    'Jag handlar impulsivt.',
    'Om saker inte blir gjorda i tid oroar jag mig inte över det.',
    'När jag vill uppnå något sätter jag upp mål och överväger specifika sätt att nå dem.',
    'Sammantaget finns det mycket mer gott än ont att minnas från mitt förflutna.',
    'När jag lyssnar på min favoritmusik tappar jag ofta helt bort tiden.',
    'Morgondagens deadlines och annat nödvändigt arbete kommer före kvällens nöjen.',
    'Eftersom det som sker ändå sker spelar det ingen roll vad jag gör.',
    'Jag tycker om berättelser om det förflutna och hur saker var förr i tiden.',
    'Smärtsamma tidigare erfarenheter spelas upp om och om igen i mitt huvud.',
    'Jag försöker leva mitt liv så fullt ut som möjligt, en dag i taget.',
    'Det gör mig upprörd att komma för sent till möten.',
    'Helst skulle jag leva varje dag som om den vore min sista.',
    'Glada minnen från goda stunder dyker lätt upp.',
    'Jag uppfyller mina åtaganden gentemot vänner och auktoriteter i tid.',
    'Jag har fått min del av övergrepp och avvisande i det förflutna.',
    'Jag fattar beslut impulsivt.',
    'Jag tar varje dag som den kommer istället för att planera den.',
    'Det förflutna har alltför många obehagliga minnen som jag helst inte vill tänka på.',
    'Det är viktigt att skapa spänning i mitt liv.',
    'Jag har gjort misstag i det förflutna som jag önskar att jag kunde göra ogjorda.',
    'Jag tycker att det är viktigare att njuta av det man gör än att bli klar i tid.',
    'Jag blir nostalgisk över min barndom.',
    'Innan jag fattar ett beslut väger jag kostnader mot fördelar.',
    'Att ta risker förhindrar att mitt liv blir tråkigt.',
    'Det är viktigare för mig att njuta av livets resa än att bara fokusera på målet.',
    'Saker och ting blir sällan som jag förväntat mig.',
    'Det är svårt för mig att glömma obehagliga bilder från min ungdom.',
    'Om jag måste tänka på mål och resultat försvinner glädjen i det jag gör.',
    'Även när jag njuter av nuet dras jag tillbaka till jämförelser med liknande tidigare erfarenheter.',
    'Man kan egentligen inte planera för framtiden eftersom saker förändras så mycket.',
    'Min livsväg styrs av krafter som jag inte kan påverka.',
    'Jag tycker inte om att tänka på det förflutna.',
    'Jag tänker på dåliga saker som hänt mig tidigare.',
    'Jag tycker att livet idag är för komplicerat; jag skulle hellre njuta av det enklare livet förr.',
    'Jag föredrar vänner som är spontana snarare än förutsägbara.',
    'Jag fortsätter arbeta med en svår ointressant uppgift om det hjälper mig att komma framåt.',
    'Det är bättre att spendera det jag tjänar på nöjen idag än att spara till morgondagens trygghet.',
    'Ofta önskar jag att jag kunde gå tillbaka i tiden och förändra det jag gjorde.',
    'Jag gör helst klart mitt arbete innan jag leker.',
    'Jag blir irriterad på människor som hindrar mig från att vara i tid.',
    'Det är viktigare att spara för framtiden än att köpa vad man vill ha idag.',
    'Jag slutför projekt i tid genom att göra stadiga framsteg.',
    'Jag tycker om att lyssna på äldre människor som berättar om förr i tiden.',
    'Jag tar risker för att skapa spänning i mitt liv.',
    'Jag gör listor över saker som måste göras.',
    'Jag kan motstå frestelser när det finns arbete som måste göras.',
    'Jag rycks ofta med av stundens spänning.',
    'Jag är impulsiv.',
    'Jag försöker göra mitt liv spontant snarare än planerat.',
];

// QAP items (Career Adapt-Abilities Scale / CAAS)
// Source: Savickas & Porfeli (2012) J Vocat Behav
const QAP_EN: string[] = [
    'Thinking about what my future will be like.',
    'Realising that today\'s choices shape my future.',
    'Preparing for the future.',
    'Becoming aware of the educational and career choices I have to make.',
    'Planning how to achieve my goals.',
    'Being concerned about my career.',
    'Keeping upbeat.',
    'Making decisions by myself.',
    'Taking responsibility for my actions.',
    'Sticking up for my beliefs.',
    'Counting on myself.',
    'Doing what is right for me.',
    'Looking for opportunities to grow as a person.',
    'Investigating options before making a choice.',
    'Observing how different people do things.',
    'Probing deeply into questions I have.',
    'Becoming curious about new opportunities.',
    'Exploring my surroundings.',
    'Performing tasks efficiently.',
    'Taking care to do things well.',
    'Learning new skills.',
    'Working up to my ability.',
    'Overcoming obstacles.',
    'Solving problems.',
];

const QAP_SV: string[] = [
    'Tänka på hur min framtid kommer att se ut.',
    'Inse att dagens val formar min framtid.',
    'Förbereda mig för framtiden.',
    'Bli medveten om de utbildnings- och karriärval jag måste göra.',
    'Planera hur jag ska nå mina mål.',
    'Vara engagerad i min karriär.',
    'Hålla humöret uppe.',
    'Fatta beslut på egen hand.',
    'Ta ansvar för mina handlingar.',
    'Stå upp för mina övertygelser.',
    'Lita på mig själv.',
    'Göra det som är rätt för mig.',
    'Söka möjligheter att växa som person.',
    'Undersöka alternativ innan jag fattar ett beslut.',
    'Observera hur olika personer gör saker.',
    'Fördjupa mig i frågor jag har.',
    'Bli nyfiken på nya möjligheter.',
    'Utforska min omgivning.',
    'Utföra uppgifter effektivt.',
    'Se till att göra saker bra.',
    'Lära mig nya färdigheter.',
    'Arbeta upp till min förmåga.',
    'Övervinna hinder.',
    'Lösa problem.',
];

// QPCS items — experimental EN/SV wording based on strategic competence areas (S1–S5)
// Source: CNOS-FAP / Pellerey (constructs); EN/SV items are working translations.
const QPCS_EN: string[] = [
    'I feel calm and relaxed when I sit down to study.',
    'I know how to handle my anxiety before an exam.',
    'When I feel tense about schoolwork, I have ways to relax.',
    'Worrying about tests rarely interferes with my performance.',
    'I can stay calm even when the workload is heavy.',
    'I express my ideas clearly when working in a group.',
    'I find it easy to ask for help when I need it.',
    'I feel comfortable explaining things to my classmates.',
    'I listen carefully to others\' opinions during discussions.',
    'I can adapt my communication style to different people.',
    'When I decide to do something, I see it through to the end.',
    'I keep working on a task even when it becomes difficult.',
    'I do not give up easily on challenging assignments.',
    'I manage my time well and meet deadlines.',
    'I push myself to finish my work even when I feel tired.',
    'I organise my study material in a way that helps me learn.',
    'I use different learning strategies depending on the subject.',
    'I review my notes regularly to reinforce my understanding.',
    'I find it helpful to study together with classmates.',
    'I contribute actively when working in a team.',
    'I believe I have the ability to succeed in my studies.',
    'I feel confident about making decisions for my future.',
    'I can identify my strengths and areas for improvement.',
    'I have a clear sense of direction for my career path.',
    'I trust that my efforts will lead to good outcomes.',
];

const QPCS_SV: string[] = [
    'Jag känner mig lugn och avslappnad när jag studerar.',
    'Jag vet hur jag hanterar min oro inför ett prov.',
    'När jag känner mig spänd över skolarbete har jag sätt att koppla av.',
    'Oro inför prov påverkar sällan mina prestationer.',
    'Jag kan hålla mig lugn även när arbetsbelastningen är tung.',
    'Jag uttrycker mina idéer tydligt när jag arbetar i grupp.',
    'Jag har lätt för att be om hjälp när jag behöver det.',
    'Jag känner mig bekväm med att förklara saker för mina klasskamrater.',
    'Jag lyssnar noga på andras åsikter under diskussioner.',
    'Jag kan anpassa mitt sätt att kommunicera till olika personer.',
    'När jag bestämmer mig för att göra något fullföljer jag det.',
    'Jag fortsätter arbeta med en uppgift även när den blir svår.',
    'Jag ger inte lätt upp vid utmanande uppgifter.',
    'Jag planerar min tid väl och håller deadline.',
    'Jag pressar mig själv att slutföra mitt arbete även när jag är trött.',
    'Jag organiserar mitt studiematerial på ett sätt som hjälper mig att lära.',
    'Jag använder olika inlärningsstrategier beroende på ämne.',
    'Jag går igenom mina anteckningar regelbundet för att befästa min förståelse.',
    'Jag tycker att det är hjälpsamt att studera tillsammans med klasskamrater.',
    'Jag bidrar aktivt när jag arbetar i team.',
    'Jag tror att jag har förmågan att lyckas i mina studier.',
    'Jag känner mig trygg med att fatta beslut om min framtid.',
    'Jag kan identifiera mina styrkor och områden att förbättra.',
    'Jag har en tydlig riktning för min karriärväg.',
    'Jag litar på att mina ansträngningar leder till goda resultat.',
];

// QPCC items — experimental EN/SV wording based on competence & belief areas (K1–K5)
// Source: CNOS-FAP / Pellerey (constructs); EN/SV items are working translations.
const QPCC_EN: string[] = [
    'I feel confident when I have to speak in front of a group.',
    'I can present my ideas clearly to an audience.',
    'I enjoy participating in class presentations.',
    'I am able to persuade others with my arguments.',
    'I feel comfortable expressing my opinions in a meeting.',
    'I can manage pressure when making important decisions.',
    'I take responsibility for the consequences of my choices.',
    'I stay calm when faced with unexpected challenges.',
    'I am able to balance multiple responsibilities at the same time.',
    'I handle stressful situations without losing focus.',
    'I set clear goals for my studies and work.',
    'I organise my tasks in order of priority.',
    'I monitor my own progress towards my goals.',
    'I adjust my plans when circumstances change.',
    'I reflect on my actions to learn from experience.',
    'I connect new information with what I already know.',
    'I organise ideas in my mind to understand them better.',
    'I apply what I learn in one subject to other areas.',
    'I use examples and analogies to deepen my understanding.',
    'I think critically about the information I receive.',
    'I believe in my ability to learn new things.',
    'I trust that my efforts will pay off in the long run.',
    'I attribute my successes to my own skills and hard work.',
    'I am optimistic about my ability to overcome difficulties.',
    'I believe that I can improve through practice and dedication.',
];

const QPCC_SV: string[] = [
    'Jag känner mig trygg när jag ska tala inför en grupp.',
    'Jag kan presentera mina idéer tydligt inför en publik.',
    'Jag tycker om att delta i klasspresentationer.',
    'Jag kan övertyga andra med mina argument.',
    'Jag känner mig bekväm med att uttrycka mina åsikter i ett möte.',
    'Jag hanterar press när jag fattar viktiga beslut.',
    'Jag tar ansvar för konsekvenserna av mina val.',
    'Jag förblir lugn inför oväntade utmaningar.',
    'Jag kan balansera flera ansvarsområden samtidigt.',
    'Jag hanterar stressiga situationer utan att tappa fokus.',
    'Jag sätter tydliga mål för mina studier och mitt arbete.',
    'Jag organiserar mina uppgifter i prioritetsordning.',
    'Jag följer mina egna framsteg mot mina mål.',
    'Jag justerar mina planer när omständigheterna förändras.',
    'Jag reflekterar över mina handlingar för att lära av erfarenhet.',
    'Jag kopplar ny information till det jag redan vet.',
    'Jag organiserar idéer i mitt huvud för att förstå dem bättre.',
    'Jag tillämpar det jag lärt mig i ett ämne på andra områden.',
    'Jag använder exempel och analogier för att fördjupa min förståelse.',
    'Jag tänker kritiskt på den information jag får.',
    'Jag tror på min förmåga att lära mig nya saker.',
    'Jag litar på att mina ansträngningar lönar sig i längden.',
    'Jag tillskriver mina framgångar mina egna färdigheter och hårda arbete.',
    'Jag är optimistisk om min förmåga att övervinna svårigheter.',
    'Jag tror att jag kan förbättras genom övning och hängivenhet.',
];

const EN_BASE = {
    testBadge: 'TEST VERSION',
    warningTitle: 'Administration for instrument testing only',
    warningBody: 'This English/Swedish version is being tested as an instrument adaptation. Any profile shown after submission is an experimental preview, not a validated assessment, and must not be used for individual educational, guidance or diagnostic decisions.',
    instructions: 'For each statement, select how often it usually describes what you do or feel. Answer according to what you actually do or feel, not what you would like to do.',
    privacyNote: 'Responses are saved to your profile history to let you review them and continue with the AI chatbot.',
    scale: ['Never or almost never', 'Sometimes', 'Often', 'Always or almost always'] as [string, string, string, string],
    progress: 'answered',
    missingAnswers: 'Answer every statement before submitting the test administration.',
    submit: 'Submit test administration',
    submittedTitle: 'Experimental factor profile',
    submittedBody: 'This profile is an experimental preview for testing the adapted instrument. It has been saved to your session history to support AI validation and PDF report generation.',
    profileMethod: 'Bars show the average selected frequency for the items assigned to each factor (1 to 4); oppositely worded items are reverse-coded within their factor. No English or Swedish norms have been applied, and the adapted factor configuration remains subject to scientific review.',
    rawAverage: 'Raw frequency average',
    restart: 'Complete again',
    back: 'Back to test administrations',
    startChat: 'Start AI Chat',
    stanineScore: 'Stanine Score',
};

const SV_BASE = {
    testBadge: 'TESTVERSION',
    warningTitle: 'Genomförandet används endast för att testa instrumentet',
    warningBody: 'Denna engelska/svenska version testas som en anpassning av instrumentet. Varje profil som visas efter inskickning är en experimentell förhandsvisning, inte en validerad bedömning, och får inte användas för individuella utbildnings-, väglednings- eller diagnostiska beslut.',
    instructions: 'För varje påstående väljer du hur ofta det vanligtvis beskriver vad du gör eller känner. Svara utifrån vad du faktiskt gör eller känner, inte vad du skulle vilja göra.',
    privacyNote: 'Svaren sparas i din profilhistorik så att du kan granska dem och fortsätta med AI-chatten.',
    scale: ['Aldrig eller nästan aldrig', 'Ibland', 'Ofta', 'Alltid eller nästan alltid'] as [string, string, string, string],
    progress: 'besvarade',
    missingAnswers: 'Besvara alla påståenden innan du skickar in testgenomförandet.',
    submit: 'Skicka in testgenomförande',
    submittedTitle: 'Experimentell faktorprofil',
    submittedBody: 'Denna profil är en experimentell förhandsvisning för att testa det anpassade instrumentet. Den har sparats i din sessionshistorik för att stödja AI-validering och generering av PDF-rapport.',
    profileMethod: 'Staplarna visar den genomsnittliga valda frekvensen för de påståenden som hör till varje faktor (1 till 4); omvänt formulerade påståenden omkodas inom sin faktor. Inga engelska eller svenska normer har tillämpats, och den anpassade faktorkonfigurationen behöver fortfarande vetenskaplig granskning.',
    rawAverage: 'Rått frekvensmedelvärde',
    restart: 'Fyll i igen',
    back: 'Tillbaka till testgenomföranden',
    startChat: 'Starta AI-chat',
    stanineScore: 'Stanine-poäng',
};

const ES_BASE = {
    testBadge: 'VERSION DE PRUEBA',
    warningTitle: 'Administracion solo para probar el instrumento',
    warningBody: 'Esta version espanola se esta usando para validar la adaptacion del instrumento. Cualquier perfil mostrado tras el envio es una vista experimental, no una evaluacion validada, y no debe usarse para decisiones educativas, orientadoras o diagnosticas individuales.',
    instructions: 'Para cada afirmacion, selecciona con que frecuencia describe lo que haces o sientes habitualmente. Responde segun lo que realmente haces o sientes, no segun lo que te gustaria hacer.',
    privacyNote: 'Las respuestas se guardan para construir el conjunto de datos de validacion y permitir controles posteriores.',
    scale: ['Nunca o casi nunca', 'A veces', 'A menudo', 'Siempre o casi siempre'] as [string, string, string, string],
    progress: 'respondidas',
    missingAnswers: 'Responde a todas las afirmaciones antes de enviar la administracion.',
    submit: 'Enviar administracion',
    submittedTitle: 'Perfil factorial experimental',
    submittedBody: 'Este perfil es una vista experimental para probar la version adaptada del instrumento. Las respuestas brutas se han guardado para la validacion psicometrica.',
    profileMethod: 'Las barras muestran la frecuencia media seleccionada para los items asignados a cada factor (1 a 4); los items inversos se recodifican dentro de su factor. Las normas espanolas solo deben aplicarse despues de la validacion.',
    rawAverage: 'Media bruta de frecuencia',
    restart: 'Completar de nuevo',
    back: 'Volver a las administraciones',
    startChat: 'Iniciar chat AI',
    stanineScore: 'Puntuacion stanine',
};

const QSA_DIMENSIONS: Record<string, string> = {
    cognitive: 'Cognitive and metacognitive factors',
    affective: 'Affective and motivational factors',
};

const QSA_DIMENSIONS_SV: Record<string, string> = {
    cognitive: 'Kognitiva och metakognitiva faktorer',
    affective: 'Affektiva och motivationella faktorer',
};

const QSA_DIMENSIONS_ES: Record<string, string> = {
    cognitive: 'Factores cognitivos y metacognitivos',
    affective: 'Factores afectivos y motivacionales',
};

const ZTPI_DIMENSIONS: Record<string, string> = {
    pn: 'Past Negative',
    pp: 'Past Positive',
    ph: 'Present Hedonistic',
    pf: 'Present Fatalistic',
    f: 'Future',
};

const ZTPI_DIMENSIONS_SV: Record<string, string> = {
    pn: 'Negativt förflutet',
    pp: 'Positivt förflutet',
    ph: 'Hedonistisk nutid',
    pf: 'Fatalistisk nutid',
    f: 'Framtid',
};

const ZTPI_DIMENSIONS_ES: Record<string, string> = {
    pn: 'Pasado negativo',
    pp: 'Pasado positivo',
    ph: 'Presente hedonista',
    pf: 'Presente fatalista',
    f: 'Futuro',
};

const QAP_DIMENSIONS: Record<string, string> = {
    concern: 'Concern',
    control: 'Control',
    curiosity: 'Curiosity',
    confidence: 'Confidence',
};

const QAP_DIMENSIONS_SV: Record<string, string> = {
    concern: 'Omsorg om framtiden',
    control: 'Kontroll',
    curiosity: 'Nyfikenhet',
    confidence: 'Tilltro',
};

const QAP_DIMENSIONS_ES: Record<string, string> = {
    concern: 'Preocupacion por el futuro',
    control: 'Control',
    curiosity: 'Curiosidad',
    confidence: 'Confianza',
};

const QPCS_DIMENSIONS: Record<string, string> = {
    managing_emotions: 'Managing emotions',
    communicative_competence: 'Communicative competence',
    will_perseverance: 'Will & perseverance',
    strategies_collaboration: 'Strategies & collaboration',
    confidence_life_project: 'Confidence & life project',
};

const QPCS_DIMENSIONS_SV: Record<string, string> = {
    managing_emotions: 'Hantera känslor',
    communicative_competence: 'Kommunikativ kompetens',
    will_perseverance: 'Vilja & uthållighet',
    strategies_collaboration: 'Strategier & samarbete',
    confidence_life_project: 'Tilltro & livsprojekt',
};

const QPCS_DIMENSIONS_ES: Record<string, string> = {
    managing_emotions: 'Gestion de las emociones',
    communicative_competence: 'Competencia comunicativa',
    will_perseverance: 'Voluntad y perseverancia',
    strategies_collaboration: 'Estrategias y colaboracion',
    confidence_life_project: 'Confianza y proyecto de vida',
};

const QPCC_DIMENSIONS: Record<string, string> = {
    public_speaking: 'Public speaking',
    anxiety_responsibility: 'Managing anxiety & responsibility',
    volition_selfregulation: 'Volition & self-regulation',
    elaboration_strategies: 'Elaboration strategies',
    beliefs_about_self: 'Beliefs about oneself',
};

const QPCC_DIMENSIONS_SV: Record<string, string> = {
    public_speaking: 'Tala inför andra',
    anxiety_responsibility: 'Hantera ångest & ansvar',
    volition_selfregulation: 'Vilja & självreglering',
    elaboration_strategies: 'Bearbetningsstrategier',
    beliefs_about_self: 'Föreställningar om sig själv',
};

const QPCC_DIMENSIONS_ES: Record<string, string> = {
    public_speaking: 'Hablar en publico',
    anxiety_responsibility: 'Gestion de ansiedad y responsabilidad',
    volition_selfregulation: 'Volicion y autorregulacion',
    elaboration_strategies: 'Estrategias de elaboracion',
    beliefs_about_self: 'Creencias sobre uno mismo',
};

export const TEST_ADMINISTRATIONS: Record<AdministrationInstrument, Record<AdministrationLocale, AdministrationCopy>> = {
    QSA: {
        en: {
            ...EN_BASE,
            dimensionTitles: QSA_DIMENSIONS,
            shortName: 'QSA',
            title: 'Learning Strategies Questionnaire (QSA)',
            items: QSA_EN,
        },
        es: {
            ...ES_BASE,
            dimensionTitles: QSA_DIMENSIONS_ES,
            shortName: 'QSA',
            title: 'Cuestionario sobre Estrategias de Aprendizaje (QSA)',
            items: QSA_EN,
        },
        sv: {
            ...SV_BASE,
            dimensionTitles: QSA_DIMENSIONS_SV,
            shortName: 'QSA',
            title: 'Frågeformulär om inlärningsstrategier (QSA)',
            items: QSA_SV,
        },
    },
    QSAr: {
        en: {
            ...EN_BASE,
            dimensionTitles: QSA_DIMENSIONS,
            shortName: 'QSAr',
            title: 'Learning Strategies Questionnaire - Short Form (QSAr)',
            items: QSAR_EN,
        },
        es: {
            ...ES_BASE,
            dimensionTitles: QSA_DIMENSIONS_ES,
            shortName: 'QSAr',
            title: 'Cuestionario sobre Estrategias de Aprendizaje - version reducida (QSAr)',
            items: QSAR_EN,
        },
        sv: {
            ...SV_BASE,
            dimensionTitles: QSA_DIMENSIONS_SV,
            shortName: 'QSAr',
            title: 'Frågeformulär om inlärningsstrategier - kortversion (QSAr)',
            items: QSAR_SV,
        },
    },
    ZTPI: {
        en: {
            ...EN_BASE,
            dimensionTitles: ZTPI_DIMENSIONS,
            shortName: 'ZTPI',
            title: 'Zimbardo Time Perspective Inventory (ZTPI)',
            items: ZTPI_EN,
        },
        es: {
            ...ES_BASE,
            dimensionTitles: ZTPI_DIMENSIONS_ES,
            shortName: 'ZTPI',
            title: 'Inventario de Perspectiva Temporal de Zimbardo (ZTPI)',
            items: ZTPI_EN,
        },
        sv: {
            ...SV_BASE,
            dimensionTitles: ZTPI_DIMENSIONS_SV,
            shortName: 'ZTPI',
            title: 'Zimbardos tidsperspektivinventarium (ZTPI)',
            items: ZTPI_SV,
        },
    },
    QPCS: {
        en: {
            ...EN_BASE,
            dimensionTitles: QPCS_DIMENSIONS,
            shortName: 'QPCS',
            title: 'Perceived Strategic Competences Questionnaire (QPCS)',
            items: QPCS_EN,
        },
        es: {
            ...ES_BASE,
            dimensionTitles: QPCS_DIMENSIONS_ES,
            shortName: 'QPCS',
            title: 'Cuestionario de Competencias Estrategicas Percibidas (QPCS)',
            items: QPCS_EN,
        },
        sv: {
            ...SV_BASE,
            dimensionTitles: QPCS_DIMENSIONS_SV,
            shortName: 'QPCS',
            title: 'Frågeformulär om upplevda strategiska kompetenser (QPCS)',
            items: QPCS_SV,
        },
    },
    QPCC: {
        en: {
            ...EN_BASE,
            dimensionTitles: QPCC_DIMENSIONS,
            shortName: 'QPCC',
            title: 'Perceived Competences and Beliefs Questionnaire (QPCC)',
            items: QPCC_EN,
            scale: ['Strongly disagree', 'Partly agree', 'Fairly agree', 'Fully agree'] as [string, string, string, string],
        },
        es: {
            ...ES_BASE,
            dimensionTitles: QPCC_DIMENSIONS_ES,
            shortName: 'QPCC',
            title: 'Cuestionario de Competencias y Creencias Percibidas (QPCC)',
            items: QPCC_EN,
            scale: ['Totalmente en desacuerdo', 'Parcialmente de acuerdo', 'Bastante de acuerdo', 'Totalmente de acuerdo'] as [string, string, string, string],
        },
        sv: {
            ...SV_BASE,
            dimensionTitles: QPCC_DIMENSIONS_SV,
            shortName: 'QPCC',
            title: 'Frågeformulär om upplevda kompetenser och föreställningar (QPCC)',
            items: QPCC_SV,
            scale: ['Instämmer inte alls', 'Instämmer delvis', 'Instämmer ganska mycket', 'Instämmer helt'] as [string, string, string, string],
        },
    },
    QAP: {
        en: {
            ...EN_BASE,
            dimensionTitles: QAP_DIMENSIONS,
            shortName: 'QAP',
            title: 'Career Adapt-Abilities Scale (QAP/CAAS)',
            items: QAP_EN,
        },
        es: {
            ...ES_BASE,
            dimensionTitles: QAP_DIMENSIONS_ES,
            shortName: 'QAP',
            title: 'Escala de Adaptabilidad de Carrera (QAP/CAAS)',
            items: QAP_EN,
        },
        sv: {
            ...SV_BASE,
            dimensionTitles: QAP_DIMENSIONS_SV,
            shortName: 'QAP',
            title: 'Skala för anpassningsbarhet i karriären (QAP/CAAS)',
            items: QAP_SV,
        },
    },
};

export function getTestAdministration(
    instrument: string,
    locale: string,
): AdministrationCopy | null {
    const valid: AdministrationInstrument[] = ['QSA', 'QSAr', 'ZTPI', 'QPCS', 'QPCC', 'QAP'];
    if (!valid.includes(instrument as AdministrationInstrument)) return null;
    if (locale !== 'en' && locale !== 'es' && locale !== 'sv') return null;
    return TEST_ADMINISTRATIONS[instrument as AdministrationInstrument][locale];
}
