export type AdministrationInstrument = 'QSA' | 'QSAr';
export type AdministrationLocale = 'en' | 'sv';

export interface AdministrationCopy {
    title: string;
    shortName: string;
    testBadge: string;
    warningTitle: string;
    warningBody: string;
    instructions: string;
    privacyNote: string;
    scale: [string, string, string, string];
    items: string[];
    progress: string;
    missingAnswers: string;
    submit: string;
    submittedTitle: string;
    submittedBody: string;
    profileMethod: string;
    cognitiveTitle: string;
    affectiveTitle: string;
    rawAverage: string;
    restart: string;
    back: string;
}

const QSA_EN: string[] = [
    'After a lesson, I carefully review my notes in order to explore and remember the ideas better.',
    'When I read, I reflect on the subject and try to understand clearly what the text explains.',
    'Sometimes I do poorly on an assignment because I cannot understand exactly what I am expected to do.',
    'When I receive a poor mark, I become discouraged.',
    'When I do well at school, I think it is because I studied hard.',
    'When I prepare for an exam or an oral assessment, I think about the questions the teacher may ask me.',
    'When I learn new words or ideas, I try to imagine a situation in which they could be applied.',
    'When I study, I get lost in details and cannot identify the main points.',
    'I feel very uncomfortable during a written assignment or oral assessment even when I am well prepared.',
    'When an oral assessment goes well, I think I was lucky that the teacher asked me something I knew.',
    'I check whether I have understood correctly what the teacher said during the lesson.',
    'To pay closer attention, I take notes during lessons.',
    'I find that studying with a classmate is a waste of time.',
    'When I begin a classroom assignment, I am confident that I can do well.',
    'When I do not succeed in an assignment or oral assessment, I think the reason is that I did not study seriously.',
    'I sometimes think that I am capable of completing my study commitments successfully.',
    'I try to find relationships between what I am learning and what I already know.',
    'Outlines, diagrams or summary tables help me understand better what a text presents.',
    'During an oral assessment, fear of making a mistake bothers me so much that I perform worse.',
    'When an oral assessment goes well, I think I am really intelligent.',
    'While studying, I ask myself questions or do exercises to check whether I have understood properly.',
    'I try to find links between what I am studying and my experiences.',
    'I panic when I know that I must sit an important written exam.',
    'When I do not succeed in an assignment or oral assessment, I think I was asked something too difficult.',
    'When I have finished studying, I imagine the questions the teacher might ask and try to answer them.',
    'I try to see how what I study could apply to my everyday life.',
    'When I read a text, I mark the most important points in it.',
    'When I have to face an oral assessment or written assignment, I am so nervous that I cannot express myself as well as I could.',
    'When an oral assessment goes well, I think it is because I studied with a great deal of effort.',
    'I find discussing or working in a group useful and stimulating.',
    'I try to establish links between the different ideas in the text I am studying.',
    'I find it difficult to summarise what I have heard at school or read in a book.',
    'During a classroom assignment or an oral assessment, doubts and uncertainty about my ability to do well come into my mind.',
    'I organise my study according to the time I have available.',
    'Before studying a subject, I try to clarify what the teacher expects of me.',
    'When I learn a new concept, I try to find an example to which it could apply.',
    'I create outlines, diagrams or summary tables to summarise what I study.',
    'My heart beats strongly when I have to take an important exam or oral assessment.',
    'When I do well at school, I think it is because I am a truly capable person.',
    'During an oral assessment, I sometimes realise that I studied the wrong subject.',
    'When I learn a new concept, I ask myself whether there are cases in which it cannot be applied.',
    'I enjoy having to do work that challenges me.',
    'I memorise rules, technical terms or formulae even without understanding them.',
    'I make drawings and sketches that help me understand what I am studying.',
    'I become nervous straight away when faced with a question or problem that I do not immediately understand.',
    'I cannot stay focused on my work for more than fifteen minutes.',
    'I sometimes think that failures at school depend fundamentally on people not being capable.',
    'While studying or listening to a lesson, links with other subjects I have already studied come to mind.',
    'I go to school having completed all homework and studied all lessons.',
    'When I take part in group work, I feel that I understand things better.',
    'When I do well, I think it is because the task was easy.',
    'I sometimes find that a study topic is more difficult than I expected.',
    'When I do not feel able to complete it, I sometimes leave a piece of work unfinished.',
    'I make a serious effort to achieve a good mark even when I do not like the subject.',
    'If for some reason I cannot prepare my lessons, I feel uneasy.',
    'I remember better when studying if I can use outlines, diagrams or tables.',
    'I prefer studying a lesson on my own rather than with someone else\'s help.',
    'When faced with a demanding task, I feel encouraged to try harder.',
    'Even if I work very hard, I sometimes think that I cannot become more intelligent anyway.',
    'When I begin studying, I try to estimate how much time I need to learn a subject.',
    'If I find that a subject requires time and effort, I do not even consider it.',
    'When for some reason I fall behind in schoolwork, I try to catch up without the teacher making me do so.',
    'When I do a boring task, I think about its less negative aspects and the satisfaction I will feel when I finish.',
    'I sometimes think that succeeding at school depends on the intellectual ability a person has.',
    'I finish my homework in good time.',
    'If I cannot prepare well for school, I feel uncomfortable.',
    'Even if a task is boring, I continue doing it until I have finished it.',
    'I think that the ability to succeed at school depends on the effort each person puts into careful study.',
    'At home I do not study subjects according to a clear plan, but according to the urgency of upcoming assessments.',
    'When I have decided to do something, I finish it even if it requires effort.',
    'I find it of little use to rely on drawings, diagrams or summary tables in the text when reviewing lessons.',
    'I feel confident that I can obtain good marks.',
    'I think that a person\'s intelligence can improve over time if they make a serious effort.',
    'I feel that I learn better when I can compare ideas with my classmates.',
    'As soon as I encounter the first difficulties, I abandon a task I have only just started.',
    'When something goes badly, I think it depends more on external circumstances than on my ability or lack of effort.',
    'If I realise that I no longer have enough time to finish my work, I panic.',
    'I sometimes think that a person\'s intelligence is something that cannot really change: it is a natural gift.',
    'Problems at home or with friends cause me to neglect my schoolwork.',
    'If I fail, I feel inclined to try again.',
    'At the start of studying, I check what I need to do.',
    'When I think about the things I need to learn, I sometimes regard them as too difficult.',
    'I think that a person\'s ability depends on the persistence and effort they put into studying.',
    'When my teacher explains something, I find myself thinking about other things and do not follow the explanation.',
    'When reading, I use my imagination to reconstruct the situations, characters or events being described.',
    'I think that in study, as in work, it is important to learn to work together.',
    'If I am in a bad mood, I find it difficult to concentrate on studying.',
    'When I do well in an oral assessment, I think the teacher was understanding and asked me easy questions.',
    'While studying, I distract myself by daydreaming and making all kinds of plans.',
    'I understand better if the teacher uses sketches and diagrams on the board while explaining.',
    'At home and outside home, I sometimes enjoy talking about the things I do at school.',
    'If I have an emotional problem caused by difficult relationships with others or with my parents, I cannot apply myself to studying.',
    'If I am prepared, I am confident that I will do well in an assignment or oral assessment.',
    'I sometimes think that with serious effort a person can also develop their intelligence.',
    'When I encounter a difficulty, I try to overcome it by increasing my effort and concentration.',
    'I avoid asking questions because I think I would bother the teacher.',
    'When I am questioned unexpectedly, I freeze and can no longer speak.',
    'I find it difficult to tell whether a concept or topic is unclear to me.',
    'When I take part in group work, I feel that I am wasting time.',
    'To remember what I study better, I try to link the different ideas together.',
];

const QSA_SV: string[] = [
    'Efter en lektion går jag noggrant igenom mina anteckningar för att fördjupa och bättre minnas idéerna.',
    'När jag läser reflekterar jag över ämnet och försöker förstå ordentligt vad texten beskriver.',
    'Ibland går det dåligt på en uppgift eftersom jag inte kan förstå exakt vad jag ska göra.',
    'När jag får ett dåligt betyg blir jag nedstämd.',
    'När det går bra för mig i skolan tänker jag att det beror på att jag har studerat mycket.',
    'När jag förbereder mig inför ett prov eller ett muntligt förhör tänker jag på de frågor läraren kan ställa.',
    'När jag lär mig nya ord eller idéer försöker jag föreställa mig en situation där de kan användas.',
    'När jag studerar fastnar jag i detaljer och kan inte hitta det viktigaste.',
    'Jag känner mig mycket obekväm under en skriftlig uppgift eller ett muntligt förhör även när jag är väl förberedd.',
    'När ett muntligt förhör går bra tänker jag att jag hade tur som fick en fråga jag kunde.',
    'Jag kontrollerar om jag har förstått rätt vad läraren sade under lektionen.',
    'För att vara mer uppmärksam antecknar jag under lektionerna.',
    'Jag tycker att det är slöseri med tid att studera med en klasskamrat.',
    'När jag börjar med en uppgift i klassrummet är jag övertygad om att jag kan göra bra ifrån mig.',
    'När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att orsaken är att jag inte studerade tillräckligt seriöst.',
    'Jag tänker ibland att jag klarar av att genomföra mina studieåtaganden med framgång.',
    'Jag försöker hitta samband mellan det jag lär mig och det jag redan vet.',
    'Dispositioner, diagram eller sammanfattande tabeller hjälper mig att bättre förstå det som står i texten.',
    'Under ett muntligt förhör stör rädslan för att göra fel mig så mycket att det går sämre.',
    'När ett muntligt förhör går bra tänker jag att jag verkligen är intelligent.',
    'När jag studerar ställer jag frågor till mig själv eller gör övningar för att kontrollera att jag har förstått ordentligt.',
    'Jag försöker hitta kopplingar mellan det jag studerar och mina egna erfarenheter.',
    'Jag grips av panik när jag vet att jag ska göra ett viktigt skriftligt prov.',
    'När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att jag fick något som var för svårt.',
    'När jag har studerat klart föreställer jag mig vilka frågor läraren kan ställa och försöker besvara dem.',
    'Jag försöker se hur det jag studerar skulle kunna användas i mitt vardagsliv.',
    'När jag läser en text markerar jag det viktigaste i texten.',
    'När jag ska göra ett muntligt förhör eller en skriftlig uppgift är jag så nervös att jag inte kan uttrycka mig så bra som jag skulle kunna.',
    'När ett muntligt förhör går bra tänker jag att det beror på att jag studerade mycket flitigt.',
    'Jag tycker att det är användbart och stimulerande att diskutera eller arbeta i grupp.',
    'Jag försöker skapa samband mellan de olika idéerna i texten jag studerar.',
    'Jag har svårt att sammanfatta det jag har hört i skolan eller läst i en bok.',
    'Under en uppgift i klassrummet eller ett muntligt förhör får jag tvivel på min förmåga att lyckas.',
    'Jag organiserar mina studier utifrån den tid jag har till förfogande.',
    'Innan jag studerar ett ämne försöker jag klargöra vad läraren förväntar sig av mig.',
    'När jag lär mig ett nytt begrepp försöker jag hitta ett exempel där det kan användas.',
    'Jag gör dispositioner, diagram eller sammanfattande tabeller för att sammanfatta det jag studerar.',
    'Mitt hjärta slår hårt när jag ska göra ett viktigt prov eller muntligt förhör.',
    'När det går bra för mig i skolan tänker jag att det beror på att jag är en verkligt kompetent person.',
    'Under ett muntligt förhör händer det att jag inser att jag har studerat fel ämne.',
    'När jag lär mig ett nytt begrepp frågar jag mig om det finns fall där det inte kan användas.',
    'Jag tycker om att behöva göra ett arbete som utmanar mig.',
    'Jag lär mig regler, facktermer eller formler utantill även utan att förstå dem.',
    'Jag gör teckningar och skisser som hjälper mig att förstå det jag studerar.',
    'Jag blir genast nervös inför en fråga eller ett problem som jag inte förstår direkt.',
    'Jag kan inte hålla koncentrationen på arbetet i mer än en kvart.',
    'Jag tänker ibland att misslyckanden i skolan i grunden beror på att personer inte har förmågan.',
    'När jag studerar eller lyssnar på en lektion kommer jag att tänka på samband med andra ämnen jag redan har studerat.',
    'Jag går till skolan efter att ha gjort alla läxor och studerat alla lektioner.',
    'När jag deltar i grupparbete upplever jag att jag förstår saker bättre.',
    'När jag lyckas bra tänker jag att det beror på att arbetet var lätt.',
    'Ibland tycker jag att ett studieområde är svårare än jag hade väntat mig.',
    'När jag inte känner mig kapabel att slutföra ett arbete händer det att jag lämnar det halvfärdigt.',
    'Jag anstränger mig seriöst för att få ett bra betyg även när jag inte tycker om ämnet.',
    'Om jag av någon anledning inte kan förbereda lektionerna känner jag mig orolig.',
    'Jag minns bättre när jag studerar om jag kan använda dispositioner, diagram eller tabeller.',
    'Jag föredrar att studera lektionen ensam framför att få hjälp av andra.',
    'Inför en krävande uppgift känner jag mig stimulerad att anstränga mig mer.',
    'Även om jag anstränger mig mycket tänker jag ibland att jag ändå inte kan bli mer intelligent.',
    'När jag ska börja studera försöker jag förutse hur mycket tid jag behöver för att lära mig ett ämne.',
    'Om jag märker att ett ämne kräver tid och ansträngning överväger jag det inte ens.',
    'Om jag av någon anledning kommer efter med skolarbetet försöker jag ta igen det utan att läraren tvingar mig.',
    'När jag utför en tråkig uppgift tänker jag på dess mindre negativa sidor och på tillfredsställelsen när jag blir klar.',
    'Jag tänker ibland att förmågan att lyckas i skolan beror på den intelligens en person har.',
    'Jag gör klart mina läxor i god tid.',
    'Om jag inte kan förbereda mig väl inför skolan känner jag mig obekväm.',
    'Även om en uppgift är tråkig fortsätter jag tills jag har gjort klart den.',
    'Jag tänker att förmågan att lyckas i skolan beror på den ansträngning var och en lägger på noggranna studier.',
    'Hemma studerar jag inte ämnena efter en tydlig plan utan efter hur nära förestående förhör är.',
    'När jag har bestämt mig för att göra något slutför jag det även om det kräver ansträngning.',
    'När jag repeterar lektioner tycker jag att det är till liten nytta att använda teckningar, diagram eller sammanfattande tabeller i texten.',
    'Jag känner mig säker på att jag kan få bra betyg.',
    'Jag tänker att en persons intelligens kan förbättras med tiden om personen anstränger sig seriöst.',
    'Jag upplever att jag lär mig bättre när jag kan jämföra mina tankar med klasskamraternas.',
    'Så snart jag möter de första svårigheterna överger jag ett arbete som jag just har påbörjat.',
    'När något går dåligt tänker jag att det beror mer på yttre omständigheter än på min förmåga eller bristande ansträngning.',
    'Om jag märker att jag inte längre har tid att avsluta arbetet grips jag av panik.',
    'Jag tänker ibland att en persons intelligens är något som egentligen inte går att förändra: den är en naturgåva.',
    'Problem hemma eller med vänner gör att jag försummar mitt skolarbete.',
    'Om jag misslyckas känner jag mig benägen att försöka igen.',
    'När jag börjar studera kontrollerar jag vad jag behöver göra.',
    'När jag tänker på det jag behöver lära mig händer det att jag ser det som alltför svårt.',
    'Jag tänker att en persons förmåga beror på den uthållighet och ansträngning personen lägger på studierna.',
    'När min lärare förklarar något börjar jag tänka på annat och följer inte med i förklaringen.',
    'När jag läser återskapar jag med min fantasi de situationer, personer eller händelser som skildras.',
    'Jag tänker att det i studier, liksom i arbete, är viktigt att lära sig arbeta tillsammans.',
    'Om jag är på dåligt humör har jag svårt att koncentrera mig på studierna.',
    'När ett muntligt förhör går bra tänker jag att läraren var förstående och ställde lätta frågor.',
    'När jag studerar distraheras jag av dagdrömmar, projekt och planer av alla slag.',
    'Jag förstår bättre om läraren använder skisser och diagram på tavlan när hen förklarar.',
    'Det händer att jag både hemma och utanför hemmet gärna talar om det jag gör i skolan.',
    'Om jag har ett känslomässigt problem på grund av dåliga relationer med andra eller med mina föräldrar kan jag inte ägna mig åt studierna.',
    'Om jag är förberedd är jag säker på att jag klarar en uppgift eller ett muntligt förhör bra.',
    'Jag tänker ibland att man genom seriös ansträngning också kan utveckla sin intelligens.',
    'När jag stöter på en svårighet försöker jag övervinna den genom att öka min ansträngning och koncentration.',
    'Jag undviker att ställa frågor eftersom jag tror att jag stör läraren.',
    'När jag får en oväntad fråga låser jag mig och kan inte längre prata.',
    'Jag har svårt att avgöra om ett begrepp eller ett ämne är oklart för mig.',
    'När jag deltar i grupparbete får jag intrycket att jag slösar bort tid.',
    'För att bättre minnas det jag studerar försöker jag koppla samman de olika idéerna.',
];

const QSAR_EN: string[] = [
    'I try to understand thoroughly what I read and reflect on it.',
    'When I receive a poor mark, I become discouraged.',
    'I try to find relationships between what I learn and what I already know.',
    'I feel capable of completing my study commitments successfully.',
    'I feel very uncomfortable during a written assignment or oral assessment even when I am well prepared.',
    'When an oral assessment goes well, I think I was lucky that the teacher asked me something I knew.',
    'I take notes during lessons because this helps me pay closer attention.',
    'When I begin a classroom assignment, I am confident that I can do well.',
    'During an oral assessment, fear of making a mistake bothers me and I perform worse.',
    'When I do not succeed in an assignment or oral assessment, I think the reason is that I did not study seriously.',
    'While studying, I ask myself questions or do exercises to check whether I have understood properly.',
    'I try to link what I am studying with my experiences.',
    'When I do not succeed in an assignment or oral assessment, I think I was asked something too difficult.',
    'I try to see how what I study could apply to my everyday life.',
    'When I read a text, I mark the most important points in it.',
    'When I must face an oral assessment or written assignment, I am so nervous that I cannot express myself well.',
    'When an oral assessment goes well, I think I did well to study with so much effort.',
    'I organise my study according to the time I have available.',
    'When I learn something new, I try to find an example to which it can apply.',
    'I create outlines, diagrams, maps or summary tables to summarise what I study.',
    'When I do well at school, I think it is because I am a truly capable person.',
    'I become nervous straight away when faced with a question or problem that I do not immediately understand.',
    'I make drawings or sketches that help me understand what I am studying.',
    'While studying or listening to a lesson, links with other subjects I have already studied come to mind.',
    'I go to school having completed my homework and studied my lessons.',
    'When I do well, I think it is because the task was easy.',
    'Even if I do not like the subject, I still make an effort to succeed.',
    'When I study, I make outlines to understand and remember better.',
    'When faced with a demanding task, I feel encouraged to try harder.',
    'I think that not succeeding at school depends on the intelligence a person has.',
    'I do my homework in good time.',
    'Even if a task seems boring, I still try to finish it.',
    'I think that succeeding at school depends on the persistence and effort put into studying.',
    'I study only when I am going to be assessed, rather than systematically day by day.',
    'When I decide to do something, I finish it even if it requires effort.',
    'When reviewing lessons, I find it useful to use drawings, diagrams or summary tables in the text.',
    'I feel confident that I can obtain good marks.',
    'If I realise that I no longer have enough time to finish a task, I panic.',
    'I sometimes think that a person\'s intelligence is something that cannot really change: it is a natural gift.',
    'Before studying, I check what I need to do.',
    'While the teacher is explaining, I find myself becoming distracted.',
    'I understand better if the teacher uses sketches and diagrams on the board while explaining.',
    'To remember what I study better, I try to link the different ideas together.',
    'While studying, I sometimes find myself thinking about other things.',
    'If I have prepared for an assignment or oral assessment, I am confident that I will do well.',
    'When I encounter a difficulty, I make a greater effort to overcome it.',
];

const QSAR_SV: string[] = [
    'Jag försöker förstå ordentligt det jag läser och reflekterar över det.',
    'När jag får ett dåligt betyg blir jag nedstämd.',
    'Jag försöker hitta samband mellan det jag lär mig och det jag redan vet.',
    'Jag känner att jag klarar av att genomföra mina studieåtaganden med framgång.',
    'Jag känner mig mycket obekväm under en skriftlig uppgift eller ett muntligt förhör även när jag är väl förberedd.',
    'När ett muntligt förhör går bra tänker jag att jag hade tur som fick en fråga jag kunde.',
    'Jag antecknar under lektionerna eftersom det hjälper mig att vara mer uppmärksam.',
    'När jag börjar med en uppgift i klassrummet är jag övertygad om att jag kan göra bra ifrån mig.',
    'Under ett muntligt förhör stör rädslan för att göra fel mig och det går sämre.',
    'När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att orsaken är att jag inte studerade seriöst.',
    'När jag studerar ställer jag frågor till mig själv eller gör övningar för att kontrollera att jag har förstått ordentligt.',
    'Jag försöker koppla det jag studerar till mina erfarenheter.',
    'När jag inte lyckas med en uppgift eller ett muntligt förhör tänker jag att jag fick något som var för svårt.',
    'Jag försöker se hur det jag studerar skulle kunna användas i mitt vardagsliv.',
    'När jag läser en text markerar jag det viktigaste i texten.',
    'När jag ska göra ett muntligt förhör eller en skriftlig uppgift är jag så nervös att jag inte kan uttrycka mig bra.',
    'När ett muntligt förhör går bra tänker jag att jag gjorde rätt som studerade så flitigt.',
    'Jag organiserar mina studier utifrån den tid jag har till förfogande.',
    'När jag lär mig något nytt försöker jag hitta ett exempel där det kan användas.',
    'Jag gör dispositioner, diagram, kartor eller sammanfattande tabeller för att sammanfatta det jag studerar.',
    'När det går bra för mig i skolan tänker jag att det beror på att jag är en verkligt kompetent person.',
    'Jag blir genast nervös inför en fråga eller ett problem som jag inte förstår direkt.',
    'Jag gör teckningar eller skisser som hjälper mig att förstå det jag studerar.',
    'När jag studerar eller lyssnar på en lektion kommer jag att tänka på samband med andra ämnen jag redan har studerat.',
    'Jag går till skolan efter att ha gjort läxorna och studerat lektionerna.',
    'När jag lyckas bra tänker jag att det beror på att uppgiften var lätt.',
    'Även om jag inte tycker om ämnet anstränger jag mig ändå för att lyckas.',
    'När jag studerar gör jag dispositioner för att förstå och minnas bättre.',
    'Inför en krävande uppgift känner jag mig stimulerad att anstränga mig mer.',
    'Jag tänker att misslyckanden i skolan beror på den intelligens en person har.',
    'Jag gör mina läxor i god tid.',
    'Även om en uppgift verkar tråkig försöker jag ändå avsluta den.',
    'Jag tänker att framgång i skolan beror på uthålligheten och ansträngningen i studierna.',
    'Jag studerar bara när jag ska förhöras och inte systematiskt dag för dag.',
    'När jag bestämmer mig för att göra något slutför jag det även om det kräver ansträngning.',
    'När jag repeterar lektioner tycker jag att det är användbart att använda teckningar, diagram eller sammanfattande tabeller i texten.',
    'Jag känner mig säker på att jag kan få bra betyg.',
    'Om jag märker att jag inte längre har tid att avsluta ett arbete grips jag av panik.',
    'Jag tänker ibland att en persons intelligens är något som egentligen inte går att förändra: den är en naturgåva.',
    'Innan jag studerar kontrollerar jag vad jag behöver göra.',
    'När läraren förklarar händer det att jag blir distraherad.',
    'Jag förstår bättre om läraren använder skisser och diagram på tavlan när hen förklarar.',
    'För att bättre minnas det jag studerar försöker jag koppla samman de olika idéerna.',
    'När jag studerar händer det att jag tänker på annat.',
    'Om jag har förberett mig inför en uppgift eller ett muntligt förhör är jag säker på att jag kommer att lyckas.',
    'När jag möter en svårighet anstränger jag mig mer för att övervinna den.',
];

const EN_BASE = {
    testBadge: 'TEST VERSION',
    warningTitle: 'Administration for instrument testing only',
    warningBody: 'This English/Swedish version is being tested as an instrument adaptation. Any profile shown after submission is an experimental preview, not a validated assessment, and must not be used for individual educational, guidance or diagnostic decisions.',
    instructions: 'For each statement, select how often it usually describes what you do or feel. Answer according to what you actually do or feel, not what you would like to do.',
    privacyNote: 'Responses are used only in this browser view to calculate the experimental profile preview below. They are not stored.',
    scale: ['Never or almost never', 'Sometimes', 'Often', 'Always or almost always'] as [string, string, string, string],
    progress: 'answered',
    missingAnswers: 'Answer every statement before submitting the test administration.',
    submit: 'Submit test administration',
    submittedTitle: 'Experimental factor profile',
    submittedBody: 'This profile is a raw response-frequency preview for testing the adapted instrument. It is not a validated result, a normative stanine profile, or a basis for individual decisions. Your answers have not been stored.',
    profileMethod: 'Bars show the average selected frequency for the items assigned to each factor (1 to 4); oppositely worded items are reverse-coded within their factor. No English or Swedish norms have been applied, and the adapted factor configuration remains subject to scientific review.',
    cognitiveTitle: 'Cognitive and metacognitive factors',
    affectiveTitle: 'Affective and motivational factors',
    rawAverage: 'Raw frequency average',
    restart: 'Complete again',
    back: 'Back to test administrations',
};

const SV_BASE = {
    testBadge: 'TESTVERSION',
    warningTitle: 'Genomförandet används endast för att testa instrumentet',
    warningBody: 'Denna engelska/svenska version testas som en anpassning av instrumentet. Varje profil som visas efter inskickning är en experimentell förhandsvisning, inte en validerad bedömning, och får inte användas för individuella utbildnings-, väglednings- eller diagnostiska beslut.',
    instructions: 'För varje påstående väljer du hur ofta det vanligtvis beskriver vad du gör eller känner. Svara utifrån vad du faktiskt gör eller känner, inte vad du skulle vilja göra.',
    privacyNote: 'Svaren används endast i denna webbläsarvy för att beräkna den experimentella profilförhandsvisningen nedan. De sparas inte.',
    scale: ['Aldrig eller nästan aldrig', 'Ibland', 'Ofta', 'Alltid eller nästan alltid'] as [string, string, string, string],
    progress: 'besvarade',
    missingAnswers: 'Besvara alla påståenden innan du skickar in testgenomförandet.',
    submit: 'Skicka in testgenomförande',
    submittedTitle: 'Experimentell faktorprofil',
    submittedBody: 'Denna profil är en rå förhandsvisning av svarsfrekvenser för att testa det anpassade instrumentet. Den är inte ett validerat resultat, en normativ stanineprofil eller underlag för individuella beslut. Dina svar har inte sparats.',
    profileMethod: 'Staplarna visar den genomsnittliga valda frekvensen för de påståenden som hör till varje faktor (1 till 4); omvänt formulerade påståenden omkodas inom sin faktor. Inga engelska eller svenska normer har tillämpats, och den anpassade faktorkonfigurationen behöver fortfarande vetenskaplig granskning.',
    cognitiveTitle: 'Kognitiva och metakognitiva faktorer',
    affectiveTitle: 'Affektiva och motivationella faktorer',
    rawAverage: 'Rått frekvensmedelvärde',
    restart: 'Fyll i igen',
    back: 'Tillbaka till testgenomföranden',
};

export const TEST_ADMINISTRATIONS: Record<AdministrationInstrument, Record<AdministrationLocale, AdministrationCopy>> = {
    QSA: {
        en: {
            ...EN_BASE,
            shortName: 'QSA',
            title: 'Learning Strategies Questionnaire (QSA)',
            items: QSA_EN,
        },
        sv: {
            ...SV_BASE,
            shortName: 'QSA',
            title: 'Frågeformulär om inlärningsstrategier (QSA)',
            items: QSA_SV,
        },
    },
    QSAr: {
        en: {
            ...EN_BASE,
            shortName: 'QSAr',
            title: 'Learning Strategies Questionnaire - Short Form (QSAr)',
            items: QSAR_EN,
        },
        sv: {
            ...SV_BASE,
            shortName: 'QSAr',
            title: 'Frågeformulär om inlärningsstrategier - kortversion (QSAr)',
            items: QSAR_SV,
        },
    },
};

export function getTestAdministration(
    instrument: string,
    locale: string,
): AdministrationCopy | null {
    if (instrument !== 'QSA' && instrument !== 'QSAr') return null;
    if (locale !== 'en' && locale !== 'sv') return null;
    return TEST_ADMINISTRATIONS[instrument][locale];
}
